apiVersion: v1
kind: ConfigMap
metadata:
  name: oms-env
  namespace: openmakersuite
  labels:
    app.kubernetes.io/name: openmakersuite
    app.kubernetes.io/part-of: openmakersuite
data:
  DEBUG: "0"
  DJANGO_SETTINGS_MODULE: "config.settings"
  ALLOWED_HOSTS: "openmakersuite.local"
  CSRF_TRUSTED_ORIGINS: "https://openmakersuite.local"
  CORS_ALLOWED_ORIGINS: "https://openmakersuite.local"
  FRONTEND_URL: "https://openmakersuite.local"
  SENTRY_ENVIRONMENT: "production"
