# Generated by Django 4.2.26 on 2025-11-10 19:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0033_location_qr_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        help_text="Type of feedback",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Feedback message")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the feedback was submitted"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feedback has been resolved",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location the feedback is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="inventory.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Severity of the security concern",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the security concern"),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the report was submitted"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this security report has been resolved",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the security report was resolved",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location where the security concern was observed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_reports",
                        to="inventory.location",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who resolved this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Task title", max_length=200)),
                ("description", models.TextField(help_text="Task description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the task",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the task was created"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the task was completed", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional due date for the task",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to complete this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_location_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_location_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this task (system if auto-created)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_location_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from_feedback",
                    models.ForeignKey(
                        blank=True,
                        help_text="Feedback that created this task (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to="location_checkins.locationfeedback",
                    ),
                ),
                (
                    "created_from_security_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security report that created this task (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to="location_checkins.securityreport",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location where the task needs to be completed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "checkin_type",
                    models.CharField(
                        choices=[
                            ("volunteer", "Volunteer"),
                            ("contractor", "Contractor"),
                            ("anonymous", "Anonymous User"),
                        ],
                        default="anonymous",
                        help_text="Type of user checking in",
                        max_length=20,
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the check-in occurred"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the check-in"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location where check-in occurred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="inventory.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_in_at"],
            },
        ),
        migrations.AddIndex(
            model_name="securityreport",
            index=models.Index(
                fields=["location", "-reported_at"],
                name="location_ch_locatio_a82084_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityreport",
            index=models.Index(
                fields=["severity", "-reported_at"],
                name="location_ch_severit_197128_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityreport",
            index=models.Index(
                fields=["is_resolved"], name="location_ch_is_reso_92110e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationtask",
            index=models.Index(
                fields=["location", "status"], name="location_ch_locatio_405d21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationtask",
            index=models.Index(
                fields=["status", "-created_at"], name="location_ch_status_58028a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationtask",
            index=models.Index(
                fields=["assigned_to", "status"], name="location_ch_assigne_fb4980_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationfeedback",
            index=models.Index(
                fields=["location", "-submitted_at"],
                name="location_ch_locatio_85c606_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="locationfeedback",
            index=models.Index(
                fields=["feedback_type", "-submitted_at"],
                name="location_ch_feedbac_3b1d19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="locationfeedback",
            index=models.Index(
                fields=["is_resolved"], name="location_ch_is_reso_c9b14b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationcheckin",
            index=models.Index(
                fields=["location", "-checked_in_at"],
                name="location_ch_locatio_c935e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="locationcheckin",
            index=models.Index(
                fields=["checkin_type", "-checked_in_at"],
                name="location_ch_checkin_a64908_idx",
            ),
        ),
    ]
