# Generated by Django 4.2.26 on 2025-11-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_location_qr_code"),
        ("location_checkins", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="securityreport",
            name="location_ch_severit_197128_idx",
        ),
        migrations.RemoveField(
            model_name="securityreport",
            name="severity",
        ),
        migrations.AddField(
            model_name="securityreport",
            name="is_urgent",
            field=models.BooleanField(
                default=False, help_text="Whether this needs immediate attention"
            ),
        ),
        migrations.AddField(
            model_name="securityreport",
            name="report_type",
            field=models.CharField(
                choices=[("cleaning", "Needs Cleaning"), ("safety", "Safety Concern")],
                default="safety",
                help_text="Type of report: cleaning or safety concern",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="securityreport",
            name="description",
            field=models.TextField(blank=True, help_text="Optional additional details"),
        ),
        migrations.AlterField(
            model_name="securityreport",
            name="location",
            field=models.ForeignKey(
                help_text="Location where the concern was observed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_reports",
                to="inventory.location",
            ),
        ),
        migrations.AddIndex(
            model_name="securityreport",
            index=models.Index(
                fields=["report_type", "-reported_at"], name="location_ch_report__5eb06e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityreport",
            index=models.Index(
                fields=["is_urgent", "-reported_at"], name="location_ch_is_urge_f155f7_idx"
            ),
        ),
    ]
