# Generated by Django 5.1.15 on 2026-05-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location_checkins", "0003_locationcheckin_traffic_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="locationcheckin",
            new_name="location_ch_source_ae5cf4_idx",
            old_name="location_ch_source_ci_idx",
        ),
    ]
