# Generated by Django 4.2.26 on 2025-12-09 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="info",
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Notification title", max_length=200)),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "read",
                    models.BooleanField(
                        default=False, help_text="Whether the notification has been read"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the notification was created"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional URL to navigate to when notification is clicked",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who will receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "read"], name="notificatio_user_id_878a13_idx"),
                    models.Index(
                        fields=["user", "-created_at"], name="notificatio_user_id_05b4bc_idx"
                    ),
                ],
            },
        ),
    ]
