# Generated by Django 4.2.27 on 2025-12-20 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, help_text="Enable email notifications"),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(default=True, help_text="Enable in-app notifications"),
                ),
                (
                    "supply_alerts",
                    models.BooleanField(
                        default=True, help_text="Receive alerts about low supplies"
                    ),
                ),
                (
                    "maintenance_alerts",
                    models.BooleanField(
                        default=True, help_text="Receive alerts about maintenance needs"
                    ),
                ),
                (
                    "order_updates",
                    models.BooleanField(
                        default=True, help_text="Receive updates about order status"
                    ),
                ),
                (
                    "system_notifications",
                    models.BooleanField(default=True, help_text="Receive system notifications"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the preferences were created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the preferences were last updated"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns these preferences",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
