# Generated by Django 5.1.14 on 2025-12-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="recent_pages_limit",
            field=models.PositiveIntegerField(
                default=8, help_text="Maximum number of recent pages to display in sidebar (1-50)"
            ),
        ),
    ]
