# Generated by Django 5.1.14 on 2025-12-21 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationpreference_recent_pages_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="recent_pages_limit",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Maximum number of recent pages to display in sidebar (1-50)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]
