# Generated by Django 5.1.15 on 2026-06-17 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notificationpreference_recent_pages_limit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_token",
                    models.CharField(
                        db_index=True,
                        help_text="Opaque server-minted device id (stored client-side in a signed cookie)",
                        max_length=128,
                    ),
                ),
                (
                    "fingerprint_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the client JS fingerprint; populated in FP4, null until then",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User-Agent string captured for this device"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Approximate IP address last seen for this device",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional user-friendly label for this device",
                        max_length=120,
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this device was first seen"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="When this device was most recently seen"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this device is known for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "device_token"),
                        name="notifications_knowndevice_unique_user_token",
                    )
                ],
            },
        ),
    ]
