# Generated by Django 4.2.26 on 2025-11-17 21:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0038_add_inventory_item_ownership"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Checklist name, e.g., 'Monthly Scrum Walk'",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this checklist covers",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this checklist is currently available",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether unauthenticated users can access this checklist",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this checklist",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sig",
                    models.ForeignKey(
                        help_text="SIG (Group) that owns this checklist",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        help_text="Name/handle for unauthenticated users",
                        max_length=200,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When completion started"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When checklist was completed", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="checklists.checklist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user completing the checklist",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_number",
                    models.IntegerField(
                        help_text="Order of this step in the checklist"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Step name/description", max_length=200),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True, help_text="Whether this step must be completed"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional instructions for this step"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated asset to scan for this step",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_steps",
                        to="inventory.asset",
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="checklists.checklist",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated inventory item to scan for this step",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_steps",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated location to scan for this step",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_steps",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["checklist", "step_number"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistStepCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the QR code was scanned"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="User notes for this step"),
                ),
                (
                    "completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_completions",
                        to="checklists.checklistcompletion",
                    ),
                ),
                (
                    "scanned_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which asset was scanned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_step_completions",
                        to="inventory.asset",
                    ),
                ),
                (
                    "scanned_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which inventory item was scanned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_step_completions",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "scanned_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which location was scanned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_step_completions",
                        to="inventory.location",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="checklists.checkliststep",
                    ),
                ),
            ],
            options={
                "ordering": ["completion", "step__step_number"],
                "indexes": [
                    models.Index(
                        fields=["completion", "step"],
                        name="checklists__complet_569733_idx",
                    ),
                    models.Index(
                        fields=["scanned_at"], name="checklists__scanned_d3bb82_idx"
                    ),
                ],
                "unique_together": {("completion", "step")},
            },
        ),
        migrations.AddIndex(
            model_name="checkliststep",
            index=models.Index(
                fields=["checklist", "step_number"],
                name="checklists__checkli_6b9518_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checkliststep",
            unique_together={("checklist", "step_number")},
        ),
        migrations.AddIndex(
            model_name="checklistcompletion",
            index=models.Index(
                fields=["checklist", "status"], name="checklists__checkli_ba44ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistcompletion",
            index=models.Index(
                fields=["user", "status"], name="checklists__user_id_634145_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistcompletion",
            index=models.Index(
                fields=["status", "-started_at"], name="checklists__status_5a34d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(
                fields=["sig", "is_active"], name="checklists__sig_id_7fc559_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(
                fields=["is_active", "is_public"], name="checklists__is_acti_9416d7_idx"
            ),
        ),
    ]
