# Generated by Django 5.1.15 on 2026-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkliststep",
            name="requires_photo",
            field=models.BooleanField(
                default=False, help_text="If true, scanning this step requires a photo upload."
            ),
        ),
        migrations.AddField(
            model_name="checkliststepcompletion",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo captured while completing this step",
                null=True,
                upload_to="checklist_step_photos/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="checkliststepcompletion",
            name="photo_caption",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
