# Generated by Django 6.0.6 on 2026-07-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0002_checkliststep_requires_photo_and_more"),
        ("inventory", "0087_ownership_abstraction"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="checkliststep",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("asset__isnull", False),
                        ("location__isnull", True),
                        ("inventory_item__isnull", True),
                    ),
                    models.Q(
                        ("location__isnull", False),
                        ("asset__isnull", True),
                        ("inventory_item__isnull", True),
                    ),
                    models.Q(
                        ("inventory_item__isnull", False),
                        ("asset__isnull", True),
                        ("location__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="checklist_step_exactly_one_target",
            ),
        ),
    ]
