"""Service layer for reorder-queue purchase-order + receiving workflow (#883).

Views keep the serializers as the request/response boundary and keep their
``record_audit_event`` calls; the workflow bodies live in these services.
"""

from .approvals import (
    APPROVED_REQUESTS_ATTR,
    PO_ELIGIBLE_STATUSES,
    approved_requests_prefetch,
    get_approved_reorder_request,
)
from .line_entry import (
    LineEntryError,
    add_asset_line_item,
    add_freeform_line_item,
    add_line_item,
    assert_addable,
    default_quantity,
    default_unit_cost,
    lookup_candidates,
    repeat_quantity,
    resolve_asset,
    resolve_identifier,
    resolve_item_supplier,
    serialize_candidate,
    serialize_lookup,
)
from .numbering import next_po_number
from .purchase_orders import (
    add_business_days,
    apply_line_quantity,
    confirm_order,
    create_purchase_order,
    mark_sent,
    recalculate_estimated_total,
    update_reorder_requests_from_po,
    void_line_item,
    void_po,
)
from .receiving import (
    LineReceipt,
    SerialCapture,
    build_receiving_worksheet,
    close_lines_short,
    close_linked_reorder_request,
    create_lead_time_log,
    line_scan_codes,
    mark_delivered_receipt,
    outstanding_lines,
    receive_delivery,
    refresh_receipt_status,
    serialized_receipt_targets,
)

__all__ = [
    "LineEntryError",
    "add_asset_line_item",
    "add_freeform_line_item",
    "add_line_item",
    "assert_addable",
    "default_quantity",
    "default_unit_cost",
    "lookup_candidates",
    "repeat_quantity",
    "resolve_asset",
    "resolve_identifier",
    "resolve_item_supplier",
    "serialize_candidate",
    "serialize_lookup",
    "APPROVED_REQUESTS_ATTR",
    "PO_ELIGIBLE_STATUSES",
    "approved_requests_prefetch",
    "get_approved_reorder_request",
    "add_business_days",
    "apply_line_quantity",
    "confirm_order",
    "create_purchase_order",
    "mark_sent",
    "next_po_number",
    "recalculate_estimated_total",
    "update_reorder_requests_from_po",
    "void_line_item",
    "void_po",
    "LineReceipt",
    "SerialCapture",
    "build_receiving_worksheet",
    "close_lines_short",
    "close_linked_reorder_request",
    "create_lead_time_log",
    "mark_delivered_receipt",
    "line_scan_codes",
    "outstanding_lines",
    "receive_delivery",
    "refresh_receipt_status",
    "serialized_receipt_targets",
]
