# Generated by Django 6.0.6 on 2026-06-27 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AprilTagAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("tag36h11", "AprilTag 36h11 (587 IDs)"),
                            ("tag36h10", "AprilTag 36h10 (2320 IDs)"),
                        ],
                        default="tag36h11",
                        help_text="AprilTag dictionary this ID is drawn from.",
                        max_length=32,
                    ),
                ),
                ("tag_id", models.PositiveSmallIntegerField()),
                ("object_id", models.PositiveBigIntegerField()),
                ("allocated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "AprilTag assignment",
                "verbose_name_plural": "AprilTag assignments",
                "ordering": ["family", "tag_id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="fiducials_a_content_60c3ff_idx"
                    ),
                    models.Index(
                        fields=["family", "released_at"], name="fiducials_a_family_9685c0_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("family", "tag_id"),
                        name="unique_active_apriltag_per_family",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("content_type", "object_id"),
                        name="unique_active_apriltag_per_subject",
                    ),
                ],
            },
        ),
    ]
