# Generated by Django 4.2.25 on 2025-11-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0002_purchaseorder_purchaseorderitem_orderdelivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reorderrequest",
            name="delivery_tracking_url",
            field=models.URLField(blank=True, help_text="Link to shipping/delivery tracking"),
        ),
        migrations.AddField(
            model_name="reorderrequest",
            name="invoice_number",
            field=models.CharField(
                blank=True, help_text="Invoice/receipt number for transparency", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="reorderrequest",
            name="invoice_url",
            field=models.URLField(
                blank=True, help_text="Link to invoice/receipt (if publicly available)"
            ),
        ),
        migrations.AddField(
            model_name="reorderrequest",
            name="public_notes",
            field=models.TextField(
                blank=True, help_text="Public notes visible in transparency view"
            ),
        ),
        migrations.AddField(
            model_name="reorderrequest",
            name="purchase_order_url",
            field=models.URLField(blank=True, help_text="Link to purchase order document"),
        ),
        migrations.AddField(
            model_name="reorderrequest",
            name="supplier_url",
            field=models.URLField(blank=True, help_text="Link to supplier item page"),
        ),
    ]
