# Generated by Django 4.2.25 on 2025-11-02 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reorder_queue", "0003_reorderrequest_delivery_tracking_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="carrier",
            field=models.CharField(
                blank=True,
                help_text="Shipping carrier (UPS, FedEx, USPS, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the order was shipped by the supplier",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="shipped_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who updated shipping information",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipped_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                help_text="Tracking number from shipping carrier",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tracking_url",
            field=models.URLField(
                blank=True, help_text="Direct link to carrier tracking page"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent to Supplier"),
                    ("confirmed", "Confirmed by Supplier"),
                    ("shipped", "Shipped"),
                    ("partially_received", "Partially Received"),
                    ("received", "Fully Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
