# Generated by Django 4.2.25 on 2025-11-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0004_purchaseorder_carrier_purchaseorder_shipped_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="carrier",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="shipped_at",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="shipped_by",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="tracking_number",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="tracking_url",
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent to Supplier"),
                    ("confirmed", "Confirmed by Supplier"),
                    ("partially_received", "Partially Received"),
                    ("received", "Fully Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WebHook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Descriptive name for this webhook", max_length=200),
                ),
                ("url", models.URLField(help_text="Webhook endpoint URL to POST notifications to")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reorder_request_created", "Reorder Request Created"),
                            ("reorder_request_approved", "Reorder Request Approved"),
                            ("reorder_request_ordered", "Reorder Request Ordered"),
                            ("reorder_request_received", "Reorder Request Received"),
                            ("item_low_stock", "Item Low Stock"),
                            ("purchase_order_created", "Purchase Order Created"),
                            ("delivery_received", "Delivery Received"),
                        ],
                        help_text="Type of event that triggers this webhook",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable or disable this webhook without deleting it"
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Optional secret key for HMAC signature verification",
                        max_length=255,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional custom HTTP headers to send with webhook (as JSON object)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what this webhook does"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, help_text="When this webhook was last triggered", null=True
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successful webhook deliveries"
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of failed webhook deliveries"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last error message if webhook delivery failed"
                    ),
                ),
            ],
            options={
                "ordering": ["event_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "is_active"], name="reorder_que_event_t_0c982f_idx"
                    ),
                    models.Index(
                        fields=["is_active", "-last_triggered_at"],
                        name="reorder_que_is_acti_8687f4_idx",
                    ),
                ],
            },
        ),
    ]
