# Generated by Django 4.2.25 on 2025-11-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0005_remove_purchaseorder_carrier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("reorder_request_created", "Reorder Request Created"),
                    ("reorder_request_approved", "Reorder Request Approved"),
                    ("reorder_request_ordered", "Reorder Request Ordered"),
                    ("reorder_request_received", "Reorder Request Received"),
                    ("item_low_stock", "Item Low Stock"),
                    ("purchase_order_created", "Purchase Order Created"),
                    ("delivery_received", "Delivery Received"),
                    ("fixture_refill_requested", "Fixture Refill Requested"),
                ],
                help_text="Type of event that triggers this webhook",
                max_length=50,
            ),
        ),
    ]
