# Generated by Django 4.2.26 on 2025-11-14 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reorder_queue", "0009_add_asset_to_purchaseorderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorderitem",
            options={"ordering": ["purchase_order", "item_supplier__item__name", "asset__name"]},
        ),
        migrations.RemoveConstraint(
            model_name="purchaseorderitem",
            name="purchase_order_item_must_have_item_or_asset",
        ),
        migrations.RenameIndex(
            model_name="purchaseorderitem",
            new_name="reorder_que_purchas_b7930a_idx",
            old_name="reorder_que_purchas_asset_i_idx",
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="is_voided",
            field=models.BooleanField(
                default=False,
                help_text="Whether this line item has been voided (e.g., item discontinued by supplier)",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="void_reason",
            field=models.TextField(blank=True, help_text="Reason for voiding this line item"),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="voided_at",
            field=models.DateTimeField(
                blank=True, help_text="When this line item was voided", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who voided this line item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_purchase_order_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("asset__isnull", True), ("item_supplier__isnull", False)),
                    models.Q(("asset__isnull", False), ("item_supplier__isnull", True)),
                    _connector="OR",
                ),
                name="purchase_order_item_must_have_item_or_asset",
            ),
        ),
    ]
