# Generated by Django 4.2.26 on 2025-12-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0011_make_po_number_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhook",
            options={
                "ordering": ["event_type", "name"],
                "permissions": [("manage_webhooks", "Can manage webhooks")],
            },
        ),
    ]
