# Generated by Django 4.2.27 on 2025-12-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0011_make_po_number_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Freeform description for line items not linked to inventory items or assets",
                max_length=500,
            ),
        ),
    ]
