# Generated by Django 5.1.14 on 2025-12-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0012_add_description_to_purchaseorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="order_in_packages",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of packages ordered (calculated from quantity_ordered / quantity_per_package for inventory items)",
            ),
        ),
    ]
