# Generated by Django 5.1.14 on 2025-12-21 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0042_add_resolved_by_to_asset_problem"),
        ("reorder_queue", "0013_add_order_in_packages_to_purchaseorderitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="purchaseorderitem",
            name="purchase_order_item_must_have_item_or_asset",
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("asset__isnull", True),
                             ("item_supplier__isnull", False)),
                    models.Q(("asset__isnull", False),
                             ("item_supplier__isnull", True)),
                    models.Q(
                        ("asset__isnull", True),
                        ("description__gt", ""),
                        ("item_supplier__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="purchase_order_item_must_have_item_or_asset",
            ),
        ),
    ]
