# Generated by Django 5.1.14 on 2025-12-21 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0042_add_resolved_by_to_asset_problem"),
        ("reorder_queue", "0014_update_constraint_allow_freeform_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="purchaseorderitem",
            name="purchase_order_item_must_have_item_or_asset",
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("asset__isnull", True),
                             ("item_supplier__isnull", False)),
                    models.Q(("asset__isnull", False),
                             ("item_supplier__isnull", True)),
                    models.Q(
                        ("asset__isnull", True),
                        ("item_supplier__isnull", True),
                        models.Q(("description", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="purchase_order_item_must_have_item_or_asset",
            ),
        ),
    ]
