# Generated by Django 5.1.15 on 2026-04-27 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0016_fix_order_in_packages_column_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="void_reason",
            field=models.TextField(blank=True, help_text="Reason for voiding this purchase order"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="voided_at",
            field=models.DateTimeField(
                blank=True, help_text="When this purchase order was voided", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who voided this purchase order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_purchase_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent to Supplier"),
                    ("confirmed", "Confirmed by Supplier"),
                    ("partially_received", "Partially Received"),
                    ("received", "Fully Received"),
                    ("cancelled", "Cancelled"),
                    ("voided", "Voided"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
