# Generated by Django 5.1.15 on 2026-04-27 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0017_purchaseorder_void_reason_purchaseorder_voided_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="sales_order_number",
            field=models.CharField(
                blank=True,
                help_text="Sales order number associated with this purchase order",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_order_number",
            field=models.CharField(
                blank=True,
                help_text="Order number assigned by the supplier (e.g. their internal order ID)",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached document",
                        upload_to="purchase_orders/attachments/%Y/%m/",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        help_text="The purchase order this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reorder_queue.purchaseorder",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
