# Generated by Django 6.0.6 on 2026-06-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reorder_queue', '0020_webhookauditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='actual_shipment_date',
            field=models.DateField(blank=True, help_text='Actual date the supplier reported this line item shipped. Separate from delivery — scantty / the web UI flip this when a supplier confirms shipment so the operator can see the gap between expected_shipment_date and reality.', null=True),
        ),
    ]
