# Generated by Django 5.2.14 on 2026-06-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0021_purchaseorderitem_actual_shipment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("po_create", "Purchase order created"),
                    ("po_void", "Purchase order voided"),
                    ("po_line_void", "Purchase order line item voided"),
                    ("po_mark_delivered", "Purchase order marked delivered"),
                    ("po_receive_items", "Purchase order line items received"),
                    ("attachment_add", "Attachment added"),
                    ("attachment_remove", "Attachment removed"),
                ],
                max_length=32,
            ),
        ),
    ]
