# Generated by Django 6.0.7 on 2026-07-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_workordermaterialusage_purchase_order_item'),
        ('reorder_queue', '0023_alter_purchaseorderauditevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Work order this line was ordered for. Receiving it records the received quantity and its cost as a material on that work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='inventory.workorder'),
        ),
    ]
