# Generated by Django 6.0.7 on 2026-07-27 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0107_supplieragreement'),
        ('reorder_queue', '0024_purchaseorderitem_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_agreement',
            field=models.ForeignKey(blank=True, help_text='Purchase/pricing agreement this order was placed under, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.supplieragreement'),
        ),
    ]
