# Generated by Django 6.0.7 on 2026-07-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0107_supplieragreement'),
        ('reorder_queue', '0025_purchaseorder_supplier_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='owning_group',
            field=models.ForeignKey(blank=True, help_text='Committee (SIG) this order was placed on behalf of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_purchaseorder_owned', to='auth.group'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Work order this whole order was placed for (attribution only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.workorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='owning_group',
            field=models.ForeignKey(blank=True, help_text='Committee (SIG) this line was ordered on behalf of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_purchaseorderitem_owned', to='auth.group'),
        ),
    ]
