# Generated by Django 6.0.7 on 2026-07-30 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reorder_queue', '0026_purchaseorder_owning_group_purchaseorder_work_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_terms',
            field=models.CharField(blank=True, choices=[('fob_origin', 'FOB Origin'), ('fob_destination', 'FOB Destination'), ('prepaid', 'Prepaid'), ('collect', 'Collect'), ('third_party', 'Third Party')], help_text='Freight terms — who pays to ship this order', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('due_on_receipt', 'Due on Receipt'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_60', 'Net 60'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], help_text='Payment terms agreed with the supplier', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='How urgently this order needs to be placed/filled', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the order was actually placed (may be backdated)'),
        ),
    ]
