# Generated by Django 6.0.7 on 2026-08-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0027_purchaseorder_freight_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="kit_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Component breakdown captured when this kit line was ordered. Receiving credits these components, not the kit's current definition. NULL for non-kit lines.",
                null=True,
            ),
        ),
    ]
