# Generated by Django 6.0.7 on 2026-08-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0028_purchaseorderitem_kit_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("po_create", "Purchase order created"),
                    ("po_send", "Purchase order sent to supplier"),
                    ("po_void", "Purchase order voided"),
                    ("po_line_add", "Purchase order line items added"),
                    ("po_line_void", "Purchase order line item voided"),
                    ("po_mark_delivered", "Purchase order marked delivered"),
                    ("po_receive_items", "Purchase order line items received"),
                    ("attachment_add", "Attachment added"),
                    ("attachment_remove", "Attachment removed"),
                ],
                max_length=32,
            ),
        ),
    ]
