# Generated by Django 6.0.7 on 2026-08-25 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0030_alter_purchaseorderauditevent_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="closed_short_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the outstanding balance on this line was written off as never arriving. Null means the line is still expecting the rest.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="closed_short_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who declared the outstanding balance would not arrive",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_short_purchase_order_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="closed_short_reason",
            field=models.TextField(
                blank=True,
                help_text="Why the outstanding balance was written off (backorder cancelled, vendor short-shipped, ...)",
            ),
        ),
    ]
