# Generated by Django 6.0.7 on 2026-08-26 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0031_purchaseorderitem_closed_short_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="reopened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a close-short on this line was taken back. Null means the line has never been reopened.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="reopened_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who took the close-short back",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reopened_purchase_order_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="reopened_reason",
            field=models.TextField(
                blank=True,
                help_text="Why the close-short was taken back (closed the wrong line, the balance shipped after all, ...)",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("po_create", "Purchase order created"),
                    ("po_send", "Purchase order sent to supplier"),
                    ("po_void", "Purchase order voided"),
                    ("po_line_add", "Purchase order line item added"),
                    ("po_line_void", "Purchase order line item voided"),
                    ("po_line_reprice", "Purchase order line item repriced"),
                    ("po_mark_delivered", "Purchase order marked delivered"),
                    ("po_receive_items", "Purchase order line items received"),
                    (
                        "po_line_reopen_short",
                        "Purchase order line item reopened after being closed short",
                    ),
                    ("attachment_add", "Attachment added"),
                    ("attachment_remove", "Attachment removed"),
                ],
                max_length=32,
            ),
        ),
    ]
