# Generated by Django 6.0.7 on 2026-08-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reorder_queue", "0032_purchaseorderitem_reopened_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("po_create", "Purchase order created"),
                    ("po_send", "Purchase order sent to supplier"),
                    ("po_void", "Purchase order voided"),
                    ("po_line_add", "Purchase order line item added"),
                    ("po_line_void", "Purchase order line item voided"),
                    ("po_line_delete", "Purchase order line item deleted"),
                    ("po_line_reprice", "Purchase order line item repriced"),
                    ("po_mark_delivered", "Purchase order marked delivered"),
                    ("po_receive_items", "Purchase order line items received"),
                    (
                        "po_line_reopen_short",
                        "Purchase order line item reopened after being closed short",
                    ),
                    ("attachment_add", "Attachment added"),
                    ("attachment_remove", "Attachment removed"),
                ],
                max_length=32,
            ),
        ),
    ]
