# Generated by Django 4.2.26 on 2025-12-09 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.CharField(help_text="Search query text", max_length=200)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("inventory", "Inventory Item"),
                            ("asset", "Asset"),
                            ("purchase_order", "Purchase Order"),
                            ("supplier", "Supplier"),
                            ("location", "Location"),
                        ],
                        help_text="Type of result",
                        max_length=20,
                    ),
                ),
                ("result_id", models.CharField(help_text="ID of the result", max_length=100)),
                (
                    "result_title",
                    models.CharField(
                        help_text="Title/name of the result for display", max_length=200
                    ),
                ),
                (
                    "searched_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the search occurred"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-searched_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-searched_at"], name="search_rece_user_id_d0e849_idx"
                    ),
                    models.Index(
                        fields=["user", "result_type", "-searched_at"],
                        name="search_rece_user_id_4031c7_idx",
                    ),
                ],
            },
        ),
    ]
