# Generated by Django 4.2.25 on 2025-11-07 07:24

import django.contrib.auth.models
import django.contrib.auth.validators
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # Create User model in state (table already exists)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="User",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("password", models.CharField(max_length=128, verbose_name="password")),
                        (
                            "last_login",
                            models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                        ),
                        (
                            "is_superuser",
                            models.BooleanField(
                                default=False,
                                help_text="Designates that this user has all permissions without explicitly assigning them.",
                                verbose_name="superuser status",
                            ),
                        ),
                        (
                            "username",
                            models.CharField(
                                error_messages={"unique": "A user with that username already exists."},
                                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                                max_length=150,
                                unique=True,
                                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                                verbose_name="username",
                            ),
                        ),
                        (
                            "first_name",
                            models.CharField(blank=True, max_length=150, verbose_name="first name"),
                        ),
                        (
                            "last_name",
                            models.CharField(blank=True, max_length=150, verbose_name="last name"),
                        ),
                        (
                            "email",
                            models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                        ),
                        (
                            "is_staff",
                            models.BooleanField(
                                default=False,
                                help_text="Designates whether the user can log into this admin site.",
                                verbose_name="staff status",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(
                                default=True,
                                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                                verbose_name="active",
                            ),
                        ),
                        (
                            "date_joined",
                            models.DateTimeField(
                                default=django.utils.timezone.now, verbose_name="date joined"
                            ),
                        ),
                        (
                            "handle",
                            models.CharField(
                                blank=True,
                                help_text="User's preferred handle/display name",
                                max_length=150,
                                null=True,
                                unique=True,
                            ),
                        ),
                        (
                            "active_directory_username",
                            models.CharField(
                                blank=True,
                                help_text="Active Directory username for integration",
                                max_length=150,
                            ),
                        ),
                        (
                            "badge_number",
                            models.CharField(
                                blank=True,
                                help_text="Badge number for physical access control",
                                max_length=50,
                                null=True,
                                unique=True,
                            ),
                        ),
                        (
                            "discord_username",
                            models.CharField(blank=True, help_text="Discord username", max_length=150),
                        ),
                        (
                            "discourse_username",
                            models.CharField(blank=True, help_text="Discourse username", max_length=150),
                        ),
                        (
                            "is_board_member",
                            models.BooleanField(
                                default=False, help_text="Indicates if user is a board member"
                            ),
                        ),
                        (
                            "is_officer",
                            models.BooleanField(default=False, help_text="Indicates if user is an officer"),
                        ),
                        (
                            "is_director",
                            models.BooleanField(default=False, help_text="Indicates if user is a director"),
                        ),
                        (
                            "groups",
                            models.ManyToManyField(
                                blank=True,
                                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.group",
                                verbose_name="groups",
                            ),
                        ),
                        (
                            "user_permissions",
                            models.ManyToManyField(
                                blank=True,
                                help_text="Specific permissions for this user.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.permission",
                                verbose_name="user permissions",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "auth_user",
                    },
                    managers=[
                        ("objects", django.contrib.auth.models.UserManager()),
                    ],
                ),
            ],
            database_operations=[],  # Table already exists
        ),
        # Create Membership model in state (table already exists)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Membership",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        (
                            "membership_type",
                            models.CharField(
                                choices=[
                                    ("monthly", "Monthly"),
                                    ("annual", "Annual"),
                                    ("complimentary", "Complimentary"),
                                    ("honorary", "Honorary"),
                                ],
                                default="monthly",
                                help_text="Type of membership",
                                max_length=20,
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("inactive", "Inactive"),
                                    ("active", "Active"),
                                    ("probative", "Probative"),
                                    ("restricted", "Restricted"),
                                    ("suspended", "Suspended"),
                                    ("terminated", "Terminated"),
                                ],
                                default="inactive",
                                help_text="Current status of the membership",
                                max_length=20,
                            ),
                        ),
                        (
                            "start_date",
                            models.DateField(
                                blank=True, help_text="When the membership started", null=True
                            ),
                        ),
                        (
                            "end_date",
                            models.DateField(
                                blank=True,
                                help_text="When the membership ends (null for active memberships)",
                                null=True,
                            ),
                        ),
                        (
                            "notes",
                            models.TextField(
                                blank=True, help_text="Additional notes about this membership"
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "users",
                            models.ManyToManyField(
                                db_table="inventory_membership_users",
                                help_text="Users associated with this membership (for families/business accounts)",
                                related_name="memberships",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "inventory_membership",
                        "verbose_name_plural": "Memberships",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            database_operations=[],  # Table already exists
        ),
    ]
