# Generated by Django 4.2.25 on 2025-11-07 07:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _create_user_table_if_not_exists(apps, schema_editor):
    """Create auth_user table if it doesn't exist (for fresh databases)."""
    vendor = schema_editor.connection.vendor
    connection = schema_editor.connection

    # Check if table exists
    if vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'auth_user'
                );
                """
            )
            exists = cursor.fetchone()[0]
    elif vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='auth_user';"
            )
            exists = cursor.fetchone() is not None
    else:
        # For other databases, assume table exists (production scenario)
        exists = True

    if not exists:
        # Create the table using database-specific SQL
        if vendor == "postgresql":
            schema_editor.execute(
                """
                CREATE TABLE auth_user (
                    id SERIAL PRIMARY KEY,
                    password VARCHAR(128) NOT NULL,
                    last_login TIMESTAMP WITH TIME ZONE,
                    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
                    username VARCHAR(150) NOT NULL UNIQUE,
                    first_name VARCHAR(150) NOT NULL DEFAULT '',
                    last_name VARCHAR(150) NOT NULL DEFAULT '',
                    email VARCHAR(254) NOT NULL DEFAULT '',
                    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    date_joined TIMESTAMP WITH TIME ZONE NOT NULL,
                    handle VARCHAR(150) UNIQUE,
                    active_directory_username VARCHAR(150) NOT NULL DEFAULT '',
                    badge_number VARCHAR(50) UNIQUE,
                    discord_username VARCHAR(150) NOT NULL DEFAULT '',
                    discourse_username VARCHAR(150) NOT NULL DEFAULT '',
                    is_board_member BOOLEAN NOT NULL DEFAULT FALSE,
                    is_officer BOOLEAN NOT NULL DEFAULT FALSE,
                    is_director BOOLEAN NOT NULL DEFAULT FALSE
                );
                """
            )
        elif vendor == "sqlite":
            schema_editor.execute(
                """
                CREATE TABLE auth_user (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    password VARCHAR(128) NOT NULL,
                    last_login DATETIME,
                    is_superuser BOOLEAN NOT NULL DEFAULT 0,
                    username VARCHAR(150) NOT NULL UNIQUE,
                    first_name VARCHAR(150) NOT NULL DEFAULT '',
                    last_name VARCHAR(150) NOT NULL DEFAULT '',
                    email VARCHAR(254) NOT NULL DEFAULT '',
                    is_staff BOOLEAN NOT NULL DEFAULT 0,
                    is_active BOOLEAN NOT NULL DEFAULT 1,
                    date_joined DATETIME NOT NULL,
                    handle VARCHAR(150) UNIQUE,
                    active_directory_username VARCHAR(150) NOT NULL DEFAULT '',
                    badge_number VARCHAR(50) UNIQUE,
                    discord_username VARCHAR(150) NOT NULL DEFAULT '',
                    discourse_username VARCHAR(150) NOT NULL DEFAULT '',
                    is_board_member BOOLEAN NOT NULL DEFAULT 0,
                    is_officer BOOLEAN NOT NULL DEFAULT 0,
                    is_director BOOLEAN NOT NULL DEFAULT 0
                );
                """
            )


def _create_membership_table_if_not_exists(apps, schema_editor):
    """Create inventory_membership table if it doesn't exist (for fresh databases)."""
    vendor = schema_editor.connection.vendor
    connection = schema_editor.connection

    # Check if table exists
    if vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'inventory_membership'
                );
                """
            )
            exists = cursor.fetchone()[0]
    elif vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='inventory_membership';"
            )
            exists = cursor.fetchone() is not None
    else:
        # For other databases, assume table exists (production scenario)
        exists = True

    if not exists:
        # Create the table using database-specific SQL
        if vendor == "postgresql":
            schema_editor.execute(
                """
                CREATE TABLE inventory_membership (
                    id SERIAL PRIMARY KEY,
                    membership_type VARCHAR(20) NOT NULL DEFAULT 'monthly',
                    status VARCHAR(20) NOT NULL DEFAULT 'inactive',
                    start_date DATE,
                    end_date DATE,
                    notes TEXT NOT NULL DEFAULT '',
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                );
                """
            )
            # Create the many-to-many table
            schema_editor.execute(
                """
                CREATE TABLE inventory_membership_users (
                    id SERIAL PRIMARY KEY,
                    membership_id INTEGER NOT NULL REFERENCES inventory_membership(id) ON DELETE CASCADE,
                    user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    UNIQUE(membership_id, user_id)
                );
                """
            )
        elif vendor == "sqlite":
            schema_editor.execute(
                """
                CREATE TABLE inventory_membership (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    membership_type VARCHAR(20) NOT NULL DEFAULT 'monthly',
                    status VARCHAR(20) NOT NULL DEFAULT 'inactive',
                    start_date DATE,
                    end_date DATE,
                    notes TEXT NOT NULL DEFAULT '',
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL
                );
                """
            )
            # Create the many-to-many table
            schema_editor.execute(
                """
                CREATE TABLE inventory_membership_users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    membership_id INTEGER NOT NULL REFERENCES inventory_membership(id) ON DELETE CASCADE,
                    user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    UNIQUE(membership_id, user_id)
                );
                """
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # Create User model in state (table may or may not exist)
        # Use SeparateDatabaseAndState to handle both fresh and existing databases
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="User",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "password",
                            models.CharField(max_length=128, verbose_name="password"),
                        ),
                        (
                            "last_login",
                            models.DateTimeField(
                                blank=True, null=True, verbose_name="last login"
                            ),
                        ),
                        (
                            "is_superuser",
                            models.BooleanField(
                                default=False,
                                help_text="Designates that this user has all permissions without explicitly assigning them.",
                                verbose_name="superuser status",
                            ),
                        ),
                        (
                            "username",
                            models.CharField(
                                error_messages={
                                    "unique": "A user with that username already exists."
                                },
                                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                                max_length=150,
                                unique=True,
                                validators=[
                                    django.contrib.auth.validators.UnicodeUsernameValidator()
                                ],
                                verbose_name="username",
                            ),
                        ),
                        (
                            "first_name",
                            models.CharField(
                                blank=True, max_length=150, verbose_name="first name"
                            ),
                        ),
                        (
                            "last_name",
                            models.CharField(
                                blank=True, max_length=150, verbose_name="last name"
                            ),
                        ),
                        (
                            "email",
                            models.EmailField(
                                blank=True, max_length=254, verbose_name="email address"
                            ),
                        ),
                        (
                            "is_staff",
                            models.BooleanField(
                                default=False,
                                help_text="Designates whether the user can log into this admin site.",
                                verbose_name="staff status",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(
                                default=True,
                                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                                verbose_name="active",
                            ),
                        ),
                        (
                            "date_joined",
                            models.DateTimeField(
                                default=django.utils.timezone.now,
                                verbose_name="date joined",
                            ),
                        ),
                        (
                            "handle",
                            models.CharField(
                                blank=True,
                                help_text="User's preferred handle/display name",
                                max_length=150,
                                null=True,
                                unique=True,
                            ),
                        ),
                        (
                            "active_directory_username",
                            models.CharField(
                                blank=True,
                                help_text="Active Directory username for integration",
                                max_length=150,
                            ),
                        ),
                        (
                            "badge_number",
                            models.CharField(
                                blank=True,
                                help_text="Badge number for physical access control",
                                max_length=50,
                                null=True,
                                unique=True,
                            ),
                        ),
                        (
                            "discord_username",
                            models.CharField(
                                blank=True, help_text="Discord username", max_length=150
                            ),
                        ),
                        (
                            "discourse_username",
                            models.CharField(
                                blank=True,
                                help_text="Discourse username",
                                max_length=150,
                            ),
                        ),
                        (
                            "is_board_member",
                            models.BooleanField(
                                default=False,
                                help_text="Indicates if user is a board member",
                            ),
                        ),
                        (
                            "is_officer",
                            models.BooleanField(
                                default=False,
                                help_text="Indicates if user is an officer",
                            ),
                        ),
                        (
                            "is_director",
                            models.BooleanField(
                                default=False,
                                help_text="Indicates if user is a director",
                            ),
                        ),
                        (
                            "groups",
                            models.ManyToManyField(
                                blank=True,
                                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.group",
                                verbose_name="groups",
                            ),
                        ),
                        (
                            "user_permissions",
                            models.ManyToManyField(
                                blank=True,
                                help_text="Specific permissions for this user.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.permission",
                                verbose_name="user permissions",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "auth_user",
                    },
                    managers=[
                        ("objects", django.contrib.auth.models.UserManager()),
                    ],
                ),
            ],
            database_operations=[
                # For fresh test databases, create the table if it doesn't exist
                # Use a RunPython operation that detects the database type and creates appropriate SQL
                migrations.RunPython(
                    code=_create_user_table_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        # Create Membership model (table may or may not exist)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Membership",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "membership_type",
                            models.CharField(
                                choices=[
                                    ("monthly", "Monthly"),
                                    ("annual", "Annual"),
                                    ("complimentary", "Complimentary"),
                                    ("honorary", "Honorary"),
                                ],
                                default="monthly",
                                help_text="Type of membership",
                                max_length=20,
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("inactive", "Inactive"),
                                    ("active", "Active"),
                                    ("probative", "Probative"),
                                    ("restricted", "Restricted"),
                                    ("suspended", "Suspended"),
                                    ("terminated", "Terminated"),
                                ],
                                default="inactive",
                                help_text="Current status of the membership",
                                max_length=20,
                            ),
                        ),
                        (
                            "start_date",
                            models.DateField(
                                blank=True,
                                help_text="When the membership started",
                                null=True,
                            ),
                        ),
                        (
                            "end_date",
                            models.DateField(
                                blank=True,
                                help_text="When the membership ends (null for active memberships)",
                                null=True,
                            ),
                        ),
                        (
                            "notes",
                            models.TextField(
                                blank=True,
                                help_text="Additional notes about this membership",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "users",
                            models.ManyToManyField(
                                db_table="inventory_membership_users",
                                help_text="Users associated with this membership (for families/business accounts)",
                                related_name="memberships",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "inventory_membership",
                        "verbose_name_plural": "Memberships",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            database_operations=[
                # For fresh test databases, create the table if it doesn't exist
                migrations.RunPython(
                    code=_create_membership_table_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
    ]
