# Generated by Django 4.2.26 on 2025-11-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0004_create_auth_user_groups_table"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sigadmin",
            new_name="membership__user_id_adc1c7_idx",
            old_name="membership_sigadmin_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="sigadmin",
            new_name="membership__group_i_423cc9_idx",
            old_name="membership_sigadmin_group_active_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                help_text="PNG signature image for use on tax receipts",
                null=True,
                upload_to="signatures/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signature_uploaded_at",
            field=models.DateTimeField(
                blank=True, help_text="When the signature was uploaded", null=True
            ),
        ),
    ]
