# Generated by Django 5.1.14 on 2025-12-22 00:33

import logging

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger(__name__)


def _get_existing_columns(connection, vendor):
    """Get existing columns in auth_user table."""
    columns = set()
    with connection.cursor() as cursor:
        if vendor == "postgresql":
            cursor.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = 'auth_user'
                """
            )
            columns = {row[0] for row in cursor.fetchall()}
        elif vendor == "sqlite":
            cursor.execute("PRAGMA table_info('auth_user')")
            columns = {row[1] for row in cursor.fetchall()}
    return columns


def _ensure_signature_line_offset_column(apps, schema_editor):
    """Ensure signature_line_offset column exists and allows NULL."""
    connection = schema_editor.connection
    vendor = connection.vendor

    if vendor not in {"postgresql", "sqlite"}:
        logger.warning(
            "Skipping signature_line_offset column migration for unsupported vendor '%s'", vendor
        )
        return

    existing_columns = _get_existing_columns(connection, vendor)

    if "signature_line_offset" in existing_columns:
        # Column exists, alter it to allow NULL and set default
        if vendor == "postgresql":
            # First, set default for existing NULL values
            schema_editor.execute(
                "UPDATE auth_user SET signature_line_offset = 0 WHERE signature_line_offset IS NULL"
            )
            # Alter column to allow NULL and set default
            schema_editor.execute(
                "ALTER TABLE auth_user ALTER COLUMN signature_line_offset DROP NOT NULL"
            )
            schema_editor.execute(
                "ALTER TABLE auth_user ALTER COLUMN signature_line_offset SET DEFAULT 0"
            )
        elif vendor == "sqlite":
            # SQLite doesn't support ALTER COLUMN easily, but we can set defaults
            # For SQLite, we'll just ensure the constraint allows NULL
            logger.info("Column signature_line_offset already exists in SQLite")
    else:
        # Column doesn't exist, add it
        if vendor == "postgresql":
            schema_editor.execute(
                "ALTER TABLE auth_user ADD COLUMN signature_line_offset INTEGER DEFAULT 0"
            )
        elif vendor == "sqlite":
            schema_editor.execute(
                "ALTER TABLE auth_user ADD COLUMN signature_line_offset INTEGER DEFAULT 0"
            )


def _noop_reverse(apps, schema_editor):
    """Intentionally left empty; we do not remove columns on reverse migrations."""


class Migration(migrations.Migration):

    dependencies = [
        (
            "membership",
            "0005_rename_membership_sigadmin_user_active_idx_membership__user_id_adc1c7_idx_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_ensure_signature_line_offset_column, _noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="signature_line_offset",
                    field=models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Y-axis offset for signature line position in PDFs",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRegistrationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique token for registration",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been used"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When this token was used", null=True
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="When this token expires")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who created this token",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_registration_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account associated with this token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Registration Token",
                "verbose_name_plural": "User Registration Tokens",
                "db_table": "membership_user_registration_token",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token", "used"], name="membership__token_5591c2_idx"),
                    models.Index(
                        fields=["expires_at", "used"], name="membership__expires_bf6842_idx"
                    ),
                ],
            },
        ),
    ]
