# Generated by Django 5.1.15 on 2026-04-24 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("membership", "0006_add_signature_line_offset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIGProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Group-wide contact email for this SIG. When set, SIG notifications (e.g. new reorder requests) go here instead of fanning out to every SIG admin individually.",
                        max_length=254,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        help_text="SIG (Group) this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sig_profile",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "SIG Profile",
                "verbose_name_plural": "SIG Profiles",
            },
        ),
    ]
