# Generated by Django 4.2.26 on 2026-01-21 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("membership", "0006_add_signature_line_offset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the committee", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the committee's purpose and responsibilities",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this committee is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Committee",
                "verbose_name_plural": "Committees",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SIGCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "committee",
                    models.ForeignKey(
                        help_text="Committee this SIG belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sigs",
                        to="membership.committee",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        help_text="SIG (Group) that belongs to this committee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_membership",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "SIG Committee Membership",
                "verbose_name_plural": "SIG Committee Memberships",
            },
        ),
        migrations.CreateModel(
            name="CommitteeChair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this chair role active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "committee",
                    models.ForeignKey(
                        help_text="Committee this user chairs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chairs",
                        to="membership.committee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is a chair of this committee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_chair_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Chair",
                "verbose_name_plural": "Committee Chairs",
                "ordering": ["committee", "user"],
            },
        ),
        migrations.AddIndex(
            model_name="committee",
            index=models.Index(fields=["is_active", "name"], name="membership__is_acti_4dd1ed_idx"),
        ),
        migrations.AddIndex(
            model_name="sigcommittee",
            index=models.Index(
                fields=["committee", "group"], name="membership__committ_0422c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="committeechair",
            index=models.Index(fields=["user", "is_active"], name="membership__user_id_fd33ca_idx"),
        ),
        migrations.AddIndex(
            model_name="committeechair",
            index=models.Index(
                fields=["committee", "is_active"], name="membership__committ_29beb3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="committeechair",
            unique_together={("user", "committee")},
        ),
    ]
