# Generated by Django 5.1.15 on 2026-05-08 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("membership", "0007_sigprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable certification name (e.g. 'Laser cutter operator').",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used by code (e.g. devices referencing required certs).",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes — what the cert covers, prerequisites, etc.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive certifications stop gating access but stay on user records.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sig",
                    models.ForeignKey(
                        help_text="SIG (Group) that owns this certification. SIG admins of this group can grant + revoke per-user grants.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certifications",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["sig__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this grant was revoked. Null = currently active.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional grant/revoke context (training date, evaluator, etc.).",
                    ),
                ),
                (
                    "certification",
                    models.ForeignKey(
                        help_text="Which certification was granted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_grants",
                        to="membership.certification",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff or SIG admin who granted this certification.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff or SIG admin who revoked this certification.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who holds this certification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(fields=["sig", "is_active"], name="membership__sig_id_ec825e_idx"),
        ),
        migrations.AddIndex(
            model_name="usercertification",
            index=models.Index(
                fields=["user", "certification", "revoked_at"],
                name="membership__user_id_fef012_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usercertification",
            index=models.Index(
                fields=["certification", "revoked_at"], name="membership__certifi_2b773e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usercertification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("user", "certification"),
                name="unique_active_user_certification",
            ),
        ),
    ]
