# Generated by Django 5.1.15 on 2026-05-27 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("membership", "0008_certification_usercertification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Random, opaque, single-use token. Generated server-side.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "intended_label",
                    models.CharField(
                        help_text="Human label shown on the redemption page and in the staff list (e.g. 'Board Member — Q3 2026', 'Safety Committee'). Not load-bearing on permissions; the groups M2M is.",
                        max_length=120,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Staff-only notes about who this is for, why, when issued.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="UTC. Redemption fails after this instant."),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Manually revoked codes flip to False; redemption fails.",
                    ),
                ),
                (
                    "redeemed",
                    models.BooleanField(
                        default=False,
                        help_text="Flipped to True on successful redemption (single-use).",
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the redemption happened.", null=True
                    ),
                ),
                (
                    "redeemed_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Source IP captured at redemption time for audit.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who minted this code.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intended_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Django auth groups the new user is added to on redeem. Drives ForgeKey door access via the existing group-membership rule.",
                        related_name="invite_codes",
                        to="auth.group",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The User account created by redeeming this code.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code", "redeemed"], name="membership__code_112f61_idx"),
                    models.Index(
                        fields=["expires_at", "redeemed"], name="membership__expires_7f8c51_idx"
                    ),
                ],
            },
        ),
    ]
