# Generated by Django 6.0.6 on 2026-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0009_invitecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tokens_valid_after",
            field=models.DateTimeField(
                blank=True,
                help_text="JWT cutoff for the 'this wasn't me' revoke-all action (notifications FP3, oms-ltqs3). Any access or refresh token whose issued-at (iat) predates this moment is rejected during validation, forcing a full re-auth across the REST API, the DRF browsable API, and the admin. Null means no tokens have ever been revoked.",
                null=True,
            ),
        ),
    ]
