# Generated by Django 6.0.7 on 2026-07-17 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hordak', '0055_alter_leg_credit_alter_leg_currency_alter_leg_debit'),
        ('inventory', '0091_workorder_loto_completion_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='inventory.asset')),
                ('leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimension', to='hordak.leg')),
                ('sig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='auth.group')),
            ],
            options={
                'verbose_name': 'leg dimension',
            },
        ),
        migrations.CreateModel(
            name='EntryMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SIG_CHARGE', 'SIG charge'), ('PO_RECEIPT', 'PO receipt'), ('VENDOR_INVOICE', 'Vendor invoice'), ('DONATION', 'Donation'), ('ASSET_PURCHASE', 'Asset purchase'), ('COST_RECOVERY', 'Cost recovery'), ('SETTLEMENT', 'Settlement'), ('OPENING_BALANCE', 'Opening balance'), ('REVERSAL', 'Reversal'), ('MANUAL', 'Manual')], max_length=32)),
                ('source_ref', models.CharField(blank=True, default='', max_length=128)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='hordak.transaction')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='hordak.transaction')),
            ],
            options={
                'verbose_name': 'entry metadata',
                'verbose_name_plural': 'entry metadata',
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('source_type', 'source_ref'), name='uniq_entry_source')],
            },
        ),
    ]
