# Generated by Django 6.0.6 on 2026-07-02 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0071_inventoryitem_is_serialized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Operator-visible name for this interlock (e.g. 'Laser cutter').", max_length=120)),
                ('host', models.CharField(help_text='IP address or hostname on the shop LAN.', max_length=255)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('ssh_username', models.CharField(default='root', max_length=64)),
                ('encrypted_ssh_password', models.BinaryField(blank=True, default=b'')),
                ('auth_type', models.CharField(choices=[('password', 'SSH password'), ('key', 'SSH key (not implemented)')], default='password', max_length=16)),
                ('service_name', models.CharField(default='keymaster.service', help_text='systemd unit the on-device helper starts/stops.', max_length=128)),
                ('relay_pin', models.IntegerField(blank=True, help_text='Relay GPIO/output pin the helper forces off on disable.', null=True)),
                ('relay_interface', models.CharField(blank=True, choices=[('pigpio', 'pigpio'), ('piface', 'PiFace'), ('automationphat', 'Automation pHAT')], help_text='Which relay backend the on-device helper drives.', max_length=16, null=True)),
                ('desired_state', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', help_text='What the operator wants; enqueued commands drive the device to this.', max_length=16)),
                ('last_reported_state', models.CharField(blank=True, choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], help_text='State the Pi last reported for the device.', max_length=16, null=True)),
                ('in_use', models.BooleanField(blank=True, help_text='Whether the tool is drawing current (CurrentSense); null if unknown.', null=True)),
                ('online', models.BooleanField(default=False, help_text='Whether the Pi could reach the device on its last report.')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='The physical tool this interlock powers.', on_delete=django.db.models.deletion.CASCADE, related_name='interlocks', to='inventory.asset')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='InterlockCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable'), ('status', 'Status')], max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(blank=True, null=True)),
                ('interlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='interlocks.interlock')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interlock_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
