# Generated by Django 6.0.6 on 2026-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker_boxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerbox',
            name='conversion_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makerbox',
            name='identity_source',
            field=models.CharField(blank=True, choices=[('whmcs', 'WHMCS'), ('common_api', 'Common API (badge / AD)'), ('manual', 'Manual admin entry')], default='', help_text="Which backend confirmed this row's identity (whmcs / common_api / manual).", max_length=16),
        ),
        migrations.AlterField(
            model_name='makerbox',
            name='bin_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='makerbox',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('grace', 'Grace'), ('expired', 'Expired'), ('unassigned', 'Unassigned'), ('unknown', 'Unknown'), ('pre_conversion', 'Pre-conversion (queued for bin allocation)')], default='unassigned', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='makerbox',
            constraint=models.UniqueConstraint(condition=models.Q(('bin_id__isnull', False)), fields=('bin_id',), name='maker_box_bin_id_unique_when_set'),
        ),
    ]
