# Generated by Django 4.2.26 on 2025-11-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Makerspace Inventory",
                        help_text="The name of your makerspace or organization",
                        max_length=200,
                    ),
                ),
                (
                    "site_tagline",
                    models.CharField(
                        blank=True,
                        help_text="Optional tagline or subtitle for your site",
                        max_length=300,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload your organization's logo. Recommended size: 200x50px or similar aspect ratio",
                        null=True,
                        upload_to="customization/logos/",
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        blank=True,
                        default="Site Logo",
                        help_text="Alt text for the logo image (for accessibility)",
                        max_length=200,
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon for the site (should be square, e.g., 32x32px or 64x64px)",
                        null=True,
                        upload_to="customization/favicons/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007cba",
                        help_text="Primary brand color (hex code, e.g., #007cba)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#417690",
                        help_text="Secondary brand color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, help_text="Text to display in the footer (supports HTML)"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email address to display on the site",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, help_text="Contact phone number", max_length=20),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, help_text="Main website URL for your organization"),
                ),
                (
                    "dashboard_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title for the dashboard (overrides site name on dashboard)",
                        max_length=200,
                    ),
                ),
                (
                    "dashboard_subtitle",
                    models.CharField(
                        blank=True, help_text="Subtitle text for the dashboard", max_length=300
                    ),
                ),
                (
                    "show_logo_on_dashboard",
                    models.BooleanField(
                        default=True, help_text="Whether to display the logo on the dashboard"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "ordering": ["-updated_at"],
            },
        ),
    ]
