# Generated by Django 4.2.26 on 2025-11-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="authorized_signature_name",
            field=models.CharField(
                blank=True,
                help_text="Name of authorized signatory for tax receipts",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="authorized_signature_title",
            field=models.CharField(
                blank=True,
                help_text="Title of authorized signatory for tax receipts",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="organization_address",
            field=models.TextField(
                blank=True, help_text="Organization address for tax receipts"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="organization_ein",
            field=models.CharField(
                blank=True,
                help_text="Employer Identification Number (EIN) for tax receipts",
                max_length=20,
            ),
        ),
    ]
