# Generated by Django 4.2.26 on 2025-12-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0002_sitesettings_authorized_signature_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="custom_css",
            field=models.TextField(
                blank=True, help_text="Custom CSS to inject into the frontend. Use with caution."
            ),
        ),
    ]
