# Generated by Django 6.0.6 on 2026-06-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_sitesettingsauditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pm_auto_bundle_due_within_days',
            field=models.PositiveIntegerField(default=0, help_text='When creating a work order against a PM, also roll in every other active PM on the same asset that is due (or overdue) within this many days. 0 disables auto-bundling.'),
        ),
    ]
