# Generated by Django 6.0.6 on 2026-07-11 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("electrical_circuits", "0013_powerbreaker_critical_category_and_more"),
        ("inventory", "0082_inventoryitem_is_retired_inventoryitem_retired_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetSiteRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "needs_compressed_air",
                    models.BooleanField(
                        default=False, help_text="Device requires compressed air to operate."
                    ),
                ),
                (
                    "generates_heat_or_flame",
                    models.BooleanField(
                        default=False, help_text="Device has a flame or gives off a lot of heat."
                    ),
                ),
                (
                    "needs_ventilation",
                    models.BooleanField(
                        default=False, help_text="Device requires ventilation when running."
                    ),
                ),
                (
                    "needs_chilling",
                    models.BooleanField(
                        default=False, help_text="Device requires chilled water / active cooling."
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, help_text="Anything else the asset needs from the building."
                    ),
                ),
                (
                    "work_safety_notes",
                    models.TextField(
                        blank=True,
                        help_text="What the crew should know before working on the asset.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        help_text="Asset these site requirements belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_requirements",
                        to="inventory.asset",
                    ),
                ),
                (
                    "breaker",
                    models.ForeignKey(
                        blank=True,
                        help_text="Breaker that feeds this asset.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_requirements",
                        to="electrical_circuits.powerbreaker",
                    ),
                ),
                (
                    "disconnect",
                    models.ForeignKey(
                        blank=True,
                        help_text="Disconnect switch used to isolate this asset for lock-out / tag-out.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_requirements",
                        to="electrical_circuits.disconnect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset site requirements",
                "verbose_name_plural": "Asset site requirements",
            },
        ),
    ]
