# Generated by Django 5.1.15 on 2026-05-08 09:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("forgekey", "0011_alter_devicetype_code"),
        ("inventory", "0057_maintenanceauditevent"),
        ("membership", "0008_certification_usercertification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Locker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable locker name (e.g. 'Wood Shop locker 4').",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used in URLs and topics.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes — what this locker holds, special handling, etc.",
                    ),
                ),
                (
                    "power_source",
                    models.CharField(
                        choices=[
                            ("poe", "Power over Ethernet"),
                            ("usb", "USB-C / barrel jack"),
                            ("ac_outlet", "AC mains outlet"),
                            ("battery", "Battery only"),
                            ("unpowered", "Unpowered (mechanical only)"),
                        ],
                        default="poe",
                        help_text="How the locker is powered.",
                        max_length=20,
                    ),
                ),
                (
                    "is_high_trust",
                    models.BooleanField(
                        default=False,
                        help_text="If true, returns require a validated SIG admin to sign off before another user can take the asset. Surfaces a PendingHighTrustReturn row that blocks new OTPs (Phase 4).",
                    ),
                ),
                (
                    "led_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of WS2818 LEDs inside the locker for user-facing status cues (idle / unlocking / lockout). 0 = no LED strip wired.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive lockers reject new OTP requests but stay in audit history.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset currently stored in this locker. Null when the locker is empty or pending a high-trust return acceptance.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="storing_lockers",
                        to="inventory.asset",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Physical location housing this locker.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lockers",
                        to="inventory.location",
                    ),
                ),
                (
                    "owning_sig",
                    models.ForeignKey(
                        help_text="SIG (Group) that owns this locker. SIG admins can grant access, configure required certifications, and accept high-trust returns.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lockers",
                        to="auth.group",
                    ),
                ),
                (
                    "required_certifications",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Certifications a user must hold to receive an OTP for this locker (operator/SIG bypass still applies).",
                        related_name="lockers",
                        to="membership.certification",
                    ),
                ),
            ],
            options={
                "ordering": ["location__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="LockerDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("latch", "Latch controller"),
                            ("reed_switch", "Door reed switch"),
                            ("ir_break", "Inventory IR break sensor"),
                            ("keypad", "OTP keypad"),
                            ("led_strip", "WS2818 LED strip controller"),
                            ("mortise_key", "Mortise key (admin override) sensor"),
                        ],
                        help_text="What this device does for the locker.",
                        max_length=30,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary controller for this role on this locker. Exactly one primary per (locker, role) when present.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        help_text="The ESP32Device row.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locker_assignments",
                        to="forgekey.esp32device",
                    ),
                ),
                (
                    "locker",
                    models.ForeignKey(
                        help_text="Which locker this device serves.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_assignments",
                        to="lockers.locker",
                    ),
                ),
            ],
            options={
                "ordering": ["locker", "role"],
            },
        ),
        migrations.CreateModel(
            name="LockerOtp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-8 digit access code. Stored in cleartext because the row itself is the bearer credential and lives < 60 minutes; verifying against a hash would force the keypad to relay every guess back to Django.",
                        max_length=8,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this OTP stops being valid. Spec: T+60 minutes."
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the OTP was redeemed (single-use).", null=True
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the OTP was administratively revoked before use.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locker",
                    models.ForeignKey(
                        help_text="Locker this code unlocks.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to="lockers.locker",
                    ),
                ),
                (
                    "requesting_user",
                    models.ForeignKey(
                        help_text="User who requested the OTP — accountability anchor.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locker_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who revoked this OTP (if revoked_at is set).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locker_otps_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(
                fields=["location", "is_active"], name="lockers_loc_locatio_c254cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(
                fields=["owning_sig", "is_active"], name="lockers_loc_owning__3d879a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locker",
            index=models.Index(fields=["current_asset"], name="lockers_loc_current_e5842c_idx"),
        ),
        migrations.AddIndex(
            model_name="lockerdevice",
            index=models.Index(fields=["locker", "role"], name="lockers_loc_locker__a2952c_idx"),
        ),
        migrations.AddConstraint(
            model_name="lockerdevice",
            constraint=models.UniqueConstraint(
                fields=("locker", "device", "role"), name="unique_locker_device_role"
            ),
        ),
        migrations.AddIndex(
            model_name="lockerotp",
            index=models.Index(
                fields=["locker", "code", "expires_at"], name="lockers_loc_locker__928479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockerotp",
            index=models.Index(
                fields=["requesting_user", "created_at"], name="lockers_loc_request_3859c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lockerotp",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True), ("used_at__isnull", True)),
                fields=("locker", "code"),
                name="unique_active_locker_otp_code",
            ),
        ),
    ]
