# Generated by Django 6.0.5 on 2026-05-31 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0017_firmwarerollout_devicefirmwareupdate_rollout"),
        ("lockers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LockerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("secure", models.BooleanField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Firmware state: INITIALIZING / SECURE / UNLOCKED / ACCESSING / ALARM.",
                        max_length=20,
                    ),
                ),
                ("reed_closed", models.BooleanField(blank=True, null=True)),
                ("latch_locked", models.BooleanField(blank=True, null=True)),
                ("ir_broken", models.BooleanField(blank=True, null=True)),
                ("mortise_active", models.BooleanField(blank=True, null=True)),
                ("item_present", models.BooleanField(blank=True, null=True)),
                ("last_trigger", models.CharField(blank=True, max_length=40)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("last_status_at", models.DateTimeField(auto_now=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="The latch device that reported this status.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="forgekey.esp32device",
                    ),
                ),
                (
                    "locker",
                    models.OneToOneField(
                        help_text="The locker this status belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="lockers.locker",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Locker statuses",
            },
        ),
    ]
