# Generated by Django 5.1.15 on 2026-05-08 10:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0057_maintenanceauditevent"),
        ("lockers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LockerAccessEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("requested", "Access requested (OTP minted)"),
                            ("unlocked", "Latch released"),
                            ("open", "Door opened"),
                            ("secured", "Door closed + latch confirmed"),
                            ("incomplete", "Door left open past threshold"),
                            ("tamper", "Tamper / lockout entered"),
                            ("lockout_cleared", "Lockout cleared"),
                            ("item_removed", "Inventory IR break while door open"),
                            ("admin_physical_entry", "Mortise key (manual override)"),
                        ],
                        help_text="What happened.",
                        max_length=24,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific payload (raw EMQX forward, propped-door duration, lockout reason, etc.). Already passes through ``observability_redaction.redact`` before storage.",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the event occurred (broker-supplied if available).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User responsible (the OTP requester for unlocks; the admin for clear_lockout; null for firmware-originated rows where no user is associated, e.g. propped-door janitor).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locker_access_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset implicated by the event (the locker's current_asset snapshot at event time; null when the locker is empty).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locker_events",
                        to="inventory.asset",
                    ),
                ),
                (
                    "locker",
                    models.ForeignKey(
                        help_text="Locker this event is about.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_events",
                        to="lockers.locker",
                    ),
                ),
                (
                    "otp",
                    models.ForeignKey(
                        blank=True,
                        help_text="OTP that authorised this event. Null for direct staff unlocks, mortise-key entries, or tamper events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_events",
                        to="lockers.lockerotp",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="LockerHighTrustReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending acceptance"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="high_trust_returns",
                        to="inventory.asset",
                    ),
                ),
                (
                    "locker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="high_trust_returns",
                        to="lockers.locker",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="high_trust_returns_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "returning_user",
                    models.ForeignKey(
                        help_text="User who returned the asset.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="high_trust_returns_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggering_event",
                    models.ForeignKey(
                        help_text="The SECURED event that opened this return.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="high_trust_returns",
                        to="lockers.lockeraccessevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lockeraccessevent",
            index=models.Index(
                fields=["locker", "-occurred_at"], name="lockers_loc_locker__371cb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockeraccessevent",
            index=models.Index(fields=["kind", "-occurred_at"], name="lockers_loc_kind_9bd300_idx"),
        ),
        migrations.AddIndex(
            model_name="lockeraccessevent",
            index=models.Index(
                fields=["actor", "-occurred_at"], name="lockers_loc_actor_i_d3517a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lockerhightrustreturn",
            index=models.Index(fields=["locker", "status"], name="lockers_loc_locker__7c1a63_idx"),
        ),
        migrations.AddIndex(
            model_name="lockerhightrustreturn",
            index=models.Index(
                fields=["status", "-created_at"], name="lockers_loc_status_c5e8e5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lockerhightrustreturn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("locker",),
                name="unique_pending_high_trust_return_per_locker",
            ),
        ),
    ]
