# Generated by Django 4.2.25 on 2025-11-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rotation_interval_seconds",
                    models.PositiveIntegerField(
                        default=10, help_text="Seconds between message rotations"
                    ),
                ),
                (
                    "auto_refresh_seconds",
                    models.PositiveIntegerField(
                        default=30, help_text="Seconds between data refreshes"
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        help_text="Optional custom CSS for dashboard styling",
                    ),
                ),
                (
                    "is_maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Show maintenance message instead of normal dashboard",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        default="Dashboard temporarily unavailable for maintenance",
                        help_text="Message to show during maintenance mode",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Configuration",
                "verbose_name_plural": "Dashboard Configuration",
            },
        ),
        migrations.CreateModel(
            name="DashboardMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Message text to display in dashboard footer",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this message should be included in rotation",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower numbers shown first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Message",
                "verbose_name_plural": "Dashboard Messages",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
