# Generated by Django 4.2.27 on 2025-12-19 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("pending_reorders", "Pending Reorders"),
                            ("asset_problems", "Asset Problems"),
                            ("qr_scans", "QR Scans"),
                            ("deliveries", "Deliveries"),
                        ],
                        help_text="Type of widget",
                        max_length=50,
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(
                        default=0, help_text="X position in grid (0-based)"
                    ),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(
                        default=0, help_text="Y position in grid (0-based)"
                    ),
                ),
                ("width", models.PositiveIntegerField(default=2, help_text="Width in grid units")),
                (
                    "height",
                    models.PositiveIntegerField(default=2, help_text="Height in grid units"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, help_text="Whether this widget is visible"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower numbers shown first)"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Widget-specific settings (JSON)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this widget configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "ordering": ["user", "order", "position_y", "position_x"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_visible"], name="dashboard_d_user_id_f43b42_idx"
                    ),
                    models.Index(
                        fields=["user", "widget_type"], name="dashboard_d_user_id_51157a_idx"
                    ),
                ],
                "unique_together": {("user", "widget_type")},
            },
        ),
    ]
