# Generated by Django 4.2.26 on 2025-11-20 14:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0038_add_inventory_item_ownership"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "donation_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique donation reference number (auto-generated if not provided)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(
                        help_text="Name of the donor (individual or organization)",
                        max_length=200,
                    ),
                ),
                (
                    "donor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Donor email address (if available)",
                        max_length=254,
                    ),
                ),
                (
                    "donor_phone",
                    models.CharField(
                        blank=True,
                        help_text="Donor phone number (if available)",
                        max_length=50,
                    ),
                ),
                (
                    "donor_address",
                    models.TextField(
                        blank=True, help_text="Donor address (if available)"
                    ),
                ),
                (
                    "date_received",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the donation was received",
                    ),
                ),
                (
                    "received_notes",
                    models.TextField(
                        blank=True, help_text="Initial notes about the donation receipt"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the donation",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the donation was reviewed",
                        null=True,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the review process"
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated value of the donation (for record-keeping)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "associated_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Costs associated with this donation (e.g., transportation, handling)",
                        max_digits=10,
                    ),
                ),
                (
                    "cost_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about associated costs (what they were for)",
                    ),
                ),
                (
                    "tax_receipt_issued",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a tax receipt was issued to the donor",
                    ),
                ),
                (
                    "tax_receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Tax receipt number (if issued)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who received the donation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed the donation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_received", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or description of the item", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the item"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity of this item"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("unusable", "Unusable"),
                        ],
                        default="good",
                        help_text="Condition of the item when received",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("usable", "Usable"),
                            ("unusable", "Unusable"),
                            ("processing", "Processing"),
                            ("disposed", "Fully Disposed"),
                        ],
                        default="pending_review",
                        help_text="Current status of this item",
                        max_length=20,
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True,
                        help_text="6-character code for QR code scanning (auto-generated)",
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="QR code image for this donation item",
                        null=True,
                        upload_to="donations/qr_codes/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this specific item"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to Asset if this item became a tracked asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_items",
                        to="inventory.asset",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        help_text="The donation this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="donations.donation",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to InventoryItem if this item became inventory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_items",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["donation", "name"],
            },
        ),
        migrations.CreateModel(
            name="Disposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disposition_type",
                    models.CharField(
                        choices=[
                            ("kept", "Kept for Use"),
                            ("sold", "Sold Directly"),
                            ("auctioned", "Auctioned"),
                            ("donated_out", "Donated to Another Organization"),
                            ("recycled", "Recycled"),
                            ("disposed", "Disposed/Trashed"),
                            ("returned", "Returned to Donor"),
                            ("parted_out", "Parted Out for Components"),
                            ("other", "Other"),
                        ],
                        help_text="What happened to this item",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity disposed in this action"
                    ),
                ),
                (
                    "disposition_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the disposition occurred",
                    ),
                ),
                (
                    "sale_method",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct Sale"), ("auction", "Auction")],
                        help_text="Sale method (direct sale or auction) - required if sold/auctioned",
                        max_length=20,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sale price (if sold or auctioned)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "kept_destination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("makerspace", "Kept for Makerspace"),
                            ("sig", "Given to Committee/SIG"),
                        ],
                        help_text="Where kept item goes (makerspace or SIG) - required if kept",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this disposition"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient name (if donated out or sold)",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset created from this disposition (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disposition_origin",
                        to="inventory.asset",
                    ),
                ),
                (
                    "disposed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the disposition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispositions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation_item",
                    models.ForeignKey(
                        help_text="The donation item this disposition applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispositions",
                        to="donations.donationitem",
                    ),
                ),
                (
                    "kept_for_sig",
                    models.ForeignKey(
                        blank=True,
                        help_text="SIG/Committee receiving the item (if kept_for_sig)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_dispositions",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-disposition_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="donationitem",
            index=models.Index(
                fields=["donation", "status"], name="donations_d_donatio_e19298_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donationitem",
            index=models.Index(fields=["status"], name="donations_d_status_07fdc2_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["status", "-date_received"],
                name="donations_d_status_2a07ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["donor_name", "-date_received"],
                name="donations_d_donor_n_2b5e85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["donation_number"], name="donations_d_donatio_aaa256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disposition",
            index=models.Index(
                fields=["donation_item", "-disposition_date"],
                name="donations_d_donatio_a29f01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disposition",
            index=models.Index(
                fields=["disposition_type", "-disposition_date"],
                name="donations_d_disposi_9d48d4_idx",
            ),
        ),
    ]
