# Generated by Django 4.2.26 on 2025-11-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="estimated_number_of_items",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Estimated number of items in this donation (used to generate QR code labels)",
                null=True,
            ),
        ),
    ]
