# Generated by Django 4.2.26 on 2025-11-22 04:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donations", "0002_donation_estimated_number_of_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="tax_receipt_issued_at",
            field=models.DateTimeField(
                blank=True, help_text="When the tax receipt was issued", null=True
            ),
        ),
        migrations.CreateModel(
            name="TaxReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique serial number for this tax receipt",
                        unique=True,
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the receipt was issued",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF file for this receipt",
                        null=True,
                        upload_to="donations/tax_receipts/",
                    ),
                ),
                (
                    "is_copy",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a copy/reprint (watermarked)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donation",
                    models.ForeignKey(
                        help_text="The donation this receipt is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_receipts",
                        to="donations.donation",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who issued this receipt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_tax_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["serial_number"], name="donations_t_serial__96bad6_idx"
                    ),
                    models.Index(
                        fields=["donation", "-issued_date"],
                        name="donations_t_donatio_d22d62_idx",
                    ),
                ],
            },
        ),
    ]
