# Generated by Django 5.1.15 on 2026-05-03 01:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0055_alter_maintenancelog_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Interface name (e.g., 'wlan0', 'eth0', 'lan0').", max_length=50
                    ),
                ),
                (
                    "interface_type",
                    models.CharField(
                        choices=[
                            ("ethernet", "Ethernet"),
                            ("wifi", "Wi-Fi"),
                            ("usb-ethernet", "USB Ethernet"),
                            ("bluetooth", "Bluetooth"),
                            ("rs485", "RS-485"),
                            ("other", "Other"),
                        ],
                        default="ethernet",
                        max_length=20,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        help_text="MAC address. Accepted in any common form on input; normalized to lowercase no-separator on save (e.g., 'aabbccddeeff').",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="MAC address must be 12 hex digits, optionally separated by ':' or '-' (e.g., aabbccddeeff or aa:bb:cc:dd:ee:ff).",
                                regex="^[0-9A-Fa-f]{2}([:-]?[0-9A-Fa-f]{2}){5}$",
                            )
                        ],
                    ),
                ),
                (
                    "mtu",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum transmission unit, in bytes (optional).",
                        null=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this interface belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="inventory.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__name", "name"],
                "indexes": [
                    models.Index(fields=["mac_address"], name="devices_int_mac_add_c0744a_idx"),
                    models.Index(fields=["asset"], name="devices_int_asset_i_67faa2_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "mac_address"),
                        name="devices_interface_unique_mac_per_asset",
                    ),
                    models.UniqueConstraint(
                        fields=("asset", "name"), name="devices_interface_unique_name_per_asset"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NetworkDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "drop_label",
                    models.CharField(
                        help_text="Drop label (e.g., 'A12', 'Sewing-NW-1').", max_length=80
                    ),
                ),
                (
                    "wire_type",
                    models.CharField(
                        choices=[
                            ("cat5e", "Cat5e"),
                            ("cat6", "Cat6"),
                            ("cat6a", "Cat6a"),
                            ("fiber-mm", "Fiber, multi-mode"),
                            ("fiber-sm", "Fiber, single-mode"),
                        ],
                        default="cat6",
                        max_length=20,
                    ),
                ),
                (
                    "patch_panel_position",
                    models.CharField(
                        blank=True,
                        help_text="Free-text upstream patch panel + port (e.g., 'IDF-1 / 24'). Free-text since the user does not control the IT rack.",
                        max_length=120,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location of the drop.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_network_drops",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["location__name", "drop_label"],
                "indexes": [
                    models.Index(fields=["location"], name="devices_net_locatio_d5d0ff_idx"),
                    models.Index(fields=["wire_type"], name="devices_net_wire_ty_2df823_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "drop_label"), name="devices_networkdrop_unique_label"
                    )
                ],
            },
        ),
    ]
