# Generated by Django 4.2.7 on 2025-10-25 05:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplier_type', models.CharField(choices=[('hdsupply', 'HD Supply'), ('grainger', 'Grainger'), ('amazon', 'Amazon'), ('other', 'Other')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sku', models.CharField(blank=True, help_text='Internal SKU', max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='inventory/images/')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='inventory/thumbnails/')),
                ('location', models.CharField(help_text='Physical location in makerspace', max_length=200)),
                ('reorder_quantity', models.PositiveIntegerField(help_text='Quantity to reorder when stock is low', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current quantity in stock')),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text='Minimum quantity before reordering')),
                ('supplier_sku', models.CharField(blank=True, help_text="Supplier's product SKU/ID", max_length=100)),
                ('supplier_url', models.URLField(blank=True, help_text="Direct link to product on supplier's website")),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit', max_digits=10, null=True)),
                ('average_lead_time', models.PositiveIntegerField(default=7, help_text='Average lead time in days')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='inventory/qrcodes/')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-usage_date'],
                'indexes': [models.Index(fields=['item', '-usage_date'], name='inventory_u_item_id_c8169c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['name'], name='inventory_i_name_9b5824_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inventory_i_sku_e27286_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_b07c45_idx'),
        ),
    ]
