# Generated by Django 4.2.7 on 2025-10-25 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_add_default_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsupplier",
            name="quantity_per_package",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of individual units included in one package from this supplier",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="itemsupplier",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per individual unit from this supplier",
                max_digits=10,
                null=True,
            ),
        ),
    ]
