# Generated by Django 4.2.7 on 2025-10-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_itemsupplier_quantity_per_package_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsupplier",
            name="package_upc",
            field=models.CharField(
                blank=True,
                help_text="UPC/EAN printed on the packaged quantity received from this supplier",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="itemsupplier",
            name="unit_upc",
            field=models.CharField(
                blank=True,
                help_text="UPC/EAN for individual units when different from the package barcode",
                max_length=32,
            ),
        ),
    ]
