# Generated by Django 4.2.25 on 2025-10-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_add_package_cost_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hex color code for category (e.g., #FF5733) - used for index card styling",
                max_length=7,
            ),
        ),
    ]
