# Generated by Django 4.2.25 on 2025-10-28 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost at time of this record', max_digits=10, null=True)),
                ('package_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Package cost at time of this record', max_digits=10, null=True)),
                ('quantity_per_package', models.PositiveIntegerField(help_text='Quantity per package at time of this record', validators=[django.core.validators.MinValueValidator(1)])),
                ('change_type', models.CharField(choices=[('created', 'Initial Price'), ('updated', 'Price Update'), ('supplier_changed', 'Supplier Info Changed')], default='updated', help_text='Type of change that triggered this history record', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this price change')),
                ('item_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.itemsupplier')),
            ],
            options={
                'verbose_name_plural': 'Price histories',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['item_supplier', '-recorded_at'], name='inventory_p_item_su_59c2b5_idx'), models.Index(fields=['recorded_at'], name='inventory_p_recorde_dfcdee_idx')],
            },
        ),
    ]
