# Generated by Django 4.2.25 on 2025-10-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_pricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsupplier",
            name="package_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package height in centimeters",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemsupplier",
            name="package_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package length in centimeters",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemsupplier",
            name="package_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package weight in grams",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemsupplier",
            name="package_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package width in centimeters",
                max_digits=8,
                null=True,
            ),
        ),
    ]
