# Generated by Django 4.2.25 on 2025-10-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_add_item_supplier_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsupplier",
            name="package_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package height in inches",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemsupplier",
            name="package_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package length in inches",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemsupplier",
            name="package_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Package weight in pounds",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemsupplier",
            name="package_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Package width in inches",
                max_digits=8,
                null=True,
            ),
        ),
    ]
