# Generated by Django 4.2.25 on 2025-10-29 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_convert_dimensions_to_us_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="is_hazardous",
            field=models.BooleanField(
                default=False, help_text="Check if this item is classified as a hazardous material"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="msds_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the Material Safety Data Sheet (MSDS) or Safety Data Sheet (SDS)",
                verbose_name="Material Safety Data Sheet URL",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="nfpa_fire_hazard",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Fire hazard rating (0-4): 0=Minimal, 1=Slight, 2=Moderate, 3=High, 4=Extreme",
                null=True,
                validators=[django.core.validators.MaxValueValidator(4)],
                verbose_name="NFPA Fire Hazard",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="nfpa_health_hazard",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Health hazard rating (0-4): 0=Minimal, 1=Slight, 2=Moderate, 3=High, 4=Extreme",
                null=True,
                validators=[django.core.validators.MaxValueValidator(4)],
                verbose_name="NFPA Health Hazard",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="nfpa_instability_hazard",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Instability/Reactivity hazard rating (0-4): 0=Minimal, 1=Slight, 2=Moderate, 3=High, 4=Extreme",
                null=True,
                validators=[django.core.validators.MaxValueValidator(4)],
                verbose_name="NFPA Instability Hazard",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="nfpa_special_hazards",
            field=models.CharField(
                blank=True,
                help_text="Special hazard symbols (e.g., W=Water Reactive, OX=Oxidizer, COR=Corrosive, ALK=Alkali, ACID=Acid, BIO=Biohazard, POI=Poison, RAD=Radioactive)",
                max_length=20,
                verbose_name="NFPA Special Hazards",
            ),
        ),
    ]
