# Generated by Django 4.2.25 on 2025-11-03 03:48

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0012_inventoryitem_is_hazardous_inventoryitem_msds_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Asset name or model", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the asset"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Serial number or unique identifier (if available)",
                        max_length=100,
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        blank=True,
                        help_text="Internal asset tag number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "manufacturer_name",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer name (use if not in supplier list)",
                        max_length=200,
                    ),
                ),
                (
                    "date_received",
                    models.DateField(
                        blank=True,
                        help_text="Date the asset was received or acquired",
                        null=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount paid for the asset (0.00 for donations)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_donation",
                    models.BooleanField(
                        default=False, help_text="Check if this asset was donated"
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of donor (if applicable)",
                        max_length=200,
                    ),
                ),
                (
                    "product_url",
                    models.URLField(
                        blank=True, help_text="Link to product page or documentation"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of the asset",
                        null=True,
                        upload_to="assets/images/",
                    ),
                ),
                (
                    "manual_pdf",
                    models.FileField(
                        blank=True,
                        help_text="User manual or documentation PDF",
                        null=True,
                        upload_to="assets/manuals/",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="QR code for quick asset identification",
                        null=True,
                        upload_to="assets/qrcodes/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                            ("lost", "Lost"),
                            ("donated_out", "Donated Out"),
                        ],
                        default="active",
                        help_text="Current status of the asset",
                        max_length=20,
                    ),
                ),
                (
                    "condition_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about the asset's condition, maintenance history, etc.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive assets are hidden from most views",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about the asset"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for organizing assets",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="inventory.category",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to inventory item type (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current physical location of the asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="inventory.location",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manufacturer or supplier of the asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufactured_assets",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="inventory_a_name_bfaf8b_idx"),
                    models.Index(
                        fields=["serial_number"], name="inventory_a_serial__4865f1_idx"
                    ),
                    models.Index(
                        fields=["asset_tag"], name="inventory_a_asset_t_f5ad3d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="inventory_a_status_69dd7e_idx"
                    ),
                    models.Index(
                        fields=["manufacturer"], name="inventory_a_manufac_4dfc0e_idx"
                    ),
                ],
            },
        ),
    ]
