# Generated by Django 4.2.25 on 2025-11-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="maintenance_plan",
            field=models.TextField(
                blank=True,
                help_text="Maintenance schedule and procedures (visible to authenticated users only)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="wiki_page_url",
            field=models.URLField(
                blank=True,
                help_text="Link to wiki page for this asset (shown to all users when scanning QR code)",
            ),
        ),
    ]
