# Generated by Django 4.2.25 on 2025-11-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_asset_maintenance_plan_asset_wiki_page_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="is_requestable",
            field=models.BooleanField(
                default=True,
                help_text="Allow general users to request reorders for this item. Uncheck to restrict reorder requests to admins only.",
            ),
        ),
    ]
