# Generated by Django 4.2.25 on 2025-11-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_inventoryitem_is_requestable"),
    ]

    operations = []
