# Generated by Django 4.2.25 on 2025-11-04 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_add_is_requestable_to_inventory_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="minimum_cases",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimum number of cases/packages before reordering (only used if case-based reordering is enabled)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="reorder_cases",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of cases/packages to reorder when stock is low (only used if case-based reordering is enabled)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="use_case_based_reorder",
            field=models.BooleanField(
                default=False,
                help_text="Enable case/package-based reordering instead of individual unit reordering",
            ),
        ),
    ]
