# Generated by Django 4.2.25 on 2025-11-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_add_case_based_reorder_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="reorder_instruction",
            field=models.TextField(
                blank=True,
                help_text="Custom reorder instruction text for index cards (e.g., 'Reorder when last case is opened'). If empty, will show default text based on stock levels.",
            ),
        ),
    ]
