# Generated by Django 4.2.25 on 2025-11-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_add_case_based_reorder_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="shelf_position",
            field=models.CharField(
                blank=True,
                choices=[("top", "Top Shelf"), ("bottom", "Bottom Shelf")],
                help_text="Shelf position for index card reference",
                max_length=20,
            ),
        ),
    ]
