# Generated by Django 4.2.25 on 2025-11-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_add_reorder_instruction"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="account_number",
            field=models.CharField(
                blank=True,
                help_text="Account number with this supplier (if applicable)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="tax_free_paperwork_filed",
            field=models.BooleanField(
                default=False,
                help_text="Check if tax-free paperwork has been filed with this supplier",
            ),
        ),
    ]
