# Generated by Django 4.2.25 on 2025-11-06 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_add_supplier_account_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this fixture (e.g., 'Bathroom 1 Soap Dispenser')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Additional details about this fixture"),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        blank=True,
                        help_text="Unique asset tag or identifier",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive fixtures are hidden from scanning"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Where this fixture is installed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixtures",
                        to="inventory.location",
                    ),
                ),
                (
                    "refill_item",
                    models.ForeignKey(
                        help_text="The inventory item used to refill this fixture",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_fixtures",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["location__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="FixtureRefillRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of this refill request",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.CharField(
                        blank=True,
                        help_text="Username or identifier of person who reported this (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When this request was resolved", null=True
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(
                        blank=True,
                        help_text="Username of person who resolved this request",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes about this request"),
                ),
                (
                    "fixture",
                    models.ForeignKey(
                        help_text="The fixture that needs refilling",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_requests",
                        to="inventory.fixture",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["fixture", "status"], name="inventory_f_fixture_15ad6a_idx"
                    ),
                    models.Index(
                        fields=["status", "-requested_at"], name="inventory_f_status_ae296c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="fixture",
            index=models.Index(
                fields=["location", "is_active"], name="inventory_f_locatio_8586dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixture",
            index=models.Index(fields=["refill_item"], name="inventory_f_refill__228979_idx"),
        ),
        migrations.AddIndex(
            model_name="fixture",
            index=models.Index(fields=["asset_tag"], name="inventory_f_asset_t_5bf411_idx"),
        ),
    ]
