# Generated by Django 4.2.25 on 2025-11-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_fixture_fixturerefillrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="msds_file",
            field=models.FileField(
                blank=True,
                help_text="Upload the Material Safety Data Sheet (MSDS/SDS) PDF or document file",
                null=True,
                upload_to="inventory/msds/",
                verbose_name="MSDS/SDS File Upload",
            ),
        ),
    ]
