# Generated by Django 4.2.25 on 2025-11-07 05:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_add_shelf_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="circuit",
            field=models.CharField(
                blank=True,
                help_text="Circuit identification where this device is plugged in",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_chargeable",
            field=models.BooleanField(
                default=False,
                help_text="Device is chargeable to members (for billing purposes)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="last_scanned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when this asset was last scanned via QR code",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="needs_compressed_air",
            field=models.BooleanField(
                default=False, help_text="Device requires compressed air to operate"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="needs_ventilation",
            field=models.BooleanField(
                default=False, help_text="Device requires ventilation when running"
            ),
        ),
        migrations.CreateModel(
            name="AssetProblem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_by",
                    models.CharField(
                        blank=True,
                        help_text="Username or identifier of person reporting the problem",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the problem or issue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        help_text="Current status of the problem report",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes about how the problem was resolved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the problem was resolved", null=True
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="The asset with the problem",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="inventory.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "status"],
                        name="inventory_a_asset_i_914b0d_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="inventory_a_status_9762a1_idx",
                    ),
                ],
            },
        ),
    ]
