# Generated by Django 4.2.25 on 2025-11-07 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0023_add_asset_fields_and_problem_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_locked",
            field=models.BooleanField(
                default=False, help_text="If True, non-admins cannot use this asset"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="lock_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("group_admin", "Group Admin"),
                    ("group_member", "Group Member"),
                    ("logistics", "Logistics"),
                ],
                help_text="Type of user who locked this asset",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="locked_at",
            field=models.DateTimeField(
                blank=True, help_text="When this asset was locked", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who locked this asset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="owning_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group that owns this asset (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_assets",
                to="auth.group",
            ),
        ),
    ]
