# Generated by Django 4.2.25 on 2025-11-07 06:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_create_custom_user_model"),  # User model must exist first
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="groups_can_enable",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups that are allowed to enable this asset",
                related_name="assets_can_enable",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("needs_maintenance", "Needs Maintenance"),
                    ("disabled", "Disabled"),
                ],
                default="available",
                help_text="Current operational status of the asset",
                max_length=20,
            ),
        ),
    ]
