# Generated by Django 4.2.25 on 2025-11-07 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_add_user_fields_and_asset_operational_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="ownership_type",
            field=models.CharField(
                choices=[("user", "User"), ("group", "Group"), ("space", "Space")],
                default="space",
                help_text="Type of ownership for this asset",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="owning_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this asset (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_username",
            field=models.CharField(blank=True, help_text="Discord username", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="discourse_username",
            field=models.CharField(blank=True, help_text="Discourse username", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="handle",
            field=models.CharField(
                blank=True,
                help_text="User's preferred handle/display name",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_director",
            field=models.BooleanField(default=False, help_text="Indicates if user is a director"),
        ),
    ]
