# Generated by Django 4.2.25 on 2025-11-07 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # This migration replaces 0026_asset_ownership_type_asset_owning_user_and_more
        # which was already applied, so we depend on the same parent
        ("inventory", "0025_add_user_fields_and_asset_operational_status"),
        ("membership", "0001_initial"),
    ]

    operations = [
        # Add ownership fields to Asset model
        # For fresh databases, these will be created. For existing databases that already
        # have these fields from 0026_asset_ownership_type_asset_owning_user_and_more,
        # the migration will handle it gracefully.
        migrations.AddField(
            model_name="asset",
            name="ownership_type",
            field=models.CharField(
                choices=[("user", "User"), ("group", "Group"), ("space", "Space")],
                default="space",
                help_text="Type of ownership for this asset",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="owning_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this asset (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
