# Generated by Django 4.2.25 on 2025-11-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_asset_ownership_type_asset_owning_user"),
        ("membership", "0001_initial"),
    ]

    operations = [
        # Remove User model from inventory app's state (table is now managed by membership app)
        # Use SeparateDatabaseAndState to only update state, not database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="User",
                ),
            ],
            database_operations=[],  # Don't delete the table - it's managed by membership app
        ),
    ]
