# Generated by Django 4.2.26 on 2025-11-08 07:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity_needed",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many of this part are needed for the asset (e.g., 2 saw blades)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this part is required for the asset to function",
                    ),
                ),
                (
                    "maintenance_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recommended days between replacements (e.g., 90 for filters)",
                        null=True,
                    ),
                ),
                (
                    "last_replaced_at",
                    models.DateTimeField(
                        blank=True, help_text="When this part was last replaced", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this part (installation instructions, compatibility, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="The asset that uses this part",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_parts",
                        to="inventory.asset",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        help_text="The inventory item (part/consumable) used by this asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_by_assets",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Part",
                "verbose_name_plural": "Asset Parts",
                "ordering": ["asset", "part__name"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="parts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consumable parts and supplies used by this asset (e.g., saw blades, nozzles, filters)",
                related_name="assets_using_part",
                through="inventory.AssetPart",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddIndex(
            model_name="assetpart",
            index=models.Index(fields=["asset", "part"], name="inventory_a_asset_i_4b008a_idx"),
        ),
        migrations.AddIndex(
            model_name="assetpart",
            index=models.Index(fields=["part", "asset"], name="inventory_a_part_id_5ebc1e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assetpart",
            unique_together={("asset", "part")},
        ),
    ]
