# Generated by Django 4.2.26 on 2025-11-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_remove_forgekey_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="report_only",
            field=models.BooleanField(
                default=False,
                help_text="If True, this asset only supports problem reporting (no enable/disable functionality). Examples: soap dispensers, fixtures.",
            ),
        ),
    ]
