# Generated by Django 4.2.26 on 2025-11-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_add_report_only_to_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code for location check-ins and feedback",
                null=True,
                upload_to="inventory/location_qrcodes/",
            ),
        ),
    ]
