# Generated by Django 4.2.26 on 2025-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_add_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="access_code",
            field=models.CharField(
                blank=True,
                help_text="Unique 6-character code for manual entry (excludes I, 0, O, 1, L)",
                max_length=6,
                null=True,
                unique=True,
            ),
        ),
    ]
