# Generated by Django 4.2.26 on 2025-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_add_access_code_to_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("implementing", "Implementing"),
                    ("testing", "Testing"),
                    ("active", "Active"),
                    ("maintenance", "Under Maintenance"),
                    ("retired", "Retired"),
                    ("lost", "Lost"),
                    ("donated_out", "Donated Out"),
                ],
                default="active",
                help_text="Current status of the asset",
                max_length=20,
            ),
        ),
    ]
