# Generated by Django 4.2.26 on 2025-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_add_implementing_testing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsupplier",
            name="is_discontinued",
            field=models.BooleanField(
                default=False,
                help_text="Whether this item has been discontinued by this supplier (no longer available for purchase)",
            ),
        ),
    ]
