# Generated by Django 4.2.26 on 2025-11-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0038_add_inventory_item_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="last_scanned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when this inventory item was last scanned via QR code",
                null=True,
            ),
        ),
    ]
