# Generated by Django 4.2.26 on 2025-12-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0039_add_last_scanned_at_to_inventory_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="inventory.location",
            ),
        ),
    ]
