# Generated by Django 4.2.27 on 2025-12-18 18:31

from django.db import migrations, models
import django.db.models.deletion


def update_part_field_constraint(apps, schema_editor):
    """
    Update the part field constraint to SET_NULL if it exists, or add the field if it doesn't.
    This handles both cases:
    1. Field exists with wrong constraint - update it
    2. Field doesn't exist - add it with correct constraint
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if the part_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='inventory_assetproblem' 
            AND column_name='part_id'
        """)
        field_exists = cursor.fetchone() is not None
        
        if field_exists:
            # Field exists, need to drop old constraint and recreate with SET_NULL
            # First, find and drop the old foreign key constraint
            cursor.execute("""
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                WHERE tc.table_name = 'inventory_assetproblem'
                    AND tc.constraint_type = 'FOREIGN KEY'
                    AND kcu.column_name = 'part_id'
            """)
            constraint_result = cursor.fetchone()
            if constraint_result:
                constraint_name = constraint_result[0]
                # Drop the old constraint
                cursor.execute(
                    f'ALTER TABLE inventory_assetproblem DROP CONSTRAINT IF EXISTS "{constraint_name}"'
                )
            
            # Ensure the column is nullable
            cursor.execute(
                "ALTER TABLE inventory_assetproblem ALTER COLUMN part_id DROP NOT NULL"
            )
            
            # Recreate the foreign key with SET_NULL behavior
            cursor.execute("""
                ALTER TABLE inventory_assetproblem 
                ADD CONSTRAINT inventory_assetproblem_part_id_fk 
                FOREIGN KEY (part_id) 
                REFERENCES inventory_assetpart(id) 
                ON DELETE SET NULL
            """)
        else:
            # Field doesn't exist, add it
            cursor.execute("""
                ALTER TABLE inventory_assetproblem 
                ADD COLUMN part_id BIGINT NULL
            """)
            
            # Add the foreign key constraint with SET_NULL
            cursor.execute("""
                ALTER TABLE inventory_assetproblem 
                ADD CONSTRAINT inventory_assetproblem_part_id_fk 
                FOREIGN KEY (part_id) 
                REFERENCES inventory_assetpart(id) 
                ON DELETE SET NULL
            """)


def reverse_update_part_field_constraint(apps, schema_editor):
    """
    Reverse migration: drop the field if it was added by this migration.
    Note: We can't easily restore the old constraint, so we'll just drop the field.
    """
    with schema_editor.connection.cursor() as cursor:
        # Drop the constraint first
        cursor.execute("""
            ALTER TABLE inventory_assetproblem 
            DROP CONSTRAINT IF EXISTS inventory_assetproblem_part_id_fk
        """)
        # Note: We don't drop the column in reverse to avoid data loss
        # The field will remain but without the constraint


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0040_location_parent"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    update_part_field_constraint,
                    reverse_update_part_field_constraint,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="assetproblem",
                    name="part",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Optional: The specific part associated with this problem (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="part_problems",
                        to="inventory.assetpart",
                    ),
                ),
            ],
        ),
    ]
