# Generated by Django 5.1.14 on 2025-12-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0041_add_part_to_assetproblem"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetproblem",
            name="resolved_by",
            field=models.CharField(
                blank=True,
                help_text="Username or identifier of person who resolved the problem",
                max_length=200,
            ),
        ),
    ]
