# Generated by Django 5.1.15 on 2026-04-22 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0045_add_work_order_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancematerial",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to an inventory item for stock checking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_materials",
                to="inventory.inventoryitem",
            ),
        ),
    ]
