# Generated by Django 5.1.15 on 2026-04-24 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0046_maintenancematerial_inventory_item"),
        ("reorder_queue", "0016_fix_order_in_packages_column_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "projected_count",
                    models.IntegerField(help_text="current_stock at the time of reconciliation"),
                ),
                ("actual_count", models.IntegerField(help_text="Physically counted quantity")),
                ("delta", models.IntegerField(help_text="actual_count - projected_count (signed)")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                            ("miscounted", "Miscounted"),
                            ("used_without_scan", "Used without scanning"),
                            ("found", "Found (positive delta)"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reconciled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_reorder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-created reorder when actual_count <= minimum_stock",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reorder_queue.reorderrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-reconciled_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "-reconciled_at"], name="inventory_s_item_id_0faf84_idx"
                    ),
                    models.Index(fields=["-reconciled_at"], name="inventory_s_reconci_81f352_idx"),
                    models.Index(fields=["reason"], name="inventory_s_reason_161d7a_idx"),
                ],
            },
        ),
    ]
