# Generated by Django 5.1.15 on 2026-04-25 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0047_stockreconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="mac_address",
            field=models.CharField(
                blank=True,
                help_text="MAC address for electronic/networked assets (e.g., AA:BB:CC:11:22:33).",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid MAC address (e.g., AA:BB:CC:11:22:33).",
                        regex="^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$",
                    )
                ],
            ),
        ),
    ]
