# Generated by Django 5.1.15 on 2026-04-26 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0048_add_asset_mac_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workordersubmission",
            name="source",
            field=models.CharField(
                choices=[("email", "Email"), ("manual", "Manual")],
                default="email",
                help_text="How this submission entered the system (email webhook vs manual upload)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workordersubmission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who manually uploaded the PDF (null for email-source submissions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_order_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
