# Generated by Django 5.1.15 on 2026-04-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0050_add_asset_problem_photo"),
        ("maintenance_orders", "0003_thirdpartyworkorder_emergency_authorized_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workordersubmission",
            name="kind",
            field=models.CharField(
                choices=[("pm_completion", "PM completion"), ("third_party_wo", "Third-party WO")],
                default="pm_completion",
                help_text="Discriminates which ingest pipeline to run: pm_completion routes to WorkOrder updates; third_party_wo routes to ThirdPartyWorkOrder.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workordersubmission",
            name="third_party_work_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolved third-party work order (null for pm_completion or until parsed)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="maintenance_orders.thirdpartyworkorder",
            ),
        ),
        migrations.AlterField(
            model_name="workordersubmission",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolved PM work order (null for third_party_wo or until parsed)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="inventory.workorder",
            ),
        ),
    ]
