# Generated by Django 5.1.15 on 2026-04-29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0051_add_workordersubmission_kind_and_tpwo"),
        ("maintenance_orders", "0005_thirdpartyworkorder_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workordersubmission",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pm_completion", "PM completion"),
                    ("third_party_wo", "Third-party WO"),
                    ("location_problem", "Location Problem Report"),
                ],
                default="pm_completion",
                help_text="Discriminates which ingest pipeline to run: pm_completion routes to WorkOrder updates; third_party_wo routes to ThirdPartyWorkOrder.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LocationProblem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_by",
                    models.CharField(
                        blank=True,
                        help_text="Username or identifier of person reporting the problem",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the problem or issue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional reporter photo of the problem",
                        null=True,
                        upload_to="location_problems/%Y/%m/",
                    ),
                ),
                (
                    "paper_form_attachment",
                    models.FileField(
                        blank=True,
                        help_text="Scanned paper-form PDF if reported via paper",
                        null=True,
                        upload_to="location_problems/paper/%Y/%m/",
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="The location with the problem",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="inventory.location",
                    ),
                ),
                (
                    "third_party_work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Third-party work order this problem was promoted to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_problems",
                        to="maintenance_orders.thirdpartyworkorder",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standard PM work order this problem was promoted to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_problems",
                        to="inventory.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.AddField(
            model_name="workordersubmission",
            name="location_problem",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolved location problem (set for location_problem ingestions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="inventory.locationproblem",
            ),
        ),
        migrations.AddIndex(
            model_name="locationproblem",
            index=models.Index(
                fields=["location", "status"], name="inventory_l_locatio_ecc1d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationproblem",
            index=models.Index(
                fields=["status", "reported_at"], name="inventory_l_status_8f79f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationproblem",
            index=models.Index(
                fields=["severity", "status"], name="inventory_l_severit_50fa6b_idx"
            ),
        ),
    ]
