# Generated by Django 5.1.15 on 2026-04-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0052_add_location_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="breaker_location",
            field=models.CharField(
                blank=True,
                help_text="Specific breaker label / number serving this asset (e.g., 'Panel A, Breaker 12').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="electrical_box",
            field=models.CharField(
                blank=True,
                help_text="Electrical box / panel enclosure that supplies this asset.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="has_interlock",
            field=models.BooleanField(
                default=False,
                help_text="Whether this asset has a hardware interlock that prevents operation.",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="has_network_drop",
            field=models.BooleanField(
                default=False, help_text="Whether this asset has a wired network drop nearby."
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="interlock_responsible",
            field=models.CharField(
                blank=True,
                help_text="Person or group responsible for the interlock (when not managed by ForgeKey).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="interlock_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("forgekey", "ForgeKey-controlled"),
                    ("key_switch", "Key switch"),
                    ("e_stop", "E-Stop"),
                    ("contactor", "Contactor / relay"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="How the interlock is implemented.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="lockout_instructions",
            field=models.TextField(
                blank=True,
                help_text="Step-by-step instructions for safely locking out this asset before service.",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="lockout_responsible",
            field=models.CharField(
                blank=True,
                help_text="Person or group responsible for performing/verifying lockout.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="lockout_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("loto", "LOTO (Lockout / Tagout)"),
                    ("plug_lockout", "Plug lockout"),
                    ("breaker_lockout", "Breaker lockout"),
                    ("key_lockout", "Key lockout"),
                    ("valve_lockout", "Valve lockout"),
                    ("forgekey", "ForgeKey-managed"),
                    ("none", "None"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="How the asset is locked out for service.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="network_drop_location",
            field=models.CharField(
                blank=True,
                help_text="Where the network drop is located (jack label, switch port, etc.).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="power_draw_watts",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rated power draw in watts (nameplate rating, when known).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="suite",
            field=models.CharField(
                blank=True,
                help_text="Suite or area of the building where this asset's power drop originates.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="wiring_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("120v_plug", "120V Plug"),
                    ("240v_plug", "240V Plug"),
                    ("hardwired", "Hardwired"),
                    ("battery", "Battery"),
                    ("pneumatic", "Pneumatic / non-electric"),
                    ("none", "No power required"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="How this asset is wired or supplied with power.",
                max_length=20,
            ),
        ),
    ]
