# Generated by Django 5.1.15 on 2026-04-30 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0053_add_asset_power_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workordersubmission",
            name="pending_changes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AC-4 (oms-2da): list of CV detections whose confidence is below the auto-apply threshold. Each entry: {kind, target_id, value, confidence, label}. Reviewer accepts or rejects via the work-order-submissions endpoints.",
            ),
        ),
        migrations.AlterField(
            model_name="workordersubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("applied", "Applied"),
                    ("failed", "Failed"),
                    ("pending_review", "Pending review"),
                ],
                default="received",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                ("electrical_acknowledged", models.BooleanField(default=False)),
                ("loto_acknowledged", models.BooleanField(default=False)),
                ("required_fields_acknowledged", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="inventory.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-validated_at"],
                "indexes": [
                    models.Index(
                        fields=["work_order", "-validated_at"], name="wov_wo_validated_idx"
                    )
                ],
            },
        ),
    ]
