# Generated by Django 5.1.15 on 2026-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0054_add_workorder_validation_and_review_queue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancelog",
            name="completed_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When the task was completed"),
        ),
    ]
