# Generated by Django 5.1.15 on 2026-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0055_alter_maintenancelog_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_critical",
            field=models.BooleanField(
                default=False,
                help_text="Marks the asset as a critical load. Critical loads are surfaced separately in trip-impact reports so operators can plan around outages of fire alarms, network APs, freezers, etc.",
            ),
        ),
    ]
