# Generated by Django 5.1.15 on 2026-05-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0057_maintenanceauditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="hours_used",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cumulative operating hours. Updated manually via the asset hours endpoint; feeds utilization metrics and the hours-based maintenance forecast.",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="maintenance_interval_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Service every N calendar days. The forecast flags the asset when (days since last completed work order) crosses this value. Combined with maintenance_interval_hours: whichever fires first.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="maintenance_interval_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Service every N operating hours. The forecast flags the asset when (hours_used since last completed work order) crosses this value.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="estimated_external_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Counterfactual cost of having this work performed by an outside vendor. Used for ROI reporting (value generated by completing in-house). Leave blank for routine work where the estimate isn't meaningful.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
