# Generated by Django 5.1.15 on 2026-05-13 07:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0058_add_analytics_fields"),
        ("vendors", "0002_vendorauditevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short label, e.g. 'Annual HVAC service'", max_length=200
                    ),
                ),
                ("description", models.TextField(help_text="Description of the work performed")),
                (
                    "completed_on",
                    models.DateField(
                        db_index=True, help_text="Calendar date the work was completed"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost of the work; null when unknown or N/A",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=64)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Invoice PDF, receipt photo, etc.",
                        null=True,
                        upload_to="inventory/maintenance_records/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset the maintenance was performed on",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="inventory.asset",
                    ),
                ),
                (
                    "performed_by_internal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal staff member who performed the work",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internal_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who entered this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vendor that performed the work (outsourced)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_on", "-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "-completed_on"], name="maint_rec_asset_done_idx"
                    ),
                    models.Index(
                        fields=["vendor", "-completed_on"], name="maint_rec_vendor_done_idx"
                    ),
                ],
            },
        ),
    ]
