# Generated by Django 6.0.5 on 2026-05-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0060_asset_breaker_disconnect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="access_code",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="access_code",
        ),
    ]
