# Generated by Django 6.0.5 on 2026-05-31 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_backfill_workorder_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancematerial',
            name='location_hint',
            field=models.CharField(blank=True, help_text="Where to find this consumable when it isn't a tracked inventory item (e.g., 'Shop supply cabinet, bin 4').", max_length=200),
        ),
        migrations.CreateModel(
            name='MaintenanceTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the tool', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many are needed')),
                ('location_hint', models.CharField(blank=True, help_text="Where to find this tool when it isn't a tracked inventory item (e.g., 'Tool crib, drawer 3').", max_length=200)),
                ('is_required', models.BooleanField(default=True, help_text='Required tools are highlighted on the work order')),
                ('notes', models.TextField(blank=True, help_text='Notes about the tool or its use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(blank=True, help_text="Optional link to an inventory item so the tool's storage location and on-hand count resolve automatically.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tools', to='inventory.inventoryitem')),
                ('maintenance_item', models.ForeignKey(help_text='The maintenance task that requires this tool', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='inventory.maintenanceitem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
