# Generated by Django 6.0.5 on 2026-05-31 17:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0063_maintenance_tools_and_supply_locations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancelog",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Where the work was performed (defaults to the asset's location).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_logs",
                to="inventory.location",
            ),
        ),
        migrations.CreateModel(
            name="MaintenanceLogPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Photo of the work performed",
                        upload_to="maintenance_log_photos/%Y/%m/",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "maintenance_log",
                    models.ForeignKey(
                        help_text="The maintenance log this photo documents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inventory.maintenancelog",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_log_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
