# Generated by Django 6.0.5 on 2026-06-04 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_maintenance_log_location_and_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOutOfService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placed_out_at', models.DateTimeField(auto_now_add=True, help_text='When the OOS was opened')),
                ('expected_return_at', models.DateTimeField(blank=True, help_text="Best-guess return-to-service date; renders as 'expected back: …' on the panel", null=True)),
                ('reason', models.TextField(help_text="Why it's out of service")),
                ('restored_at', models.DateTimeField(blank=True, help_text='When the asset was brought back online. Null means the row is the current active OOS; only one such row per asset.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text="Asset that's out of service", on_delete=django.db.models.deletion.CASCADE, related_name='out_of_service_events', to='inventory.asset')),
                ('placed_by', models.ForeignKey(help_text='Member who placed the asset OOS', on_delete=django.db.models.deletion.PROTECT, related_name='asset_out_of_service_events', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, help_text='Member who cleared the OOS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_restorations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_out_at'],
                'indexes': [models.Index(fields=['asset', 'restored_at'], name='inventory_a_asset_i_ecf5a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short human-readable label, e.g. "Welding Class — John Smith"', max_length=200)),
                ('starts_at', models.DateTimeField(help_text='When the reservation begins')),
                ('ends_at', models.DateTimeField(help_text='When the reservation ends')),
                ('notes', models.TextField(blank=True, help_text='Optional context (room, prerequisites, etc.)')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the reservation was cancelled (soft-delete so the audit history sticks). Cancelled rows do not block new overlapping reservations and never drive the panel face.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Asset being reserved', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.asset')),
                ('reserved_by', models.ForeignKey(help_text='Member who owns the reservation (staff or SIG admin)', on_delete=django.db.models.deletion.PROTECT, related_name='asset_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['asset', 'starts_at'], name='inventory_a_asset_i_f48496_idx'), models.Index(fields=['asset', 'ends_at'], name='inventory_a_asset_i_ae91de_idx')],
            },
        ),
    ]
