# Generated by Django 6.0.5 on 2026-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_assetoutofservice_assetreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='training_required',
            field=models.BooleanField(default=False, help_text="Operators must complete training / hold a certification before using this asset. Surfaced as a TRAINING REQUIRED banner on the e-paper PM panel. Independent of the formal Certification model in membership.* — this is the lightweight 'has the operator been shown how to use this safely' flag."),
        ),
    ]
