# Generated by Django 6.0.5 on 2026-06-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_asset_training_required'),
        ('membership', '0009_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='required_certifications',
            field=models.ManyToManyField(blank=True, help_text='Specific certifications an operator must hold before this asset will unlock. When set, the e-paper panel renders the cert name(s) instead of the generic TRAINING REQUIRED badge. Independent of training_required — set either, both, or neither.', related_name='required_for_assets', to='membership.certification'),
        ),
    ]
