# Generated by Django 6.0.6 on 2026-06-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_asset_required_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreconciliation',
            name='reason',
            field=models.CharField(choices=[('lost', 'Lost'), ('damaged', 'Damaged'), ('miscounted', 'Miscounted'), ('used_without_scan', 'Used without scanning'), ('found', 'Found (positive delta)'), ('vision_supply_check', 'Vision supply check'), ('other', 'Other')], max_length=32),
        ),
    ]
