# Generated by Django 6.0.6 on 2026-06-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0068_alter_stockreconciliation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancelog",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Source work order if this log was auto-written on WO completion.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_logs",
                to="inventory.workorder",
            ),
        ),
    ]
