# Generated by Django 6.0.6 on 2026-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_maintenancelog_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='additional_maintenance_items',
            field=models.ManyToManyField(blank=True, help_text='Sibling PMs on the same asset bundled into this WO via auto-bundling. When the WO is marked completed, every linked item (primary + bundled) gets its last_completed_at advanced and a MaintenanceLog row written.', related_name='bundled_work_orders', to='inventory.maintenanceitem'),
        ),
    ]
