# Generated by Django 6.0.6 on 2026-07-01 02:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0070_workorder_additional_maintenance_items"),
        ("reorder_queue", "0023_alter_purchaseorderauditevent_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="is_serialized",
            field=models.BooleanField(
                default=False,
                help_text="Track individual units of this item by serial number as SerializedComponents",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="serial_tracking_mode",
            field=models.CharField(
                choices=[("consumable", "Consumable"), ("reusable", "Reusable")],
                default="consumable",
                help_text="Consumable components are used up (received -> in_stock -> installed -> consumed -> disposed); reusable components can be installed/removed repeatedly and eventually retired",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SerializedComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Manufacturer or internal serial number uniquely identifying this unit",
                        max_length=200,
                    ),
                ),
                (
                    "lot",
                    models.CharField(
                        blank=True,
                        help_text="Optional batch/lot number for grouped provenance",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("in_stock", "In Stock"),
                            ("installed", "Installed"),
                            ("removed", "Removed"),
                            ("consumed", "Consumed"),
                            ("retired", "Retired"),
                            ("disposed", "Disposed"),
                        ],
                        default="received",
                        help_text="Current lifecycle status of this unit",
                        max_length=20,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, help_text="When this unit was received into stock", null=True
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this unit was most recently installed",
                        null=True,
                    ),
                ),
                (
                    "disposed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this unit was disposed", null=True
                    ),
                ),
                (
                    "disposal_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason recorded when the unit was disposed",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installed_in_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset this component is currently installed in (if installed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_components",
                        to="inventory.asset",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The serialized inventory item this physical unit is an instance of",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serialized_components",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "provenance_delivery_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Delivery line item this unit was received against (provenance)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serialized_components",
                        to="reorder_queue.deliveryitem",
                    ),
                ),
                (
                    "provenance_purchase_order_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Purchase-order line item this unit was ordered against (provenance)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serialized_components",
                        to="reorder_queue.purchaseorderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "serial_number"],
            },
        ),
        migrations.CreateModel(
            name="ComponentUsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("receive", "Receive"),
                            ("install", "Install"),
                            ("remove", "Remove"),
                            ("consume", "Consume"),
                            ("retire", "Retire"),
                            ("dispose", "Dispose"),
                        ],
                        help_text="The lifecycle action performed",
                        max_length=20,
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the action occurred"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional free-text notes about the action"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (if known)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset involved in the action (for install/remove and later transitions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_usage_events",
                        to="inventory.asset",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        help_text="The serialized component this event applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="inventory.serializedcomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="serializedcomponent",
            index=models.Index(fields=["item", "status"], name="inventory_s_item_id_b4a3e5_idx"),
        ),
        migrations.AddIndex(
            model_name="serializedcomponent",
            index=models.Index(fields=["status"], name="inventory_s_status_3acd9c_idx"),
        ),
        migrations.AddIndex(
            model_name="serializedcomponent",
            index=models.Index(
                fields=["installed_in_asset"], name="inventory_s_install_04e951_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="serializedcomponent",
            constraint=models.UniqueConstraint(
                fields=("item", "serial_number"), name="uniq_serialized_component_item_serial"
            ),
        ),
        migrations.AddIndex(
            model_name="componentusageevent",
            index=models.Index(fields=["component", "at"], name="inventory_c_compone_c5d357_idx"),
        ),
        migrations.AddIndex(
            model_name="componentusageevent",
            index=models.Index(fields=["action"], name="inventory_c_action_8c41bd_idx"),
        ),
    ]
