# Generated by Django 6.0.6 on 2026-07-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0071_inventoryitem_is_serialized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetproblem",
            name="affected_parts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which of the asset's parts/components the reporter flagged as needing replacement or repair, so maintenance knows what to fix.",
                related_name="problems",
                to="inventory.assetpart",
            ),
        ),
    ]
