# Generated by Django 6.0.6 on 2026-07-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_assetproblem_affected_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTagSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Calendar year this counter tracks (e.g. 2026).', unique=True)),
                ('alpha', models.CharField(default='A', help_text='Current alpha section, advances when the numeric run passes 999.', max_length=1)),
                ('number', models.PositiveIntegerField(default=0, help_text='Last allocated number for the year (0 means none allocated yet).')),
            ],
            options={
                'verbose_name': 'asset tag sequence',
                'verbose_name_plural': 'asset tag sequences',
                'ordering': ['year'],
            },
        ),
    ]
