# Generated by Django 6.0.6 on 2026-07-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0073_assettagsequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetpart",
            name="replacement_serial_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Serial number of the replacement unit installed at the last replacement (captured only for serialized parts)",
                max_length=200,
            ),
        ),
    ]
