# Generated by Django 6.0.6 on 2026-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0074_assetpart_replacement_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="last_counted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the most recent cycle count", null=True
            ),
        ),
    ]
