# Generated by Django 6.0.6 on 2026-07-07 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_inventoryitem_last_counted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='The document file (manual, CAD source, wiring diagram, cut-sheet, cut-ready template, etc.). Any file type is accepted.', upload_to='assets/documents/%Y/%m/')),
                ('category', models.CharField(choices=[('manual', 'Manual / Documentation'), ('cad_source', 'CAD Source'), ('wiring_diagram', 'Wiring Diagram'), ('cut_sheet_spec', 'Cut Sheet / Spec'), ('cut_ready_template', 'Cut-Ready Template (DXF/SVG/G-code/STL)'), ('photo', 'Photo'), ('other', 'Other')], default='other', help_text='What kind of document this is', max_length=20)),
                ('title', models.CharField(help_text='Human-readable title for the document', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional notes about this document')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number; incremented when this document supersedes an earlier one')),
                ('is_current', models.BooleanField(default=True, help_text='False once a newer version supersedes this document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(help_text='The asset this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.asset')),
                ('supersedes', models.ForeignKey(blank=True, help_text='The prior document version this one replaces (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='inventory.assetdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_asset_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset', 'category', '-version', '-uploaded_at'],
                'indexes': [models.Index(fields=['asset', 'category'], name='inventory_a_asset_i_e85ce3_idx'), models.Index(fields=['asset', 'is_current'], name='inventory_a_asset_i_e68cc2_idx')],
            },
        ),
    ]
