# Generated by Django 6.0.6 on 2026-07-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0076_assetdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="ordering_adapter",
            field=models.CharField(
                choices=[
                    ("none", "None (generic part#,qty pad)"),
                    ("generic_csv", "Generic CSV (part#,qty pad)"),
                    ("amazon", "Amazon (add-to-cart URL)"),
                    ("hdsupply", "HD Supply (Part#,Qty CSV)"),
                ],
                default="none",
                help_text="How the order-pad export builds an order for this supplier: a generic part#,qty pad, an Amazon add-to-cart URL, or an HD Supply Part#,Qty CSV.",
                max_length=20,
            ),
        ),
    ]
