# Generated by Django 6.0.6 on 2026-07-08 00:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0076_assetdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderOmrTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "template_version",
                    models.PositiveIntegerField(
                        help_text="Content signature of the WO's task/material set at print time. A scan is refused if this no longer matches the WO's current tasks."
                    ),
                ),
                ("page_w_pt", models.FloatField(help_text="Form page width in PDF points.")),
                ("page_h_pt", models.FloatField(help_text="Form page height in PDF points.")),
                (
                    "fiducial_dict",
                    models.CharField(
                        default="aruco_4x4_50",
                        help_text="cv2.aruco dictionary the 4 corner fiducials are drawn from.",
                        max_length=32,
                    ),
                ),
                (
                    "fiducials_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The 4 corner fiducial anchors: {corner: {id, cx, cy}} in points.",
                    ),
                ),
                (
                    "regions_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Per-mark region map: list of {target_id, kind, page, rect_norm}. rect_norm is [x0,y0,x1,y1] normalized against the fiducial centers.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="The work order this printed OMR form belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_templates",
                        to="inventory.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("work_order",), name="unique_omr_template_per_work_order"
                    )
                ],
            },
        ),
    ]
