# Generated by Django 6.0.6 on 2026-07-08 00:28

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0078_supplier_ordering_adapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetMeter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Meter name (e.g. 'Spindle runtime', 'Water dispensed')",
                        max_length=100,
                    ),
                ),
                (
                    "meter_type",
                    models.CharField(
                        choices=[
                            ("runtime_hours", "Runtime hours"),
                            ("volume_gallons", "Volume (gallons)"),
                            ("cycles", "Cycles"),
                            ("kwh", "Energy (kWh)"),
                            ("generic_count", "Generic count"),
                        ],
                        default="generic_count",
                        help_text="What this meter measures",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit label for the value (e.g. hours, gallons, cycles, kWh, count)",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto_session", "Auto — usage sessions"),
                            ("auto_telemetry", "Auto — telemetry"),
                            ("manual", "Manual entry"),
                        ],
                        default="manual",
                        help_text="How this meter advances — auto rollup or manual entry",
                        max_length=20,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Cached latest reading value (value_after of the newest reading)",
                        max_digits=14,
                    ),
                ),
                (
                    "current_is_estimated",
                    models.BooleanField(
                        default=False,
                        help_text="True when the current value came from an estimated (eyeballed) reading",
                    ),
                ),
                (
                    "rollup_watermark_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Idempotency watermark for auto_session meters — the ended_at of the last usage session already folded into a reading. The rollup only consumes sessions ended AFTER this, so re-runs are exactly-once.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive meters are skipped by the rollup and hidden by default",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="The asset this meter measures",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="inventory.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssetMeterReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto_session", "Auto — usage sessions"),
                            ("auto_telemetry", "Auto — telemetry"),
                            ("manual", "Manual entry"),
                            ("manual_adjust", "Manual correction"),
                        ],
                        help_text="What produced this reading",
                        max_length=20,
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Signed change to the meter total from this reading",
                        max_digits=14,
                    ),
                ),
                (
                    "value_after",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Meter total immediately after applying this reading",
                        max_digits=14,
                    ),
                ),
                (
                    "is_estimated",
                    models.BooleanField(
                        default=False,
                        help_text="False for measured readings; True for a human eyeball estimate",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        help_text="When the reading was observed / the usage it covers ended"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="Soft provenance string (e.g. 'device_usage x12 ≤<ts>'). Deliberately NOT a foreign key so inventory need not migrate against forgekey.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes (e.g. the reason for a manual correction)",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        help_text="The meter this reading belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="inventory.assetmeter",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded a manual reading (null for automatic rollups)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_meter_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assetmeter",
            index=models.Index(
                fields=["asset", "is_active"], name="inventory_a_asset_i_36d8cb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetmeter",
            unique_together={("asset", "name")},
        ),
        migrations.AddIndex(
            model_name="assetmeterreading",
            index=models.Index(
                fields=["meter", "recorded_at"], name="inventory_a_meter_i_f86d68_idx"
            ),
        ),
    ]
