# Generated by Django 6.0.6 on 2026-07-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_alter_workordersubmission_source'),
        ('inventory', '0079_assetmeter_assetmeterreading_and_more'),
    ]

    operations = [
    ]
