# Generated by Django 6.0.6 on 2026-07-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0079_assetmeter_assetmeterreading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetproblem",
            name="lockout_requested",
            field=models.BooleanField(
                default=False,
                help_text="The reporter asked staff to lock out this asset (e.g. an anonymous scanner tapped 'Request Lockout'). This is a REQUEST for staff to act on, never a direct device actuation.",
            ),
        ),
    ]
