# Generated by Django 6.0.6 on 2026-07-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0080_merge_20260708_1504"),
    ]

    operations = [
        migrations.AddField(
            model_name="serializedcomponent",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Optional expiry/best-by date for this unit. Recorded and displayed only — an expired unit still counts normally in available/on-hand and drives no forecast effect or alert.",
                null=True,
            ),
        ),
    ]
