# Generated by Django 6.0.6 on 2026-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0081_serializedcomponent_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="is_retired",
            field=models.BooleanField(
                default=False,
                help_text="Retired/phased-out: never flagged for reorder; hidden from the list once stock hits 0.",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
