# Generated by Django 6.0.6 on 2026-07-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0082_inventoryitem_is_retired_inventoryitem_retired_at"),
        # The facilities data migration must copy these values off Asset before
        # we drop the columns (issue #880).
        ("facilities", "0002_migrate_asset_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="breaker",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="circuit",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="disconnect",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="needs_compressed_air",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="needs_ventilation",
        ),
    ]
