# Generated by Django 6.0.6 on 2026-07-12 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0083_remove_asset_breaker_remove_asset_circuit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySafetyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_hazardous",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this item is classified as a hazardous material",
                    ),
                ),
                (
                    "msds_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the Material Safety Data Sheet (MSDS) or Safety Data Sheet (SDS)",
                        verbose_name="Material Safety Data Sheet URL",
                    ),
                ),
                (
                    "msds_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload the Material Safety Data Sheet (MSDS/SDS) PDF or document file",
                        null=True,
                        upload_to="inventory/msds/",
                        verbose_name="MSDS/SDS File Upload",
                    ),
                ),
                (
                    "nfpa_health_hazard",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Health hazard rating (0-4): 0=Minimal, 1=Slight, 2=Moderate, 3=High, 4=Extreme",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(4)],
                        verbose_name="NFPA Health Hazard",
                    ),
                ),
                (
                    "nfpa_fire_hazard",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Fire hazard rating (0-4): 0=Minimal, 1=Slight, 2=Moderate, 3=High, 4=Extreme",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(4)],
                        verbose_name="NFPA Fire Hazard",
                    ),
                ),
                (
                    "nfpa_instability_hazard",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Instability/Reactivity hazard rating (0-4): 0=Minimal, 1=Slight, 2=Moderate, 3=High, 4=Extreme",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(4)],
                        verbose_name="NFPA Instability Hazard",
                    ),
                ),
                (
                    "nfpa_special_hazards",
                    models.CharField(
                        blank=True,
                        help_text="Special hazard symbols (e.g., W=Water Reactive, OX=Oxidizer, COR=Corrosive, ALK=Alkali, ACID=Acid, BIO=Biohazard, POI=Poison, RAD=Radioactive)",
                        max_length=20,
                        verbose_name="NFPA Special Hazards",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        help_text="Inventory item these safety details belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_profile",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory safety profile",
                "verbose_name_plural": "Inventory safety profiles",
            },
        ),
    ]
