# Generated by Django 6.0.6 on 2026-07-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0085_migrate_hazmat_to_safety_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="is_hazardous",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="msds_file",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="msds_url",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="nfpa_fire_hazard",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="nfpa_health_hazard",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="nfpa_instability_hazard",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="nfpa_special_hazards",
        ),
    ]
