# Generated by Django 6.0.6 on 2026-07-12 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("inventory", "0086_remove_inventoryitem_is_hazardous_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="ownership_type",
            field=models.CharField(
                choices=[("user", "User"), ("group", "Group"), ("space", "Space")],
                default="space",
                help_text="Type of ownership for this record (user, group, or space)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="owning_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group (SIG) that owns this record (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_owned",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="owning_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this record (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="ownership_type",
            field=models.CharField(
                choices=[("user", "User"), ("group", "Group"), ("space", "Space")],
                default="space",
                help_text="Type of ownership for this record (user, group, or space)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="owning_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group (SIG) that owns this record (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_owned",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="owning_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this record (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
