# Generated by Django 6.0.6 on 2026-07-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0087_ownership_abstraction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fixturerefillrequest",
            name="requested_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user who requested this refill (null if anonymous/system)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixture_refill_requests_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixturerefillrequest",
            name="resolved_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user who resolved this request (null if anonymous/system)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixture_refill_requests_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fixturerefillrequest",
            name="requested_by",
            field=models.CharField(
                blank=True,
                help_text="Display name of person who reported this (anon-supplied, or the authenticated user's handle/username); the *_name half of requested_user",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="fixturerefillrequest",
            name="resolved_by",
            field=models.CharField(
                blank=True,
                help_text="Display name of person who resolved this request; the *_name half of resolved_user",
                max_length=200,
            ),
        ),
    ]
