# Generated by Django 6.0.6 on 2026-07-15 15:59

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def _backfill_quantity_used(apps, schema_editor):
    """Seed ``quantity_used`` from ``quantity_planned`` for existing rows.

    New rows default to 1.00, but rows that pre-date this field already carry
    the maintenance-material spec quantity in ``quantity_planned`` — copy it so
    a later "used" check decrements the meaningful planned amount, not a flat 1.
    """
    WorkOrderMaterialUsage = apps.get_model("inventory", "WorkOrderMaterialUsage")
    WorkOrderMaterialUsage.objects.update(quantity_used=models.F("quantity_planned"))


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0089_backfill_fixture_refill_actor"),
    ]

    operations = [
        migrations.AddField(
            model_name="workordermaterialusage",
            name="applied_quantity",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Whole stock units decremented from the linked inventory item for this usage; null when no decrement is currently applied. Reversal restores exactly this amount.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workordermaterialusage",
            name="quantity_used",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Quantity actually consumed. When this row is marked used and the material links to an inventory item, the item's stock is decremented by this amount (rounded to whole stock units) and a UsageLog row is written. Defaults to the planned quantity.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="workordermaterialusage",
            name="usage_log",
            field=models.ForeignKey(
                blank=True,
                help_text="UsageLog row written when stock was decremented; voided on reversal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inventory.usagelog",
            ),
        ),
        migrations.RunPython(_backfill_quantity_used, migrations.RunPython.noop),
    ]
