# Generated by Django 6.0.6 on 2026-07-15 16:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0090_wo_material_usage_decrement"),
        ("loto", "0004_repoint_derived_from_to_breaker"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="loto_completion_note",
            field=models.TextField(
                blank=True,
                help_text="Free-text lockout/tagout completion note recorded web-side. The structured per-energy-source boxes (WorkOrderLotoCompletion) are the OMR-readable half; this is the free-text half of 'LOTO = both'.",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderLotoCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized energy-source type code (preserved if source deleted)",
                        max_length=20,
                    ),
                ),
                (
                    "source_label",
                    models.CharField(
                        help_text="Denormalized human label, e.g. 'Electrical (240V)'",
                        max_length=200,
                    ),
                ),
                (
                    "isolation_point",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized isolation point (where to lock out)",
                        max_length=200,
                    ),
                ),
                (
                    "required_devices",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized comma-joined list of required lockout devices",
                        max_length=300,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this energy source has been isolated / locked out",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_work_order_loto",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "energy_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="The energy source (null if it was deleted after WO creation)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_completions",
                        to="loto.assetenergysource",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="The work order this LOTO completion belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loto_completions",
                        to="inventory.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["source_type", "source_label"],
                "indexes": [
                    models.Index(
                        fields=["work_order", "is_completed"], name="wolc_wo_completed_idx"
                    )
                ],
            },
        ),
    ]
