# Generated by Django 6.0.7 on 2026-07-17 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hordak", "0055_alter_leg_credit_alter_leg_currency_alter_leg_debit"),
        ("inventory", "0091_workorder_loto_completion_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usagelog",
            name="charged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who recorded this consumption.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="charged_group",
            field=models.ForeignKey(
                blank=True,
                help_text="The committee (SIG) charged for this consumption, if any.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charged_usage_logs",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="ledger_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="The posted SIG_CHARGE journal entry, if a committee was charged.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hordak.transaction",
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Snapshot of unit_cost x quantity_used at consume time (null when cost unknown).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Snapshot of the item's unit cost at consume time (may be unknown).",
                max_digits=10,
                null=True,
            ),
        ),
    ]
