# Generated by Django 6.0.7 on 2026-07-19 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0092_usagelog_charged_by_usagelog_charged_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="reorder_alerts_enabled",
            field=models.BooleanField(
                default=False, help_text="Watch this item for ML reorder alerts"
            ),
        ),
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Timestamp of the forecast run that produced this row.",
                    ),
                ),
                (
                    "horizon_days",
                    models.PositiveIntegerField(
                        help_text="Lead time + buffer used for the projection window."
                    ),
                ),
                (
                    "predicted_daily_demand",
                    models.FloatField(help_text="Mean predicted demand per day (yhat)."),
                ),
                (
                    "horizon_demand",
                    models.FloatField(help_text="Sum of predicted demand (yhat) over the horizon."),
                ),
                (
                    "horizon_demand_upper",
                    models.FloatField(
                        help_text="Sum of the upper prediction band (yhat_upper) over the horizon; drives safety stock."
                    ),
                ),
                (
                    "available_at_generation",
                    models.IntegerField(
                        help_text="Snapshot of available/on-hand stock used for this projection."
                    ),
                ),
                ("days_until_stockout", models.FloatField(blank=True, null=True)),
                ("projected_stockout_date", models.DateField(blank=True, null=True)),
                ("predictive_reorder_point", models.IntegerField()),
                (
                    "needs_reorder",
                    models.BooleanField(
                        help_text="available_at_generation <= predictive_reorder_point at generation time."
                    ),
                ),
                ("lead_time_days", models.IntegerField(blank=True, null=True)),
                ("safety_stock", models.IntegerField(default=0)),
                (
                    "method",
                    models.CharField(
                        choices=[("prophet", "Prophet"), ("fallback", "Statistical fallback")],
                        max_length=20,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, help_text='Model identifier, e.g. "prophet-1".', max_length=32
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_forecasts",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "get_latest_by": "generated_at",
                "indexes": [
                    models.Index(
                        fields=["item", "-generated_at"], name="inventory_d_item_id_ef722d_idx"
                    )
                ],
            },
        ),
    ]
