# Generated by Django 6.0.7 on 2026-07-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0093_demand_forecast_and_reorder_alerts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandforecast",
            name="method",
            field=models.CharField(
                choices=[
                    ("prophet", "Prophet"),
                    ("holtwinters", "Holt-Winters seasonal"),
                    ("fallback", "Statistical fallback"),
                ],
                max_length=20,
            ),
        ),
    ]
