# Generated by Django 6.0.7 on 2026-07-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0094_add_holtwinters_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandforecast",
            name="avg_interval_days",
            field=models.FloatField(
                blank=True,
                help_text="Mean number of days between this item's purchase events; NULL when there is not enough history to average one.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="days_until_due",
            field=models.FloatField(
                blank=True,
                help_text="Days from generation to predicted_next_reorder_date; negative when overdue.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="interval_samples",
            field=models.IntegerField(
                default=0,
                help_text="Number of gaps the average was taken over (purchase events - 1).",
            ),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="last_restock_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the most recent purchase event for this item.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="predicted_next_reorder_date",
            field=models.DateField(
                blank=True,
                help_text="last_restock_date + avg_interval_days -- when the item is due to be bought again.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="available_at_generation",
            field=models.IntegerField(
                help_text="Snapshot of available/on-hand stock at generation. Informational under the interval model -- it does not drive needs_reorder."
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="days_until_stockout",
            field=models.FloatField(
                blank=True, help_text="Retired (v1): available / predicted daily demand.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="horizon_days",
            field=models.PositiveIntegerField(
                help_text="Retired (v1): lead time + buffer used for the projection window."
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="horizon_demand",
            field=models.FloatField(
                help_text="Retired (v1): sum of predicted demand (yhat) over the horizon."
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="horizon_demand_upper",
            field=models.FloatField(
                help_text="Retired (v1): sum of the upper prediction band (yhat_upper) over the horizon."
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="method",
            field=models.CharField(
                choices=[
                    ("restock_interval", "Restock interval"),
                    ("insufficient_history", "Insufficient history"),
                    ("prophet", "Prophet"),
                    ("holtwinters", "Holt-Winters seasonal"),
                    ("fallback", "Statistical fallback"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="model_version",
            field=models.CharField(
                blank=True, help_text='Model identifier, e.g. "interval-1".', max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="needs_reorder",
            field=models.BooleanField(
                help_text="Item is due to be bought: days_until_due <= lead_time_days at generation time."
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="predicted_daily_demand",
            field=models.FloatField(
                help_text="Retired (v1): mean predicted demand per day (yhat)."
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="predictive_reorder_point",
            field=models.IntegerField(
                help_text="Retired (v1): stock level the v1 projection reordered at."
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="projected_stockout_date",
            field=models.DateField(
                blank=True,
                help_text="Retired (v1): date the v1 projection ran the item to zero.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="safety_stock",
            field=models.IntegerField(
                default=0, help_text="Retired (v1): buffer built from the v1 prediction band."
            ),
        ),
    ]
