# Generated by Django 6.0.7 on 2026-07-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0095_demand_forecast_restock_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetask",
            name="reference_image",
            field=models.ImageField(
                blank=True,
                help_text="Instructional photo for this step — 'here is what this should look like'. Defined once on the template, printed next to the step on the work-order form and shown on the digital work order. This is the reference half; the photo a tech takes while performing the work is an evidence WorkOrderPhoto linked to the step's completion row.",
                null=True,
                upload_to="maintenance_task_reference/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="workorderphoto",
            name="task_completion",
            field=models.ForeignKey(
                blank=True,
                help_text="The step this photo documents. Null for work-order-level photos (and for photos whose step row was deleted).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence_photos",
                to="inventory.workordertaskcompletion",
            ),
        ),
    ]
