# Generated by Django 6.0.7 on 2026-07-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0096_step_reference_and_evidence_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="elapsed_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Committed time in seconds. Excludes the segment currently running — read the serializer's live value for the running total.",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="is_timing",
            field=models.BooleanField(
                default=False, help_text="Whether the stopwatch is running right now."
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When work first started on this order (the first time the timer was started). Never reset by a later pause/resume.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="timing_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of the segment currently running (null while paused).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workordertaskcompletion",
            name="elapsed_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Committed time in seconds. Excludes the segment currently running — read the serializer's live value for the running total.",
            ),
        ),
        migrations.AddField(
            model_name="workordertaskcompletion",
            name="is_timing",
            field=models.BooleanField(
                default=False, help_text="Whether the stopwatch is running right now."
            ),
        ),
        migrations.AddField(
            model_name="workordertaskcompletion",
            name="timing_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of the segment currently running (null while paused).",
                null=True,
            ),
        ),
    ]
