# Generated by Django 6.0.7 on 2026-07-23 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_asset_problem_work_order_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterialusage',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Direct stock link for an ad-hoc line. Set it to draw the material from tracked inventory when the line is marked used; leave it null for an out-of-pocket buy, which moves no stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_material_usage', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='workordermaterialusage',
            name='is_ad_hoc',
            field=models.BooleanField(default=False, help_text='True when this line was added during the job rather than copied from the PM template. Only ad-hoc lines can be removed.'),
        ),
        migrations.AddField(
            model_name='workordermaterialusage',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Photo of the receipt backing an out-of-pocket purchase.', null=True, upload_to='work_orders/receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='workordermaterialusage',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price per unit paid.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workordermaterialusage',
            name='material',
            field=models.ForeignKey(blank=True, help_text='The material specification (null if deleted after WO creation, or if this is an ad-hoc line typed in during the job)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='inventory.maintenancematerial'),
        ),
    ]
