# Generated by Django 6.0.7 on 2026-07-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0101_work_order_actual_materials_cost'),
        ('reorder_queue', '0023_alter_purchaseorderauditevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterialusage',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, help_text='Purchase-order line this material was received from (null if it was entered by hand, or if the PO line was deleted afterwards).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_material_usage', to='reorder_queue.purchaseorderitem'),
        ),
    ]
