# Generated by Django 6.0.7 on 2026-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_workordermaterialusage_purchase_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_cost_recoverable',
            field=models.BooleanField(default=False, help_text='Landlord-billable; in-house repair cost on this asset flows into the cost-recovery Actual (recoverable) column.'),
        ),
    ]
