# Generated by Django 6.0.7 on 2026-07-24 01:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0104_seed_hvac_cost_recoverable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached file — photo, document, receipt, or anything else",
                        upload_to="work_orders/attachments/%Y/%m/",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Photo"), ("document", "Document"), ("other", "Other")],
                        default="other",
                        help_text="Rough category, so the attachments list can be grouped",
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_work_order_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="The work order this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="inventory.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(fields=["work_order", "kind"], name="woa_wo_kind_idx"),
                    models.Index(fields=["-uploaded_at"], name="woa_uploaded_idx"),
                ],
            },
        ),
    ]
