# Generated by Django 6.0.7 on 2026-07-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0105_work_order_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLevelSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        help_text="The item's current_stock at the moment the snapshot was taken."
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        db_index=True,
                        help_text="Week the snapshot represents (the run's week-start date).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_snapshots",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["item", "snapshot_date"], name="inventory_s_item_id_9fe659_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "snapshot_date"), name="uniq_stock_snapshot_per_item_week"
                    )
                ],
            },
        ),
    ]
