# Generated by Django 6.0.7 on 2026-07-27 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0106_stocklevelsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short name for the agreement (e.g. '2026 nonprofit pricing')", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Terms, pricing notes, contacts')),
                ('document', models.FileField(blank=True, help_text='Optional scan/PDF of the signed agreement or quote', null=True, upload_to='supplier_agreements/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive agreements are hidden when picking one on a purchase order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(help_text='Supplier this agreement is with', on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
