# Generated by Django 6.0.7 on 2026-07-28 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0107_supplieragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='base_unit',
            field=models.CharField(default='unit', help_text="Label for the smallest countable thing (e.g. 'sheet', 'bottle', 'unit'). current_stock is always expressed in these.", max_length=40),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='count_mode',
            field=models.CharField(choices=[('each', 'Each (count individual base units)'), ('by_level', 'By packaging level (count whole packs)'), ('open_closed', 'Sealed + open (count sealed packs, track open ones)')], default='each', help_text="Granularity this item is counted at. 'Each' counts base units (today's behaviour); the other modes count whole packs of count_level.", max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='open_container_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of currently-OPEN packs (sealed + open counting mode); typically 0 or 1.'),
        ),
        migrations.CreateModel(
            name='PackagingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What this rung is called: 'case', 'ream', 'bottle', 'bag', 'sheet', 'roll'…", max_length=40)),
                ('sort_order', models.PositiveIntegerField(help_text='0 = outermost/largest rung; increases toward the base unit.')),
                ('base_units', models.PositiveIntegerField(help_text="How many of the item's base units ONE of this rung holds. The base rung is 1.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_levels', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['item', 'sort_order'],
                'unique_together': {('item', 'sort_order')},
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='count_level',
            field=models.ForeignKey(blank=True, help_text="Which packaging level is the counting granularity. Must be one of this item's packaging levels; null for 'Each'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.packaginglevel'),
        ),
    ]
