# Generated by Django 6.0.7 on 2026-08-11 07:40

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0108_packaging_levels_and_count_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "is_ad_hoc",
                    models.BooleanField(
                        default=False,
                        help_text="True when this tool was added during the job rather than copied from the PM template. Only ad-hoc rows can be removed.",
                    ),
                ),
                ("name", models.CharField(help_text="Denormalized tool name", max_length=200)),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, help_text="How many are needed"),
                ),
                (
                    "location_hint",
                    models.CharField(
                        blank=True,
                        help_text="Where this tool is staged for THIS job (e.g., 'Bench 2'). Editable on the work order; overrides the linked inventory item's location and never writes back to the PM template.",
                        max_length=200,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Required tools are highlighted on the work order"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about the tool or its use"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to an inventory item so the tool's storage location resolves automatically when no per-job location is set.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_tools",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        blank=True,
                        help_text="The template tool this row was copied from (null if the template tool was deleted after WO generation, or if this is an ad-hoc row added during the job). Provenance only — never read for display.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_tools",
                        to="inventory.maintenancetool",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="The work order this tool belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="inventory.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_required", django.db.models.functions.text.Lower("name"), "name"],
                "indexes": [models.Index(fields=["work_order"], name="wotool_wo_idx")],
            },
        ),
    ]
