# Generated by Django 6.0.7 on 2026-08-11 02:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0108_packaging_levels_and_count_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="is_kit",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="This SKU is a kit: buying one line of it delivers the quantities listed in its components, which is where received stock is credited.",
            ),
        ),
        migrations.CreateModel(
            name="KitComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many of this component one kit contains (e.g. 1 cyan cartridge)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        help_text="The stock item contained in the kit",
                        limit_choices_to={"is_kit": False},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplied_by_kits",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        help_text="The kit SKU that contains this component",
                        limit_choices_to={"is_kit": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_components",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["kit", "component__name"],
                "indexes": [
                    models.Index(fields=["kit", "component"], name="inventory_k_kit_id_99f00c_idx"),
                    models.Index(
                        fields=["component", "kit"], name="inventory_k_compone_9081f1_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kit", models.F("component")), _negated=True),
                        name="kit_component_no_self_reference",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)),
                        name="kit_component_quantity_positive",
                    ),
                ],
                "unique_together": {("kit", "component")},
            },
        ),
    ]
