# Generated by Django 6.0.7 on 2026-09-04 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0110_workordertool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_cases",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How this item's reorder amount is PRESENTED, in cases/packages, when case-based reordering is enabled. It does not affect what is ordered — a reorder orders 'Reorder quantity', in base units, and any surface that promises what will actually be filed shows that number instead, so set it too.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
