# Generated by Django 6.0.7 on 2026-09-04 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0110_workordertool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_cases",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Never affects what is ordered. Sizes only how a reorder amount is presented, and only for an item whose counting mode gives this column meaning.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
