# Generated by Django 6.0.7 on 2026-09-04 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0110_workordertool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_cases",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of cases/packages this item's reorder amount is SHOWN as, when case-based reordering is enabled. Display only — a reorder actually orders 'Reorder quantity', in base units, so set that one too.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
