# Generated by Django 6.0.7 on 2026-09-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0111_alter_inventoryitem_reorder_cases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsupplier",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per individual unit from this supplier. Derived from the package cost; changing it re-prices the package.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
