# Generated by Django 6.0.7 on 2026-09-13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0116_itemsupplier_deferrable_pair_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_cases",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Whole cases to order when a case-based item is low. Each case is the package size of the supplier it is ordered from; if that size is not known, ordering stays on the existing base-unit calculation. Not used for an item counted in packaging levels. Stock is still counted in individual units.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
