version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      - vscode-server:/home/vscode/.vscode-server
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://makerspace:changeme_in_production@db:5432/makerspace_inventory
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=1
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENTRY_ENVIRONMENT=development
      - CI=true  # Match CI environment for consistent test behavior
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - default

  # Override frontend service for development
  frontend:
    volumes:
      - ../frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN:-}
      - CI=true  # Consistent with CI environment
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm start"

  # Override backend for development
  backend:
    volumes:
      - ../backend:/app:cached
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://makerspace:changeme_in_production@db:5432/makerspace_inventory
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENTRY_ENVIRONMENT=development

volumes:
  vscode-server:
  frontend_node_modules:
