# Generated by Django 5.1.15 on 2026-04-30 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0052_add_location_problem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "panel",
                    models.CharField(
                        help_text="Panel name or designation (e.g. 'Panel A', 'Main')",
                        max_length=50,
                    ),
                ),
                (
                    "breaker_number",
                    models.CharField(
                        help_text="Slot or number on the panel (e.g. '12', '14/16')", max_length=20
                    ),
                ),
                (
                    "amperage",
                    models.PositiveIntegerField(
                        help_text="Trip amperage of the breaker",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "voltage",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Nominal voltage (e.g. 120, 240)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "poles",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of poles (1=single, 2=double, 3=three-phase)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional human description (e.g. 'Wood shop dust collector')",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location of the panel that holds this breaker",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breakers",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["panel", "breaker_number"],
            },
        ),
        migrations.CreateModel(
            name="LightSwitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Local identifier within the location (e.g. 'door-east')",
                        max_length=80,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breaker",
                    models.ForeignKey(
                        blank=True,
                        help_text="Breaker that feeds this lighting circuit",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="light_switches",
                        to="electrical_circuits.breaker",
                    ),
                ),
                (
                    "controls_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location whose lights this switch controls (if different)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlling_switches",
                        to="inventory.location",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location where the switch is mounted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="light_switches",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["location__name", "identifier"],
            },
        ),
        migrations.CreateModel(
            name="NetworkDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Jack label or local identifier (e.g. 'wallplate-3A')",
                        max_length=80,
                    ),
                ),
                (
                    "drop_type",
                    models.CharField(
                        choices=[
                            ("data", "Data jack"),
                            ("voice", "Voice / phone"),
                            ("patch_panel", "Patch panel termination"),
                            ("ap", "Wireless access point"),
                            ("camera", "Camera"),
                            ("iot", "IoT sensor"),
                            ("other", "Other"),
                        ],
                        default="data",
                        max_length=20,
                    ),
                ),
                (
                    "patch_panel",
                    models.CharField(
                        blank=True,
                        help_text="Upstream patch panel name (e.g. 'IDF-1 patch panel B')",
                        max_length=80,
                    ),
                ),
                (
                    "patch_port",
                    models.CharField(
                        blank=True,
                        help_text="Port number on the upstream patch panel",
                        max_length=20,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="MAC address of the connected device, if known",
                        max_length=17,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Approximate description of the connected device"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="electrical_circuits/network_drops/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Physical location of the drop",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_drops",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["location__name", "identifier"],
            },
        ),
        migrations.CreateModel(
            name="Outlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Local identifier within the location (e.g. 'NW-bench-1')",
                        max_length=80,
                    ),
                ),
                (
                    "outlet_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard 120V"),
                            ("240v", "240V"),
                            ("nema_5_15", "NEMA 5-15 (120V 15A)"),
                            ("nema_5_20", "NEMA 5-20 (120V 20A)"),
                            ("nema_6_15", "NEMA 6-15 (240V 15A)"),
                            ("nema_6_20", "NEMA 6-20 (240V 20A)"),
                            ("nema_l6_30", "NEMA L6-30 (240V 30A locking)"),
                            ("nema_14_30", "NEMA 14-30 (240V 30A)"),
                            ("nema_14_50", "NEMA 14-50 (240V 50A)"),
                            ("usb", "USB charging"),
                            ("other", "Other"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "plugged_in_notes",
                    models.TextField(
                        blank=True, help_text="Approximate description of what is plugged in"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="electrical_circuits/outlets/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breaker",
                    models.ForeignKey(
                        blank=True,
                        help_text="Breaker that feeds this outlet (null if unknown)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outlets",
                        to="electrical_circuits.breaker",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location of the outlet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlets",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["location__name", "identifier"],
            },
        ),
        migrations.AddIndex(
            model_name="breaker",
            index=models.Index(fields=["location"], name="electrical__locatio_96393d_idx"),
        ),
        migrations.AddIndex(
            model_name="breaker",
            index=models.Index(fields=["panel"], name="electrical__panel_44c883_idx"),
        ),
        migrations.AddConstraint(
            model_name="breaker",
            constraint=models.UniqueConstraint(
                fields=("location", "panel", "breaker_number"),
                name="electrical_circuits_breaker_unique_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="lightswitch",
            index=models.Index(fields=["location"], name="electrical__locatio_0a2f3d_idx"),
        ),
        migrations.AddIndex(
            model_name="lightswitch",
            index=models.Index(fields=["breaker"], name="electrical__breaker_ac3321_idx"),
        ),
        migrations.AddIndex(
            model_name="lightswitch",
            index=models.Index(fields=["controls_location"], name="electrical__control_41d1df_idx"),
        ),
        migrations.AddConstraint(
            model_name="lightswitch",
            constraint=models.UniqueConstraint(
                fields=("location", "identifier"),
                name="electrical_circuits_lightswitch_unique_identifier",
            ),
        ),
        migrations.AddIndex(
            model_name="networkdrop",
            index=models.Index(fields=["location"], name="electrical__locatio_3f731e_idx"),
        ),
        migrations.AddIndex(
            model_name="networkdrop",
            index=models.Index(fields=["drop_type"], name="electrical__drop_ty_dcaa06_idx"),
        ),
        migrations.AddIndex(
            model_name="networkdrop",
            index=models.Index(fields=["patch_panel"], name="electrical__patch_p_13c615_idx"),
        ),
        migrations.AddConstraint(
            model_name="networkdrop",
            constraint=models.UniqueConstraint(
                fields=("location", "identifier"),
                name="electrical_circuits_networkdrop_unique_identifier",
            ),
        ),
        migrations.AddIndex(
            model_name="outlet",
            index=models.Index(fields=["location"], name="electrical__locatio_863428_idx"),
        ),
        migrations.AddIndex(
            model_name="outlet",
            index=models.Index(fields=["breaker"], name="electrical__breaker_124dda_idx"),
        ),
        migrations.AddConstraint(
            model_name="outlet",
            constraint=models.UniqueConstraint(
                fields=("location", "identifier"),
                name="electrical_circuits_outlet_unique_identifier",
            ),
        ),
    ]
