# Generated by Django 5.1.15 on 2026-05-02 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electrical_circuits", "0001_initial"),
        ("inventory", "0054_add_workorder_validation_and_review_queue"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerBreaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Slot number on the panel (e.g. '12', '14/16' for tandem)",
                        max_length=20,
                    ),
                ),
                (
                    "pole_count",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1 pole"), (2, "2 pole"), (3, "3 pole")], default=1
                    ),
                ),
                (
                    "amperage",
                    models.PositiveIntegerField(
                        help_text="Trip amperage of the breaker",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("A", "Phase A"),
                            ("B", "Phase B"),
                            ("C", "Phase C"),
                            ("AB", "Phases A+B"),
                            ("BC", "Phases B+C"),
                            ("AC", "Phases A+C"),
                            ("ABC", "Phases A+B+C"),
                        ],
                        default="A",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("spare", "Spare"),
                            ("locked_out", "Locked out"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label (e.g., 'Wood shop dust collector')",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["panel__name", "position"],
            },
        ),
        migrations.CreateModel(
            name="PowerCircuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Circuit label (e.g., 'Bench row 1')", max_length=200
                    ),
                ),
                (
                    "conductor_size",
                    models.CharField(
                        blank=True,
                        help_text="Conductor gauge (e.g., '12 AWG', '10 AWG')",
                        max_length=20,
                    ),
                ),
                (
                    "conductor_length_ft",
                    models.PositiveIntegerField(
                        blank=True, help_text="Approximate conductor run length in feet", null=True
                    ),
                ),
                (
                    "max_load_amps",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum continuous load in amps. Defaults to breaker amperage × 0.8 if not set explicitly.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circuits",
                        to="electrical_circuits.powerbreaker",
                    ),
                ),
            ],
            options={
                "ordering": ["breaker__panel__name", "breaker__position"],
            },
        ),
        migrations.CreateModel(
            name="PowerOutlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "outlet_type",
                    models.CharField(
                        choices=[
                            ("5-15R", "NEMA 5-15R (120V 15A)"),
                            ("5-20R", "NEMA 5-20R (120V 20A)"),
                            ("6-15R", "NEMA 6-15R (240V 15A)"),
                            ("6-20R", "NEMA 6-20R (240V 20A)"),
                            ("L5-15R", "NEMA L5-15R (120V 15A locking)"),
                            ("L5-20R", "NEMA L5-20R (120V 20A locking)"),
                            ("L6-20R", "NEMA L6-20R (240V 20A locking)"),
                            ("L6-30R", "NEMA L6-30R (240V 30A locking)"),
                            ("14-30R", "NEMA 14-30R (240V 30A)"),
                            ("14-50R", "NEMA 14-50R (240V 50A)"),
                            ("USB", "USB charging"),
                            ("OTHER", "Other"),
                        ],
                        default="5-15R",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Local identifier (e.g., 'NW-bench-1')", max_length=80
                    ),
                ),
                (
                    "location_description",
                    models.CharField(
                        blank=True,
                        help_text="Physical placement (e.g., 'east wall, 3 ft from corner')",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("capped", "Capped / decommissioned"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outlets",
                        to="electrical_circuits.powercircuit",
                    ),
                ),
                (
                    "legacy_outlet",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to the legacy Outlet row this was migrated from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="power_outlet",
                        to="electrical_circuits.outlet",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="power_outlets",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["location__name", "label"],
            },
        ),
        migrations.CreateModel(
            name="PowerPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Panel name (e.g., 'Sewing Panel A', 'Main Distribution')",
                        max_length=100,
                    ),
                ),
                (
                    "phase_configuration",
                    models.CharField(
                        choices=[
                            ("single", "Single phase"),
                            ("split", "Split phase (120/240V)"),
                            ("three", "Three phase"),
                        ],
                        default="split",
                        max_length=10,
                    ),
                ),
                (
                    "voltage",
                    models.PositiveIntegerField(
                        default=240,
                        help_text="Nominal voltage rating (e.g. 120, 208, 240, 480)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "main_breaker_amperage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Main breaker amperage (null if no main / sub-fed)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("install_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="True for migration-created placeholders that require admin review",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Site/Location where the panel is mounted",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="power_panels",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["location__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="powerbreaker",
            name="panel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breakers",
                to="electrical_circuits.powerpanel",
            ),
        ),
        migrations.CreateModel(
            name="PowerPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Port label (e.g., 'Main', 'Auxiliary', 'PSU 1')", max_length=80
                    ),
                ),
                (
                    "port_type",
                    models.CharField(
                        choices=[
                            ("5-15R", "NEMA 5-15R (120V 15A)"),
                            ("5-20R", "NEMA 5-20R (120V 20A)"),
                            ("6-15R", "NEMA 6-15R (240V 15A)"),
                            ("6-20R", "NEMA 6-20R (240V 20A)"),
                            ("L5-15R", "NEMA L5-15R (120V 15A locking)"),
                            ("L5-20R", "NEMA L5-20R (120V 20A locking)"),
                            ("L6-20R", "NEMA L6-20R (240V 20A locking)"),
                            ("L6-30R", "NEMA L6-30R (240V 30A locking)"),
                            ("14-30R", "NEMA 14-30R (240V 30A)"),
                            ("14-50R", "NEMA 14-50R (240V 50A)"),
                            ("USB", "USB charging"),
                            ("OTHER", "Other"),
                        ],
                        default="5-15R",
                        max_length=20,
                    ),
                ),
                (
                    "max_draw_amps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nameplate max current draw in amps",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_ports",
                        to="inventory.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__name", "label"],
            },
        ),
        migrations.AddIndex(
            model_name="powercircuit",
            index=models.Index(fields=["breaker"], name="electrical__breaker_0efcc1_idx"),
        ),
        migrations.AddIndex(
            model_name="poweroutlet",
            index=models.Index(fields=["circuit"], name="electrical__circuit_595f0e_idx"),
        ),
        migrations.AddIndex(
            model_name="poweroutlet",
            index=models.Index(fields=["location"], name="electrical__locatio_30c941_idx"),
        ),
        migrations.AddIndex(
            model_name="poweroutlet",
            index=models.Index(fields=["outlet_type"], name="electrical__outlet__614582_idx"),
        ),
        migrations.AddConstraint(
            model_name="poweroutlet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("label__gt", "")),
                fields=("location", "label"),
                name="electrical_circuits_poweroutlet_unique_label",
            ),
        ),
        migrations.AddIndex(
            model_name="powerpanel",
            index=models.Index(fields=["location"], name="electrical__locatio_261853_idx"),
        ),
        migrations.AddConstraint(
            model_name="powerpanel",
            constraint=models.UniqueConstraint(
                fields=("location", "name"), name="electrical_circuits_powerpanel_unique_name"
            ),
        ),
        migrations.AddIndex(
            model_name="powerbreaker",
            index=models.Index(fields=["panel"], name="electrical__panel_i_58adff_idx"),
        ),
        migrations.AddIndex(
            model_name="powerbreaker",
            index=models.Index(fields=["status"], name="electrical__status_632d5e_idx"),
        ),
        migrations.AddConstraint(
            model_name="powerbreaker",
            constraint=models.UniqueConstraint(
                fields=("panel", "position"),
                name="electrical_circuits_powerbreaker_unique_position",
            ),
        ),
        migrations.AddIndex(
            model_name="powerport",
            index=models.Index(fields=["asset"], name="electrical__asset_i_cbe75d_idx"),
        ),
        migrations.AddIndex(
            model_name="powerport",
            index=models.Index(fields=["port_type"], name="electrical__port_ty_01f87d_idx"),
        ),
        migrations.AddConstraint(
            model_name="powerport",
            constraint=models.UniqueConstraint(
                fields=("asset", "label"), name="electrical_circuits_powerport_unique_label"
            ),
        ),
    ]
