# Generated by Django 5.1.15 on 2026-05-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("electrical_circuits", "0003_migrate_legacy_outlets_to_power_topology"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cable_type",
                    models.CharField(
                        choices=[("power", "Power"), ("network", "Network")],
                        help_text="Determines which endpoint pairing is valid (power vs network).",
                        max_length=10,
                    ),
                ),
                ("endpoint_a_object_id", models.CharField(max_length=64)),
                ("endpoint_b_object_id", models.CharField(max_length=64)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Optional cable color (useful in dense racks).",
                        max_length=30,
                    ),
                ),
                (
                    "length_ft",
                    models.PositiveIntegerField(
                        blank=True, help_text="Approximate cable length in feet.", null=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional cable label (e.g., printed sleeve text).",
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("planned", "Planned"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="connected",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint_a_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "endpoint_b_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["cable_type", "label"],
                "indexes": [
                    models.Index(
                        fields=["endpoint_a_content_type", "endpoint_a_object_id"],
                        name="ec_cable_endpoint_a_idx",
                    ),
                    models.Index(
                        fields=["endpoint_b_content_type", "endpoint_b_object_id"],
                        name="ec_cable_endpoint_b_idx",
                    ),
                    models.Index(fields=["cable_type"], name="electrical__cable_t_7db92e_idx"),
                    models.Index(fields=["status"], name="electrical__status_ed0eae_idx"),
                ],
            },
        ),
    ]
