# Generated by Django 5.1.15 on 2026-05-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electrical_circuits", "0004_cable"),
        ("loto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerbreaker",
            name="required_loto_devices",
            field=models.ManyToManyField(
                blank=True,
                help_text="LOTO devices required to safely isolate this breaker. Propagates to AssetEnergySource rows derived from cables fed by this breaker.",
                related_name="breakers",
                to="loto.lotodevice",
            ),
        ),
    ]
