# Generated by Django 5.1.15 on 2026-05-18 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_circuits', '0005_powerbreaker_required_loto_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpanel',
            name='fed_by',
            field=models.ForeignKey(blank=True, help_text='Upstream feeder circuit. Leave blank for the main / service-entrance panel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_panels', to='electrical_circuits.powercircuit'),
        ),
    ]
