# Generated by Django 5.1.15 on 2026-05-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_circuits', '0006_powerpanel_fed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbreaker',
            name='review_note',
            field=models.TextField(blank=True, help_text='Free-text context for the review flag (what changed, by whom, when).'),
        ),
        migrations.AddField(
            model_name='powerbreaker',
            name='review_status',
            field=models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs attention — active but circuit confirmed gone/wrong'), ('circuit_moved', 'Circuit moved — awaiting cleanup')], default='ok', help_text="Operator review flag for stale wiring. 'needs_attention' = red (active but downstream wiring is wrong/missing), 'circuit_moved' = grey (known to be reassigned, cleanup pending).", max_length=20),
        ),
    ]
