# Generated by Django 5.1.15 on 2026-05-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_circuits', '0007_powerbreaker_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poweroutlet',
            name='outlet_type',
            field=models.CharField(choices=[('5-15R', 'NEMA 5-15R (120V 15A)'), ('5-20R', 'NEMA 5-20R (120V 20A)'), ('6-15R', 'NEMA 6-15R (240V 15A)'), ('6-20R', 'NEMA 6-20R (240V 20A)'), ('L5-15R', 'NEMA L5-15R (120V 15A locking)'), ('L5-20R', 'NEMA L5-20R (120V 20A locking)'), ('L5-30R', 'NEMA L5-30R (120V 30A locking)'), ('L6-20R', 'NEMA L6-20R (240V 20A locking)'), ('L6-30R', 'NEMA L6-30R (240V 30A locking)'), ('14-30R', 'NEMA 14-30R (240V 30A)'), ('14-50R', 'NEMA 14-50R (240V 50A)'), ('C13', 'IEC C13 (PDU appliance, ≤10A)'), ('C14', 'IEC C14 (PDU inlet, ≤10A)'), ('C19', 'IEC C19 (PDU high-current, ≤16A)'), ('C20', 'IEC C20 (PDU high-current inlet, ≤16A)'), ('USB', 'USB charging'), ('OTHER', 'Other'), ('other', 'Other (legacy lowercase)')], default='5-15R', max_length=20),
        ),
        migrations.AlterField(
            model_name='powerport',
            name='port_type',
            field=models.CharField(choices=[('5-15R', 'NEMA 5-15R (120V 15A)'), ('5-20R', 'NEMA 5-20R (120V 20A)'), ('6-15R', 'NEMA 6-15R (240V 15A)'), ('6-20R', 'NEMA 6-20R (240V 20A)'), ('L5-15R', 'NEMA L5-15R (120V 15A locking)'), ('L5-20R', 'NEMA L5-20R (120V 20A locking)'), ('L5-30R', 'NEMA L5-30R (120V 30A locking)'), ('L6-20R', 'NEMA L6-20R (240V 20A locking)'), ('L6-30R', 'NEMA L6-30R (240V 30A locking)'), ('14-30R', 'NEMA 14-30R (240V 30A)'), ('14-50R', 'NEMA 14-50R (240V 50A)'), ('C13', 'IEC C13 (PDU appliance, ≤10A)'), ('C14', 'IEC C14 (PDU inlet, ≤10A)'), ('C19', 'IEC C19 (PDU high-current, ≤16A)'), ('C20', 'IEC C20 (PDU high-current inlet, ≤16A)'), ('USB', 'USB charging'), ('OTHER', 'Other'), ('other', 'Other (legacy lowercase)')], default='5-15R', max_length=20),
        ),
    ]
