# Generated by Django 5.1.15 on 2026-05-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical_circuits', '0008_powerport_iec_port_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpanel',
            name='breaker_type',
            field=models.CharField(blank=True, choices=[('SQUARE_D_QO', 'Square D QO (plug-on, 10kA)'), ('SQUARE_D_HOMELINE', 'Square D Homeline (plug-on, 10kA)'), ('EATON_CH', 'Eaton CH / Cutler-Hammer Classic'), ('EATON_BR', 'Eaton BR (residential)'), ('SIEMENS_QP', 'Siemens QP / Murray MP'), ('GE_Q_LINE', 'GE Q-Line / ABB Q-Line'), ('FEDERAL_PACIFIC', 'Federal Pacific Stab-Lok (legacy — replace)'), ('PUSHMATIC', 'Pushmatic / ITE-Bulldog (legacy)'), ('DIN_RAIL', 'IEC DIN-rail (C60 / industrial)'), ('OTHER', 'Other / unknown')], default='', help_text='Breaker family this panel accepts. Used to filter replacement sourcing and warn when a mismatched breaker is added.', max_length=30),
        ),
        migrations.AddField(
            model_name='powerpanel',
            name='numbering_direction',
            field=models.CharField(choices=[('top_down', 'Top-down (slot 1 at top)'), ('bottom_up', 'Bottom-up (slot 1 at bottom)')], default='top_down', help_text='Slot 1 location on the physical cabinet — top-down for most North American load centers, bottom-up for some industrial / European panels.', max_length=10),
        ),
    ]
