# Generated by Django 5.1.15 on 2026-05-18 17:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electrical_circuits", "0009_powerpanel_breaker_type_and_numbering"),
        ("inventory", "0059_add_maintenance_record"),
        ("loto", "0003_backfill_derived_energy_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disconnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human label (e.g., 'Dust collector disconnect — east wall').",
                        max_length=120,
                    ),
                ),
                (
                    "disconnect_type",
                    models.CharField(
                        choices=[
                            ("fused", "Fused safety switch"),
                            ("unfused", "Unfused safety switch"),
                            ("toggle", "Toggle / snap switch"),
                            ("integral", "Integral to the equipment"),
                            ("none", "No separate disconnect (breaker serves)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amperage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Switch rating in amps (informational; not enforced against load).",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "fuse_size",
                    models.CharField(
                        blank=True,
                        help_text="Fuse size string (e.g., '30A class J'). Only meaningful for fused type.",
                        max_length=20,
                    ),
                ),
                (
                    "is_lockable",
                    models.BooleanField(
                        default=True,
                        help_text="True if the switch accepts a lockout device for LOTO.",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="electrical_circuits/disconnects/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Flagged automatically when clean() detects an inconsistent combination (fused with no fuse_size, lockable integral/none, etc.).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        help_text="Upstream circuit this disconnect isolates.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disconnects",
                        to="electrical_circuits.powercircuit",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the disconnect is mounted. Nullable because 'integral' and 'none' types don't have a physical switch separate from the load.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disconnects",
                        to="inventory.location",
                    ),
                ),
                (
                    "required_loto_devices",
                    models.ManyToManyField(
                        blank=True,
                        help_text="LOTO devices required to safely isolate this disconnect. When set, LOTO resolution should prefer these over the upstream breaker's list.",
                        related_name="disconnects",
                        to="loto.lotodevice",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="poweroutlet",
            name="disconnect",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional upstream disconnect — set for receptacle circuits with a dedicated isolation switch (welder outlets, 240V loads).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="powered_outlets",
                to="electrical_circuits.disconnect",
            ),
        ),
        migrations.CreateModel(
            name="HardwiredConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "conductor_size",
                    models.CharField(
                        blank=True, help_text="Conductor gauge (e.g., '10 AWG').", max_length=20
                    ),
                ),
                (
                    "conductor_length_ft",
                    models.PositiveIntegerField(
                        blank=True, help_text="Approximate conductor run length in feet.", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardwired_connections",
                        to="inventory.asset",
                    ),
                ),
                (
                    "disconnect",
                    models.ForeignKey(
                        help_text="Required: every hardwired load resolves through a Disconnect.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hardwired_loads",
                        to="electrical_circuits.disconnect",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__name", "disconnect__label"],
            },
        ),
        migrations.AddIndex(
            model_name="disconnect",
            index=models.Index(fields=["circuit"], name="electrical__circuit_ce0daf_idx"),
        ),
        migrations.AddIndex(
            model_name="disconnect",
            index=models.Index(fields=["location"], name="electrical__locatio_27d1f2_idx"),
        ),
        migrations.AddIndex(
            model_name="disconnect",
            index=models.Index(fields=["disconnect_type"], name="electrical__disconn_de4c72_idx"),
        ),
        migrations.AddIndex(
            model_name="hardwiredconnection",
            index=models.Index(fields=["asset"], name="electrical__asset_i_98a112_idx"),
        ),
        migrations.AddIndex(
            model_name="hardwiredconnection",
            index=models.Index(fields=["disconnect"], name="electrical__disconn_8dfa20_idx"),
        ),
        migrations.AddConstraint(
            model_name="hardwiredconnection",
            constraint=models.UniqueConstraint(
                fields=("asset", "disconnect"),
                name="electrical_circuits_hardwiredconnection_unique_pair",
            ),
        ),
    ]
