# Generated by Django 5.1.15 on 2026-05-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electrical_circuits", "0011_drop_cable_powerport_hardwired"),
        ("loto", "0004_repoint_derived_from_to_breaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powerbreaker",
            name="required_loto_devices",
            field=models.ManyToManyField(
                blank=True,
                help_text="LOTO devices required to safely isolate this breaker. Propagates to AssetEnergySource rows derived from assets fed by this breaker.",
                related_name="breakers",
                to="loto.lotodevice",
            ),
        ),
    ]
