# Generated by Django 5.1.15 on 2026-05-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electrical_circuits", "0012_alter_powerbreaker_required_loto_devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerbreaker",
            name="critical_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not critical"),
                    ("fire_alarm", "Fire alarm"),
                    ("emergency_lighting", "Emergency lighting"),
                    ("exit_sign", "Exit sign"),
                    ("egress_door", "Egress door power"),
                    ("life_safety_other", "Life-safety (other)"),
                ],
                default="",
                help_text="Type of life-safety load (e.g., fire_alarm, emergency_lighting). Required when is_critical=True; ignored otherwise.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="powerbreaker",
            name="critical_note",
            field=models.TextField(
                blank=True,
                help_text="Free-text context for the critical flag — what's downstream, code reference, last inspection, recovery procedure if tripped.",
            ),
        ),
        migrations.AddField(
            model_name="powerbreaker",
            name="is_critical",
            field=models.BooleanField(
                default=False,
                help_text="Flags a life-safety circuit (fire alarm, emergency lighting, exit sign, egress door). Critical breakers render with a red warning badge and block / warn in LOTO planning.",
            ),
        ),
    ]
