# Generated by Django 5.1.15 on 2026-04-28 04:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Vendor business name", max_length=200)),
                (
                    "vendor_kind",
                    models.CharField(
                        choices=[
                            ("hvac", "HVAC"),
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("general", "General Contractor"),
                            ("landscaping", "Landscaping"),
                            ("security", "Security"),
                            ("pest_control", "Pest Control"),
                            ("fire_safety", "Fire Safety"),
                            ("roofing", "Roofing"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Service category — used to map TDLR license requirements to asset categories",
                        max_length=32,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                (
                    "tdlr_license_number",
                    models.CharField(
                        blank=True,
                        help_text="Texas Department of Licensing & Regulation license number, if required for this vendor kind",
                        max_length=64,
                    ),
                ),
                (
                    "tdlr_license_expires_at",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date of the TDLR license — sourcing should block expired vendors",
                        null=True,
                    ),
                ),
                (
                    "coi_provider",
                    models.CharField(
                        blank=True,
                        help_text="Certificate of Insurance carrier name",
                        max_length=200,
                    ),
                ),
                ("coi_policy_number", models.CharField(blank=True, max_length=128)),
                (
                    "coi_expires_at",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date of the certificate of insurance",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive vendors are hidden from sourcing UI but retained for historical work orders",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["vendor_kind", "is_active"], name="vendor_kind_active_idx"
                    ),
                    models.Index(fields=["is_active", "name"], name="vendor_active_name_idx"),
                ],
            },
        ),
    ]
