# Generated by Django 6.0.6 on 2026-06-09 20:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0067_asset_required_certifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vision_areas', to='inventory.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisionCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_fingerprint', models.CharField(db_index=True, max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_status', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='storage_vision.visionarea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisionCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('phone', 'Phone'), ('camera', 'Fixed camera')], max_length=16)),
                ('original_image', models.ImageField(upload_to='storage_vision/originals/')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('processor_version', models.CharField(blank=True, max_length=64)),
                ('markers_detected', models.JSONField(blank=True, default=list)),
                ('failure_reason', models.TextField(blank=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='storage_vision.visionarea')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='storage_vision.visioncamera')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='VisionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_code', models.CharField(max_length=64)),
                ('empty_low_confidence_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='storage_vision.visionarea')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vision_slots', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['area__name', 'marker_code'],
            },
        ),
        migrations.CreateModel(
            name='VisionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('empty', 'Empty'), ('low', 'Low'), ('full', 'Full'), ('unknown', 'Unknown')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('evidence_crop', models.ImageField(blank=True, null=True, upload_to='storage_vision/crops/')),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('suggested_action', models.CharField(choices=[('review_only', 'Review only'), ('reconcile_empty', 'Reconcile empty')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=16)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('last_duplicate_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='storage_vision.visioncapture')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='storage_vision.visionslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visionarea',
            index=models.Index(fields=['is_active', 'name'], name='storage_vis_is_acti_411f93_idx'),
        ),
        migrations.AddIndex(
            model_name='visioncamera',
            index=models.Index(fields=['is_active', 'name'], name='storage_vis_is_acti_12eb31_idx'),
        ),
        migrations.AddIndex(
            model_name='visioncapture',
            index=models.Index(fields=['status', '-received_at'], name='storage_vis_status_4a1cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='visioncapture',
            index=models.Index(fields=['area', '-received_at'], name='storage_vis_area_id_7772d7_idx'),
        ),
        migrations.AddIndex(
            model_name='visionslot',
            index=models.Index(fields=['marker_code'], name='storage_vis_marker__da5461_idx'),
        ),
        migrations.AddIndex(
            model_name='visionslot',
            index=models.Index(fields=['is_active', 'area'], name='storage_vis_is_acti_cd657a_idx'),
        ),
        migrations.AddConstraint(
            model_name='visionslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('marker_code',), name='unique_active_vision_slot_marker'),
        ),
        migrations.AddIndex(
            model_name='visionobservation',
            index=models.Index(fields=['status', '-created_at'], name='storage_vis_status_a4d167_idx'),
        ),
        migrations.AddIndex(
            model_name='visionobservation',
            index=models.Index(fields=['slot', 'status'], name='storage_vis_slot_id_ce2a91_idx'),
        ),
        migrations.AddIndex(
            model_name='visionobservation',
            index=models.Index(fields=['suggested_action', 'status'], name='storage_vis_suggest_ef7702_idx'),
        ),
        migrations.AddConstraint(
            model_name='visionobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('slot', 'suggested_action'), name='unique_pending_vision_obs_per_slot_action'),
        ),
    ]
