# Generated by Django 6.0.6 on 2026-06-10 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_alter_stockreconciliation_reason'),
        ('storage_vision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='storage_vision.visionobservation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockreconciliation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['observation', '-created_at'], name='storage_vis_observa_235967_idx'), models.Index(fields=['reviewer', '-created_at'], name='storage_vis_reviewe_e83b15_idx')],
            },
        ),
    ]
