# Generated by Django 4.2.26 on 2025-11-08 08:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0029_add_asset_part"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Device type name", max_length=50, unique=True),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("indicator", "Indicator/Status Light"),
                            ("badge_reader", "Badge Reader"),
                            ("epaper_screen", "E-Paper Screen"),
                            ("oled_screen", "OLED Screen"),
                            ("temperature_sensor", "Temperature Sensor"),
                            ("generic_input", "Generic Input"),
                            ("generic_output", "Generic Output"),
                            ("ac_relay", "AC Relay"),
                            ("power_measurement", "Power Measurement"),
                        ],
                        help_text="Device type code",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this device type"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this device type active?"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, help_text="When usage started"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, help_text="When usage ended", null=True),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration of usage in seconds", null=True
                    ),
                ),
                (
                    "power_consumption_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Power consumption during this session (kWh)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes about this usage session")),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being used",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_sessions",
                        to="inventory.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User using the asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_usage_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ESP32Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        help_text="MAC address of the ESP32 device (format: XX:XX:XX:XX:XX:XX)",
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="MAC address must be in format XX:XX:XX:XX:XX:XX",
                                regex="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Human-readable name for this device", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this device"),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True,
                        help_text="Current firmware version on the device",
                        max_length=50,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, help_text="Last time the device was seen online", null=True
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, help_text="Is the device currently online?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this device active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_type",
                    models.ForeignKey(
                        help_text="Type of device",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="forgekey.devicetype",
                    ),
                ),
            ],
            options={
                "ordering": ["mac_address"],
            },
        ),
        migrations.CreateModel(
            name="OperationalMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("classroom", "Classroom Mode"),
                            ("maintenance", "Maintenance Mode"),
                            ("locked_out", "Locked Out"),
                        ],
                        default="available",
                        help_text="Current operational mode",
                        max_length=20,
                    ),
                ),
                (
                    "classroom_mode_enabled",
                    models.BooleanField(
                        default=False, help_text="Is classroom mode currently enabled?"
                    ),
                ),
                (
                    "classroom_mode_enabled_at",
                    models.DateTimeField(
                        blank=True, help_text="When classroom mode was enabled", null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        help_text="Asset this mode applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_mode",
                        to="inventory.asset",
                    ),
                ),
                (
                    "classroom_mode_enabled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who enabled classroom mode",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classroom_modes_enabled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["asset"],
            },
        ),
        migrations.CreateModel(
            name="FirmwareVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Firmware version string", max_length=50, unique=True
                    ),
                ),
                (
                    "firmware_file",
                    models.FileField(
                        help_text="Firmware binary file", upload_to="forgekey/firmware/"
                    ),
                ),
                (
                    "signature",
                    models.TextField(help_text="Cryptographic signature of the firmware file"),
                ),
                (
                    "release_notes",
                    models.TextField(blank=True, help_text="Release notes for this version"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this firmware version active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this firmware",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmware_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        help_text="Device type this firmware is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmware_versions",
                        to="forgekey.devicetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("version", "device_type")},
            },
        ),
        migrations.CreateModel(
            name="DeviceLockout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "lockout_level",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("maintainer", "Maintainer"),
                            ("group_admin", "Group Admin"),
                            ("logistics_team", "Logistics Team"),
                            ("logistics_lead", "Logistics Lead"),
                            ("coo", "COO"),
                        ],
                        help_text="Permission level of the user who locked this out",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the lockout")),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unlocked_at",
                    models.DateTimeField(
                        blank=True, help_text="When this lockout was cleared", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this lockout currently active?"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset that is locked out",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lockouts",
                        to="inventory.asset",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this lockout",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lockouts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who unlocked this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lockouts_unlocked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-locked_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceFirmwareUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Update status",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, help_text="When update started", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When update completed", null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if update failed"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device to update",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmware_updates",
                        to="forgekey.esp32device",
                    ),
                ),
                (
                    "firmware_version",
                    models.ForeignKey(
                        help_text="Firmware version to install",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_updates",
                        to="forgekey.firmwareversion",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who requested this update",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmware_updates_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Role of this device for the asset (e.g., 'power_control', 'metering')",
                        max_length=100,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary device for controlling this asset?",
                    ),
                ),
                (
                    "power_off_delay_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Delay in seconds before removing power after device is disabled",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this device is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forgekey_devices",
                        to="inventory.asset",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="ESP32 device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to="forgekey.esp32device",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "-is_primary", "role"],
            },
        ),
        migrations.CreateModel(
            name="AssetAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("authorized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this authorization active?"),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes about this authorization")),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this authorization is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorizations",
                        to="inventory.asset",
                    ),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who granted this authorization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorizations_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User authorized to use this asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "user"],
            },
        ),
        migrations.CreateModel(
            name="PowerMeterReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "voltage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Voltage reading (V)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "current",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Current reading (A)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "power",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Power reading (W)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "energy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Energy reading (kWh)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this reading was taken"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this reading is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_readings",
                        to="inventory.asset",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Power measurement device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_readings",
                        to="forgekey.esp32device",
                    ),
                ),
                (
                    "usage_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usage session this reading belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="power_readings",
                        to="forgekey.deviceusage",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"], name="forgekey_po_device__e6d821_idx"
                    ),
                    models.Index(
                        fields=["asset", "timestamp"], name="forgekey_po_asset_i_9626cf_idx"
                    ),
                    models.Index(fields=["usage_session"], name="forgekey_po_usage_s_866913_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="esp32device",
            index=models.Index(fields=["mac_address"], name="forgekey_es_mac_add_7f2b3a_idx"),
        ),
        migrations.AddIndex(
            model_name="esp32device",
            index=models.Index(fields=["device_type"], name="forgekey_es_device__5a6464_idx"),
        ),
        migrations.AddIndex(
            model_name="esp32device",
            index=models.Index(fields=["is_online"], name="forgekey_es_is_onli_f8b583_idx"),
        ),
        migrations.AddIndex(
            model_name="deviceusage",
            index=models.Index(
                fields=["asset", "user", "started_at"], name="forgekey_de_asset_i_36ceb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceusage",
            index=models.Index(fields=["started_at"], name="forgekey_de_started_90ba18_idx"),
        ),
        migrations.AddIndex(
            model_name="devicelockout",
            index=models.Index(
                fields=["asset", "is_active"], name="forgekey_de_asset_i_1329c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicelockout",
            index=models.Index(fields=["locked_by"], name="forgekey_de_locked__481b17_idx"),
        ),
        migrations.AddIndex(
            model_name="devicefirmwareupdate",
            index=models.Index(fields=["device", "status"], name="forgekey_de_device__803112_idx"),
        ),
        migrations.AddIndex(
            model_name="devicefirmwareupdate",
            index=models.Index(fields=["status"], name="forgekey_de_status_2d8a88_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assetdevice",
            unique_together={("asset", "device")},
        ),
        migrations.AddIndex(
            model_name="assetauthorization",
            index=models.Index(
                fields=["asset", "user", "is_active"], name="forgekey_as_asset_i_13bdff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetauthorization",
            unique_together={("asset", "user")},
        ),
    ]
