# Generated by Django 5.1.15 on 2026-04-26 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0001_initial"),
        ("inventory", "0049_add_workordersubmission_source_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="esp32device",
            name="boot_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Last-reported boot counter from the device", null=True
            ),
        ),
        migrations.AddField(
            model_name="esp32device",
            name="enrollment_photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo captured at device enrollment for staff identification",
                null=True,
                upload_to="forgekey/enrollment_photos/",
            ),
        ),
        migrations.AddField(
            model_name="esp32device",
            name="free_heap",
            field=models.PositiveIntegerField(
                blank=True, help_text="Last-reported free heap (bytes) from the device", null=True
            ),
        ),
        migrations.AddField(
            model_name="esp32device",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="Last-reported IP address of the device", null=True
            ),
        ),
        migrations.AddField(
            model_name="esp32device",
            name="last_photo",
            field=models.ImageField(
                blank=True,
                help_text="Most-recent periodic surveillance photo from the device",
                null=True,
                upload_to="forgekey/device_photos/last/",
            ),
        ),
        migrations.AddField(
            model_name="esp32device",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Default location assignment (for sensor devices unbound to a specific asset)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forgekey_devices",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="firmwareversion",
            name="binary_url",
            field=models.URLField(
                blank=True,
                help_text="Override URL for the firmware binary; if blank, the firmware_file URL is used",
            ),
        ),
        migrations.AddField(
            model_name="firmwareversion",
            name="mandatory",
            field=models.BooleanField(
                default=False,
                help_text="If true, devices must apply this firmware before continuing normal operation",
            ),
        ),
        migrations.AddField(
            model_name="firmwareversion",
            name="sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hex digest of the firmware binary (auto-computed on save)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="code",
            field=models.CharField(
                choices=[
                    ("indicator", "Indicator/Status Light"),
                    ("badge_reader", "Badge Reader"),
                    ("epaper_screen", "E-Paper Screen"),
                    ("oled_screen", "OLED Screen"),
                    ("temperature_sensor", "Temperature Sensor"),
                    ("generic_input", "Generic Input"),
                    ("generic_output", "Generic Output"),
                    ("ac_relay", "AC Relay"),
                    ("power_measurement", "Power Measurement"),
                    ("people_counter", "People Counter"),
                    ("env_sensor", "Environmental Sensor"),
                    ("door_counter", "Door Counter"),
                ],
                help_text="Device type code",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ESP32DevicePhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="JPEG photo from the device", upload_to="forgekey/device_photos/"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the device captured the photo (device-supplied)",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the server received the photo"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device that uploaded this photo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="forgekey.esp32device",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-received_at"], name="forgekey_es_device__97c647_idx"
                    ),
                    models.Index(fields=["received_at"], name="forgekey_es_receive_67dc69_idx"),
                ],
            },
        ),
    ]
