# Generated by Django 5.1.15 on 2026-04-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0002_esp32device_boot_count_esp32device_enrollment_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmwareversion",
            name="signature",
            field=models.TextField(
                blank=True,
                help_text="base64(DER) ECDSA(P-256) signature over the firmware binary, computed on save when FORGEKEY_FIRMWARE_SIGNING_KEY is configured.",
            ),
        ),
    ]
