# Generated by Django 5.1.15 on 2026-05-01 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0004_seed_device_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccupancyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sensor_kind",
                    models.CharField(
                        help_text="Sensor kind extracted from the MQTT topic (e.g. 'people_counter')",
                        max_length=50,
                    ),
                ),
                (
                    "count_in",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="People entering during this event"
                    ),
                ),
                (
                    "count_out",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="People leaving during this event"
                    ),
                ),
                (
                    "event_timestamp_utc",
                    models.DateTimeField(
                        help_text="Device-supplied event time (UTC). Falls back to server time if absent."
                    ),
                ),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the backend persisted this event"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original MQTT message body, kept for forward compatibility",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device that published this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupancy_events",
                        to="forgekey.esp32device",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp_utc"],
                "indexes": [
                    models.Index(
                        fields=["device", "event_timestamp_utc"],
                        name="forgekey_oc_device__cd0d07_idx",
                    ),
                    models.Index(
                        fields=["event_timestamp_utc"], name="forgekey_oc_event_t_5dbaff_idx"
                    ),
                ],
            },
        ),
    ]
