# Generated by Django 5.1.15 on 2026-05-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0006_firmwaresigningkey"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="firmwaresigningkey",
            new_name="forgekey_fi_is_acti_625867_idx",
            old_name="forgekey_fi_is_acti_idx",
        ),
    ]
