# Generated by Django 5.1.15 on 2026-05-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0007_rename_forgekey_fi_is_acti_idx_forgekey_fi_is_acti_625867_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="esp32device",
            name="capabilities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of capability identifiers announced by firmware over the <prefix>/<mac>/capabilities MQTT topic (e.g. ['people_counter', 'status_led']). Refreshed on every retained announcement.",
            ),
        ),
        migrations.AddField(
            model_name="esp32device",
            name="capabilities_announced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the device last published its capability set.",
                null=True,
            ),
        ),
    ]
