# Generated by Django 5.1.15 on 2026-05-03 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0008_add_capabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        help_text="Logical command name, e.g. 'restart', 'blink', 'identify'.",
                        max_length=64,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Full MQTT payload published to the device."
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ack_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acked", "Acknowledged"),
                            ("error", "Error"),
                            ("timeout", "Timed out"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("ack_at", models.DateTimeField(blank=True, null=True)),
                ("ack_payload", models.JSONField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="forgekey.esp32device",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_commands_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-sent_at"], name="forgekey_de_device__a090c5_idx"
                    )
                ],
            },
        ),
    ]
