# Generated by Django 5.1.15 on 2026-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0010_forgekeyauditevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetype",
            name="code",
            field=models.CharField(
                choices=[
                    ("indicator", "Indicator/Status Light"),
                    ("badge_reader", "Badge Reader"),
                    ("epaper_screen", "E-Paper Screen"),
                    ("oled_screen", "OLED Screen"),
                    ("temperature_sensor", "Temperature Sensor"),
                    ("generic_input", "Generic Input"),
                    ("generic_output", "Generic Output"),
                    ("ac_relay", "AC Relay"),
                    ("power_measurement", "Power Measurement"),
                    ("people_counter", "People Counter"),
                    ("env_sensor", "Environmental Sensor"),
                    ("door_counter", "Door Counter"),
                    ("locker_latch", "Locker latch controller"),
                    ("door_latch", "Door latch controller"),
                    ("otp_keypad", "OTP keypad"),
                    ("led_strip", "WS2818 LED strip controller"),
                    ("reed_switch", "Door reed switch"),
                    ("ir_break", "Inventory IR-break sensor"),
                    ("mortise_key", "Mortise key (admin override) sensor"),
                ],
                help_text="Device type code",
                max_length=30,
                unique=True,
            ),
        ),
    ]
