# Generated by Django 5.1.15 on 2026-05-13 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0012_seed_locker_device_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateAuthority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, default="forgekey-root", max_length=64)),
                ("cert_pem", models.TextField()),
                ("encrypted_private_key", models.BinaryField()),
                ("key_kid", models.CharField(blank=True, max_length=64)),
                ("not_before", models.DateTimeField()),
                ("not_after", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="forgekey_ca_single_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="ESP32 unique chip identifier — the device-identity security boundary.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["device_id"],
                "indexes": [
                    models.Index(fields=["device_id"], name="forgekey_de_device__8ea778_idx"),
                    models.Index(fields=["status"], name="forgekey_de_status_b0cfda_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("serial", models.CharField(max_length=128, unique=True)),
                ("subject", models.CharField(help_text="RFC4514 subject DN.", max_length=512)),
                ("fingerprint_sha256", models.CharField(max_length=64, unique=True)),
                ("not_before", models.DateTimeField()),
                ("not_after", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issued_by",
                    models.CharField(
                        blank=True,
                        help_text="Issuer CA name at the time of issuance (audit breadcrumb).",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="forgekey.deviceidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="esp32device",
            name="identity",
            field=models.OneToOneField(
                blank=True,
                help_text="Per-chip device identity (set by /enroll/). MAC drops to inventory metadata once an identity is bound.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="esp32_device",
                to="forgekey.deviceidentity",
            ),
        ),
        migrations.CreateModel(
            name="DeviceEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("csr_pem", models.TextField()),
                ("nonce", models.CharField(blank=True, db_index=True, max_length=64)),
                ("unique_chip_id", models.CharField(blank=True, max_length=64)),
                ("mac_address", models.CharField(blank=True, max_length=32)),
                ("sensor_kind", models.CharField(blank=True, max_length=50)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("chip_info", models.JSONField(blank=True, default=dict)),
                ("boot_count", models.PositiveIntegerField(blank=True, null=True)),
                ("free_heap", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("flash_memory_id", models.CharField(blank=True, max_length=64)),
                (
                    "token_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hex of the provisioning token used (full digest).",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("issued", "Issued"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="forgekey/enrollment_photos/"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forgekey_enrollments_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="forgekey.devicecertificate",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="forgekey.deviceidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-requested_at"], name="forgekey_de_status_830952_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="devicecertificate",
            index=models.Index(
                fields=["fingerprint_sha256"], name="forgekey_de_fingerp_570fa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecertificate",
            index=models.Index(
                fields=["device", "-created_at"], name="forgekey_de_device__92649b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecertificate",
            index=models.Index(fields=["revoked_at"], name="forgekey_de_revoked_da6515_idx"),
        ),
    ]
