# Generated by Django 6.0.5 on 2026-05-29 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgekey', '0014_epaperdisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaperdisplay',
            name='device',
            field=models.OneToOneField(blank=True, help_text='ESP32 driving the panel. Nullable for HTTPS-only ePaper devices that self-register by display_id and never enroll via the MAC-based MQTT pathway.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epaper_display', to='forgekey.esp32device'),
        ),
    ]
