# Generated by Django 6.0.5 on 2026-05-31 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0015_alter_epaperdisplay_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sensor_kind",
                    models.CharField(
                        help_text="Sensor kind extracted from the MQTT topic (e.g. 'temperature_sensor')",
                        max_length=50,
                    ),
                ),
                ("temperature_c", models.FloatField(help_text="Temperature in degrees Celsius")),
                (
                    "humidity_percent",
                    models.FloatField(
                        blank=True,
                        help_text="Relative humidity (0-100%), if the sensor reports it",
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the backend persisted this reading",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original MQTT message body, kept for forward compatibility",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device that published this reading",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_readings",
                        to="forgekey.esp32device",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "recorded_at"], name="forgekey_te_device__e7541b_idx"
                    )
                ],
            },
        ),
    ]
