# Generated by Django 6.0.5 on 2026-05-31 15:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0016_temperaturereading"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmwareRollout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional operator label for the campaign.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "batch_size_percent",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Percent of the target fleet to dispatch per wave (1-100).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Minimum minutes between waves.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_advanced_at",
                    models.DateTimeField(
                        blank=True, help_text="When the most recent wave was dispatched.", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmware_rollouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firmware_version",
                    models.ForeignKey(
                        help_text="Firmware version this campaign is rolling out.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollouts",
                        to="forgekey.firmwareversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="devicefirmwareupdate",
            name="rollout",
            field=models.ForeignKey(
                blank=True,
                help_text="Rollout campaign that dispatched this update, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="device_updates",
                to="forgekey.firmwarerollout",
            ),
        ),
    ]
