# Generated by Django 6.0.5 on 2026-06-01 00:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0017_firmwarerollout_devicefirmwareupdate_rollout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmwareBuild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pio_env",
                    models.CharField(
                        help_text="PlatformIO environment to build (e.g. 'seeed_xiao_esp32s3').",
                        max_length=100,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        default="main",
                        help_text="Git ref (branch / tag / commit) of the ForgeKey repo to build.",
                        max_length=200,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version string assigned to the resulting FirmwareVersion.",
                        max_length=50,
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(
                        default=False, help_text="Mark the built FirmwareVersion mandatory."
                    ),
                ),
                ("release_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("building", "Building"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "ca_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the active CA cert injected into this build (audit).",
                        max_length=64,
                    ),
                ),
                (
                    "commit_sha",
                    models.CharField(
                        blank=True, help_text="Resolved commit the worker built.", max_length=64
                    ),
                ),
                (
                    "log",
                    models.TextField(blank=True, help_text="Build log (git + pio output, tail)."),
                ),
                ("error_message", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device_type",
                    models.ForeignKey(
                        help_text="Target device type the built firmware is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmware_builds",
                        to="forgekey.devicetype",
                    ),
                ),
                (
                    "firmware_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The FirmwareVersion produced on success.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="builds",
                        to="forgekey.firmwareversion",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmware_builds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
    ]
