# Generated by Django 6.0.5 on 2026-06-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgekey', '0020_epaper_firmware_rollout'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaperdisplay',
            name='battery_available',
            field=models.BooleanField(blank=True, help_text='Tri-state: null = no health report received yet, True = panel has a battery sensor and reported a percent, False = panel explicitly reports no battery telemetry available.', null=True),
        ),
        migrations.AddField(
            model_name='epaperdisplay',
            name='battery_unavailable_reason',
            field=models.CharField(blank=True, help_text="When battery_available is False, the reason code the firmware supplied (e.g. 'battery_adc_not_configured'). Surfaced as a tooltip on the dashboard.", max_length=64),
        ),
        migrations.AddField(
            model_name='epaperdisplay',
            name='last_health_at',
            field=models.DateTimeField(blank=True, help_text='When the panel last POSTed a /health/ envelope (regardless of whether battery telemetry was included).', null=True),
        ),
    ]
