# Generated by Django 6.0.5 on 2026-06-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgekey', '0020_epaper_firmware_rollout'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaperdisplay',
            name='event_face_weight',
            field=models.PositiveSmallIntegerField(default=2, help_text='Relative weight of the reservation face in the rotation when both faces are eligible.'),
        ),
        migrations.AddField(
            model_name='epaperdisplay',
            name='pm_face_weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Relative weight of the PM face in the rotation when both faces are eligible.'),
        ),
        migrations.AddField(
            model_name='epaperdisplay',
            name='rotation_counter',
            field=models.PositiveBigIntegerField(default=0, help_text='Monotonic count of image renders since boot, used as the modulo input for the event/pm rotation. Advanced server-side on each render.'),
        ),
    ]
