# Generated by Django 6.0.6 on 2026-06-24 06:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0022_epaperdisplay_battery_available_and_more"),
        ("inventory", "0070_workorder_additional_maintenance_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgekeyauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("authorization_grant", "Authorization granted"),
                    ("authorization_revoke", "Authorization revoked"),
                    ("lockout_create", "Device locked out"),
                    ("lockout_unlock", "Device unlocked"),
                    ("firmware_request", "Firmware update requested"),
                    ("indicator_bind", "Indicator bound"),
                    ("indicator_unbind", "Indicator unbound"),
                    ("indicator_sync", "Indicator synced"),
                    ("indicator_test", "Indicator test sent"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="RoomOperationalMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In use"),
                            ("unavailable", "Unavailable"),
                            ("locked_out", "Locked out"),
                            ("classroom", "In use for a class"),
                        ],
                        default="available",
                        help_text="Admin-set operational status for the room",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.OneToOneField(
                        help_text="Room this operational mode applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_mode",
                        to="inventory.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last set this room mode",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_operational_modes_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["location"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In use"),
                            ("unavailable", "Unavailable"),
                            ("locked_out", "Locked out"),
                            ("classroom", "In use for a class"),
                        ],
                        help_text="Most recently pushed status (debounce / UI display)",
                        max_length=20,
                    ),
                ),
                (
                    "last_presentation",
                    models.JSONField(
                        blank=True,
                        help_text="Most recently pushed set_indicator payload (debounce / UI display)",
                        null=True,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the indicator was last pushed an update",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset whose derived status drives the light (XOR location)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_bindings",
                        to="inventory.asset",
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        help_text="Indicator-type device whose light reflects the target status",
                        limit_choices_to={"device_type__code": "indicator"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_binding",
                        to="forgekey.esp32device",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Room whose manual status drives the light (XOR asset)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_bindings",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("asset__isnull", False), ("location__isnull", True)),
                            models.Q(("asset__isnull", True), ("location__isnull", False)),
                            _connector="OR",
                        ),
                        name="indicatorbinding_asset_xor_location",
                    )
                ],
            },
        ),
    ]
