# Generated by Django 6.0.6 on 2026-06-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0023_alter_forgekeyauditevent_action_roomoperationalmode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetauthorization",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiry; a past value makes the authorization inactive.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="forgekeyauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("authorization_grant", "Authorization granted"),
                    ("authorization_revoke", "Authorization revoked"),
                    ("lockout_create", "Device locked out"),
                    ("lockout_unlock", "Device unlocked"),
                    ("firmware_request", "Firmware update requested"),
                    ("indicator_bind", "Indicator bound"),
                    ("indicator_unbind", "Indicator unbound"),
                    ("indicator_sync", "Indicator synced"),
                    ("indicator_test", "Indicator test sent"),
                    ("access_granted", "Access granted"),
                    ("access_denied", "Access denied"),
                    ("session_ended", "Usage session ended"),
                    ("badge_enrolled", "Badge enrolled"),
                ],
                max_length=32,
            ),
        ),
    ]
