# Generated by Django 6.0.6 on 2026-07-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forgekey", "0027_backfill_enrolled_esp32devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="esp32device",
            name="indicator_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Last-reported indicator/status-LED sub-state, parsed from the ``indicator`` field of the device's status message. Normalized ``{'color': <str>, 'pattern': <str|None>}`` — empty until the firmware reports it.",
            ),
        ),
        migrations.AddField(
            model_name="esp32device",
            name="relay_channels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Last-reported power-relay channel states, parsed from the ``power_relay.channels`` sub-state of the device's status message (ga-40w live-state). Normalized list of ``{'channel': <1-indexed int>, 'on': <bool>}`` — empty until the firmware reports it.",
            ),
        ),
    ]
