# Generated by Django 5.1.15 on 2026-04-28 04:09

import django.core.validators
import django.db.models.deletion
import maintenance_orders.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0050_add_asset_problem_photo"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirdPartyWorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short summary of the work to be performed", max_length=200
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("major_repair", "Major Repair"),
                            ("buildout", "Buildout"),
                            ("building_emergency", "Building Emergency"),
                        ],
                        default="standard",
                        max_length=32,
                    ),
                ),
                (
                    "is_emergency",
                    models.BooleanField(
                        default=False,
                        help_text="Denormalized fast-path flag for Building Emergency dispatch. Bypasses standard NTE approval and 3-quote sourcing.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("sourcing", "Sourcing"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("validated", "Validated"),
                            ("financial_review", "Financial Review"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=32,
                    ),
                ),
                (
                    "nte_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Not-To-Exceed amount approved by SIG. Null for emergency 'blank check' work.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "par_cost_buffer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Absolute par-cost variance auto-approved without re-review. Phase 3 reconciliation also enforces a 15%-of-NTE relative cap.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "actual_invoice_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final invoiced total. Set during Step 6 financial reconciliation.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "dispatch_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Flat truck-roll / dispatch fee. Auto-split equally across all ThirdPartyWorkOrderAsset rows during reconciliation (Phase 3).",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("downtime_start", models.DateTimeField(blank=True, null=True)),
                ("downtime_end", models.DateTimeField(blank=True, null=True)),
                (
                    "keyfob_id",
                    models.CharField(
                        blank=True,
                        help_text="Keyfob checked out to the vendor for site access. Phase 5 enforces return before closure.",
                        max_length=64,
                    ),
                ),
                (
                    "warranty_recovery",
                    models.BooleanField(
                        default=False,
                        help_text="Set by Phase 2 warranty gate when costs are recoverable under active warranty",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Customer/SIG-visible notes about the work"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal Ops notes — not surfaced to vendors or SIG dashboards",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary asset this work order targets. Required for SIG work; may be null for Building Emergency. Multi-asset distribution is captured via ThirdPartyWorkOrderAsset.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="third_party_work_orders",
                        to="inventory.asset",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_third_party_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shadow_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ops staff member shadowing the vendor on-site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shadowed_third_party_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor performing the work",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyWorkOrderAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "share_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Share of the WO's total cost allocated to this asset (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="third_party_work_order_links",
                        to="inventory.asset",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_links",
                        to="maintenance_orders.thirdpartyworkorder",
                    ),
                ),
            ],
            options={
                "ordering": ["work_order", "-share_pct"],
            },
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Assets among which costs are distributed for multi-asset WOs",
                related_name="distributed_third_party_work_orders",
                through="maintenance_orders.ThirdPartyWorkOrderAsset",
                to="inventory.asset",
            ),
        ),
        migrations.CreateModel(
            name="ThirdPartyWorkOrderAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=maintenance_orders.models._attachment_upload_path),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("fsr", "Field Service Report"),
                            ("photo", "Photo"),
                            ("quote", "Quote"),
                            ("paper_form", "Paper Form"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_third_party_wo_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="maintenance_orders.thirdpartyworkorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="thirdpartyworkorderasset",
            index=models.Index(fields=["work_order"], name="tpwo_link_wo_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyworkorderasset",
            index=models.Index(fields=["asset"], name="tpwo_link_asset_idx"),
        ),
        migrations.AddConstraint(
            model_name="thirdpartyworkorderasset",
            constraint=models.UniqueConstraint(
                fields=("work_order", "asset"), name="tpwo_unique_asset_per_wo"
            ),
        ),
        migrations.AddIndex(
            model_name="thirdpartyworkorder",
            index=models.Index(fields=["status", "-opened_at"], name="tpwo_status_opened_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyworkorder",
            index=models.Index(fields=["vendor", "status"], name="tpwo_vendor_status_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyworkorder",
            index=models.Index(fields=["is_emergency", "status"], name="tpwo_emerg_status_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyworkorder",
            index=models.Index(fields=["asset", "-opened_at"], name="tpwo_asset_opened_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyworkorderattachment",
            index=models.Index(fields=["work_order", "kind"], name="tpwoa_wo_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyworkorderattachment",
            index=models.Index(fields=["kind", "-uploaded_at"], name="tpwoa_kind_upload_idx"),
        ),
    ]
