# Generated by Django 5.1.15 on 2026-04-28 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0050_add_asset_problem_photo"),
        ("maintenance_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetWarranty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "install_date",
                    models.DateField(
                        help_text="Date the warranty coverage begins (typically install or purchase date)"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of coverage in days. Either duration_days or end_date must be provided; the other is computed automatically.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Computed from install_date + duration_days when blank. Set explicitly to override (e.g., extended warranty).",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Warranty provider — usually the manufacturer or extended-warranty carrier",
                        max_length=200,
                    ),
                ),
                ("policy_number", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warranties",
                        to="inventory.asset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "asset warranties",
                "ordering": ["-end_date"],
                "indexes": [
                    models.Index(fields=["asset", "-end_date"], name="aw_asset_end_idx"),
                    models.Index(fields=["end_date"], name="aw_end_idx"),
                ],
            },
        ),
    ]
