# Generated by Django 5.1.15 on 2026-04-28 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_orders", "0002_assetwarranty"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="emergency_authorized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="emergency_authorized_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Logistics user who authorized emergency bypass of NTE / 3-quote rules. Re-authorization required every 24h via EmergencyAuthorization audit rows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emergency_authorized_third_party_work_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="nte_set_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="nte_set_by",
            field=models.ForeignKey(
                blank=True,
                help_text="SIG admin who set the NTE during Step 1 intake",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nte_set_third_party_work_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="quote_waiver_reason",
            field=models.TextField(
                blank=True,
                help_text="Justification for waiving the 3-quote requirement (audit log)",
            ),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="quote_waiver_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="quote_waiver_signed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Authorized user who signed off on bypassing the 3-quote requirement. Persisted with reason + timestamp for audit.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_waived_third_party_work_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="total_downtime",
            field=models.DurationField(
                blank=True,
                help_text="Persisted total downtime computed at validation. Equals downtime_end - downtime_start once Ops signs off in Step 5.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="variance_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not evaluated"),
                    ("auto_approved", "Auto-approved within par buffer"),
                    ("blocked", "Blocked — exceeds par/15% NTE"),
                ],
                default="",
                help_text="Outcome of Step 6 financial reconciliation. Set when advance_to_financial_review is called. 'blocked' prevents closure.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorderasset",
            name="allocated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost share materialized at reconciliation: (actual_invoice_total - dispatch_fee) * share_pct + dispatch_fee/N. Persisted on advance_to_financial_review.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.CreateModel(
            name="EmergencyAuthorization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("authorized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="24 hours after authorized_at unless explicitly revoked"
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_authorizations",
                        to="maintenance_orders.thirdpartyworkorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-authorized_at"],
                "indexes": [
                    models.Index(
                        fields=["work_order", "-authorized_at"], name="tpwo_emerg_auth_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyWorkOrderQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quoted total in dollars",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_third_party_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="third_party_quotes",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="maintenance_orders.thirdpartyworkorder",
                    ),
                ),
            ],
            options={
                "ordering": ["work_order", "amount"],
                "indexes": [
                    models.Index(fields=["work_order"], name="tpwo_quote_wo_idx"),
                    models.Index(fields=["vendor"], name="tpwo_quote_vendor_idx"),
                ],
            },
        ),
    ]
