# Generated by Django 5.1.15 on 2026-04-28 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_orders", "0003_thirdpartyworkorder_emergency_authorized_at_and_more"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="keyfob_returned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the vendor returns the keyfob. Closure is blocked while keyfob_id is set but keyfob_returned_at is null.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="keyfob_returned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who recorded the keyfob return.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="keyfob_returned_third_party_work_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RecoveryTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Recoverable amount — typically the WO's actual_invoice_total at closure.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                (
                    "assigned_group",
                    models.CharField(
                        default="Logistics",
                        help_text="Auth Group name responsible for working this task.",
                        max_length=64,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_recovery_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_tasks",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_tasks",
                        to="maintenance_orders.thirdpartyworkorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="rt_status_created_idx"),
                    models.Index(fields=["assigned_group", "status"], name="rt_group_status_idx"),
                    models.Index(fields=["work_order"], name="rt_wo_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyWorkOrderAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("transition", "State transition"),
                            ("variance_override", "Variance override"),
                            ("emergency_auth", "Emergency authorization"),
                            ("emergency_validation", "Emergency validation"),
                            ("keyfob_return", "Keyfob return"),
                            ("quote_waiver", "Quote waiver"),
                        ],
                        max_length=32,
                    ),
                ),
                ("old_state", models.CharField(blank=True, max_length=32)),
                ("new_state", models.CharField(blank=True, max_length=32)),
                ("notes", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Action-specific payload (variance amounts, auth ids, etc).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action; null for system events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="third_party_wo_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="maintenance_orders.thirdpartyworkorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["work_order", "-created_at"], name="tpwo_audit_wo_idx"),
                    models.Index(fields=["action", "-created_at"], name="tpwo_audit_action_idx"),
                ],
            },
        ),
    ]
