# Generated by Django 5.1.15 on 2026-04-29 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0051_add_workordersubmission_kind_and_tpwo"),
        ("maintenance_orders", "0004_thirdpartyworkorder_keyfob_returned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdpartyworkorder",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location this work order targets. Set when the WO was promoted from a LocationProblem (non-asset complaint such as a leak or broken door). Optional for asset-rooted work.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="third_party_work_orders",
                to="inventory.location",
            ),
        ),
    ]
