# Generated by Django 5.1.15 on 2026-04-30 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0054_add_workorder_validation_and_review_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LOTODevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("padlock", "Padlock"),
                            ("hasp", "Hasp"),
                            ("tag", "Tag"),
                            ("key", "Key"),
                            ("valve_cover", "Valve cover"),
                            ("breaker_lock", "Breaker lock"),
                            ("plug_lock", "Plug lock"),
                            ("other", "Other"),
                        ],
                        default="padlock",
                        help_text="Kind of lockout device.",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human label or serial (e.g. 'PAD-001', 'red tag #12').",
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In use"),
                            ("missing", "Missing"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who currently has the device checked out.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loto_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the device is normally stored.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loto_devices",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["device_type", "label"],
            },
        ),
        migrations.CreateModel(
            name="AssetEnergySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("electrical", "Electrical"),
                            ("hydraulic", "Hydraulic"),
                            ("pneumatic", "Pneumatic"),
                            ("mechanical", "Mechanical / stored motion"),
                            ("thermal", "Thermal"),
                            ("chemical", "Chemical"),
                            ("gravitational", "Gravitational / suspended load"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "magnitude",
                    models.CharField(
                        blank=True,
                        help_text="Human description of the magnitude (e.g. '240V', '80psi').",
                        max_length=80,
                    ),
                ),
                (
                    "isolation_point",
                    models.CharField(
                        blank=True,
                        help_text="Where to isolate (e.g. 'Panel A breaker 12', 'red valve behind machine').",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_sources",
                        to="inventory.asset",
                    ),
                ),
                (
                    "required_devices",
                    models.ManyToManyField(
                        blank=True,
                        help_text="LOTO devices required to isolate this source.",
                        related_name="energy_sources",
                        to="loto.lotodevice",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_id", "source_type"],
            },
        ),
        migrations.AddIndex(
            model_name="lotodevice",
            index=models.Index(fields=["status"], name="loto_lotode_status_12bff6_idx"),
        ),
        migrations.AddIndex(
            model_name="lotodevice",
            index=models.Index(fields=["location"], name="loto_lotode_locatio_3ab6f6_idx"),
        ),
        migrations.AddIndex(
            model_name="lotodevice",
            index=models.Index(fields=["assigned_to"], name="loto_lotode_assigne_7a90a6_idx"),
        ),
        migrations.AddConstraint(
            model_name="lotodevice",
            constraint=models.UniqueConstraint(
                fields=("device_type", "label"), name="loto_device_unique_label_per_type"
            ),
        ),
        migrations.AddIndex(
            model_name="assetenergysource",
            index=models.Index(fields=["asset"], name="loto_assete_asset_i_25e21b_idx"),
        ),
        migrations.AddIndex(
            model_name="assetenergysource",
            index=models.Index(fields=["source_type"], name="loto_assete_source__2edeb3_idx"),
        ),
    ]
