# Generated by Django 5.1.15 on 2026-05-05 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electrical_circuits", "0004_cable"),
        ("inventory", "0056_asset_is_critical"),
        ("loto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetenergysource",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Power cable this energy source was auto-derived from (oms-qc3). NULL for manual entries and for derived rows whose cable was later deleted (those rows are also marked status=historical).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_energy_sources",
                to="electrical_circuits.cable",
            ),
        ),
        migrations.AddField(
            model_name="assetenergysource",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("historical", "Historical (cable removed/decommissioned)"),
                ],
                default="active",
                help_text="Active = the source is current. Historical = the cable backing this derived source was decommissioned or removed; the row is preserved for audit instead of being deleted.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lotodevice",
            name="secured_breakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="PowerBreakers this device is required to lock out. Used by the LOTO derivation pipeline (oms-qc3) to populate AssetEnergySource.required_devices for any asset cabled downstream of the breaker.",
                related_name="lockout_devices",
                to="electrical_circuits.powerbreaker",
            ),
        ),
        migrations.AddIndex(
            model_name="assetenergysource",
            index=models.Index(fields=["status"], name="loto_assete_status_156767_idx"),
        ),
        migrations.AddIndex(
            model_name="assetenergysource",
            index=models.Index(fields=["derived_from"], name="loto_assete_derived_a3514a_idx"),
        ),
        migrations.AddConstraint(
            model_name="assetenergysource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("derived_from__isnull", False)),
                fields=("derived_from",),
                name="loto_energy_source_unique_per_cable",
            ),
        ),
    ]
