# Generated by Django 5.1.15 on 2026-05-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electrical_circuits", "0005_powerbreaker_required_loto_devices"),
        ("inventory", "0056_asset_is_critical"),
        ("loto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetenergysource",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Power cable this row was auto-derived from. NULL for manual entries (hydraulic, pneumatic, etc.) and for derived rows whose source cable was hard-deleted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_energy_sources",
                to="electrical_circuits.cable",
            ),
        ),
        migrations.AddField(
            model_name="assetenergysource",
            name="is_stale",
            field=models.BooleanField(
                default=False,
                help_text="True when the cable that derived this row was decommissioned or removed. Kept (rather than deleted) so the LOTO audit trail survives equipment moves.",
            ),
        ),
        migrations.AddIndex(
            model_name="assetenergysource",
            index=models.Index(fields=["derived_from"], name="loto_assete_derived_a3514a_idx"),
        ),
    ]
