# Generated by Django 5.1.15 on 2026-05-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0059_add_maintenance_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thermostat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human label (e.g., 'Wood shop north', 'Front office').",
                        max_length=120,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for safety-sign rendering. True when the kill-breaker chain could not be resolved (no controlled_asset, or the asset has no hardwired/cordset feed).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "controlled_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="The HVAC/RTU asset this thermostat commands. Used to derive the kill-breaker list on the location's safety sign.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlling_thermostats",
                        to="inventory.asset",
                    ),
                ),
                (
                    "controls_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which room this thermostat actually conditions — often equal to ``location``. Auto-defaults to ``location`` on save when blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlling_thermostats",
                        to="inventory.location",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Where the thermostat is mounted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thermostats",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["controls_location__name", "label"],
                "indexes": [
                    models.Index(fields=["location"], name="climate_the_locatio_37790c_idx"),
                    models.Index(
                        fields=["controls_location"], name="climate_the_control_a601f6_idx"
                    ),
                    models.Index(
                        fields=["controlled_asset"], name="climate_the_control_709ec8_idx"
                    ),
                ],
            },
        ),
    ]
