# Generated by Django 5.1.15 on 2026-05-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thermostat",
            name="needs_review",
            field=models.BooleanField(
                default=False,
                help_text="Flag for safety-sign rendering. True when the kill-breaker chain could not be resolved (no controlled_asset, or the asset has no breaker FK set).",
            ),
        ),
    ]
