# Generated by Django 6.0.5 on 2026-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_storage', '0003_storage_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstoragestint',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Generated QR code image for this stint. Encodes {FRONTEND_URL}/scan/project-storage/<stint_id>; regenerate from the warden detail page when FRONTEND_URL changes.', null=True, upload_to='project_storage/qrcodes/'),
        ),
    ]
