# Generated by Django 6.0.7 on 2026-07-31 17:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project_storage', '0004_projectstoragestint_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.PositiveSmallIntegerField(help_text='Pallet rack number — the leading digits of the code (1 in 1A1).', validators=[django.core.validators.MinValueValidator(1)])),
                ('level', models.CharField(help_text='Level on the rack — the letter in the code (A in 1A1). Stored upper-case. Early letters are ground-reachable, late letters are high.', max_length=1, validators=[django.core.validators.RegexValidator('^[A-Za-z]$', 'Level must be a single letter (A-Z).')])),
                ('position', models.PositiveSmallIntegerField(help_text='Position along the rack — the trailing digits of the code (1 in 1A1), numbered from South/East toward North/West.', validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(db_index=True, help_text='Canonical location code, computed from rack + level + position (e.g. 1A1).', max_length=16, unique=True)),
                ('requires_pallet_jack', models.BooleanField(default=False, help_text='This slot is too high to reach without a pallet jack.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive slots stay on file (their AprilTag ID is permanent) but are not offered for new reservations.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owning_group', models.ForeignKey(blank=True, help_text='Optional SIG this slot is reserved for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_slots', to='auth.group')),
            ],
            options={
                'ordering': ['rack', 'level', 'position'],
                'constraints': [models.UniqueConstraint(fields=('rack', 'level', 'position'), name='unique_storage_slot_components')],
            },
        ),
    ]
