# Generated by Django 6.0.7 on 2026-07-31 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_storage', '0005_storageslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstoragestint',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='Reservation slot in the racking. Authoritative over storage_location_name when set; blank for ad-hoc storage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stints', to='project_storage.storageslot'),
        ),
        migrations.AddConstraint(
            model_name='projectstoragestint',
            constraint=models.UniqueConstraint(condition=models.Q(('moved_to_purgatory_at__isnull', True), ('removed_at__isnull', True), ('slot__isnull', False)), fields=('slot',), name='unique_active_stint_per_slot'),
        ),
    ]
