# Generated by Django 6.0.7 on 2026-07-31 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project_storage', '0006_projectstoragestint_slot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('committee', 'Committee'), ('logistics', 'Logistics'), ('class', 'Class')], help_text='Which non-Project storage type holds the slot (C/L/E in the overview).', max_length=16)),
                ('occupant_label', models.CharField(blank=True, help_text='Free-text occupant for logistics/class assignments — an instructor, a class name, a crew.', max_length=120)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Staff member who made the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owning_group', models.ForeignKey(blank=True, help_text='The committee (SIG) holding this slot, for committee assignments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_assignments', to='auth.group')),
                ('slot', models.ForeignKey(help_text='The racking slot this assignment holds.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='project_storage.storageslot')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['slot', '-assigned_at'], name='project_sto_slot_id_c748f8_idx'), models.Index(fields=['storage_type'], name='project_sto_storage_e1f14f_idx'), models.Index(fields=['released_at'], name='project_sto_release_4c47e1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('slot',), name='unique_active_assignment_per_slot')],
            },
        ),
    ]
