# Generated by Django 5.1.15 on 2026-05-26 23:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0060_asset_breaker_disconnect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PMSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text='Short human label, e.g. "Replace HEPA filter".', max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional longer instructions or part numbers."
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        help_text="How often the task should be performed, in days."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive schedules are hidden from the PM board."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Which asset this task is performed on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pm_schedules",
                        to="inventory.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__name", "task_name"],
            },
        ),
        migrations.CreateModel(
            name="PMServiceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the service was performed. Defaults to now.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who performed the service. Null for anonymous kiosk entries.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_service_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        help_text="The recurring task this log entry satisfies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_logs",
                        to="preventive_maintenance.pmschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="pmschedule",
            constraint=models.UniqueConstraint(
                fields=("asset", "task_name"), name="unique_pm_schedule_per_asset_task"
            ),
        ),
    ]
