/**
 * AC-34 — Storage Vision operating loop (slice 10).
 *
 * From the spec:
 *
 *   Given the backend and frontend are running with storage vision
 *   enabled and test fixtures loaded
 *   When the Playwright smoke test configures an area and slot,
 *   uploads a fixture image with the slot marker, waits for
 *   processing, approves the pending observation, and opens the
 *   existing reorder queue
 *   Then the pending reorder created through the approved stock
 *   reconciliation is visible to staff
 *
 * Backend requirements:
 *   - STORAGE_VISION_ENABLED=true (gated writes return 503 otherwise)
 *   - CELERY_TASK_ALWAYS_EAGER=1 so process_capture runs inside the
 *     upload request (the CI box has no celery worker)
 *
 * Both env vars are wired in .github/workflows/ci.yml e2e-tests.
 *
 * The fixture image is generated by
 *   e2e/fixtures/storage-vision/generate_marker_fixture.py
 * (committed alongside the source PNG). The marker payload is
 * VIS-E2E-BOLT and the area below the marker is bright (~RGB 240)
 * so heuristic-v1 classifies the slot as empty with confidence > the
 * default 0.50 threshold → suggested_action=reconcile_empty →
 * approve writes a StockReconciliation, which (since stock falls to
 * 0 ≤ minimum_stock=5) auto-creates a ReorderRequest.
 */
import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  API_BASE_URL,
  checkBackendAvailable,
  createActiveMembershipForUser,
  createTestCategory,
  createTestInventoryItem,
  createTestLocation,
  createTestUser,
  loginUser,
  setAuthToken,
} from './fixtures';

const FIXTURE_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures/storage-vision/marker-VIS-E2E-BOLT.jpg',
);

interface SeedHandles {
  token: string;
  itemId: string;
  areaId: number;
  slotId: number;
}

async function seedStorageVision(token: string): Promise<SeedHandles> {
  const suffix = Date.now();
  const category = await createTestCategory(`E2E Vision Cat ${suffix}`, token);
  const inventoryLocation = await createTestLocation(
    `E2E Bin Shelf ${suffix}`,
    token,
  );
  const visionLocation = await createTestLocation(
    `E2E Shop Floor ${suffix}`,
    token,
  );
  const item = await createTestInventoryItem(
    {
      name: `E2E Vision Bolt ${suffix}`,
      category: category.id,
      location: inventoryLocation.id,
      current_stock: 8,
      minimum_stock: 5,
      reorder_quantity: 10,
    },
    token,
  );

  const areaResponse = await fetch(`${API_BASE_URL}/storage-vision/areas/`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      name: `E2E Bay ${suffix}`,
      location: visionLocation.id,
    }),
  });
  if (!areaResponse.ok) {
    throw new Error(
      `Seed: VisionArea create failed (${areaResponse.status}): ${await areaResponse.text()}`,
    );
  }
  const area = await areaResponse.json();

  const slotResponse = await fetch(`${API_BASE_URL}/storage-vision/slots/`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      area: area.id,
      item: item.id,
      marker_code: 'VIS-E2E-BOLT',
      empty_low_confidence_threshold: '0.50',
    }),
  });
  if (!slotResponse.ok) {
    throw new Error(
      `Seed: VisionSlot create failed (${slotResponse.status}): ${await slotResponse.text()}`,
    );
  }
  const slot = await slotResponse.json();

  return {
    token,
    itemId: item.id,
    areaId: area.id,
    slotId: slot.id,
  };
}

async function uploadFixtureCapture(
  token: string,
  areaId: number,
): Promise<number> {
  const body = new FormData();
  body.append('area', String(areaId));
  body.append(
    'original_image',
    new Blob([readFileSync(FIXTURE_PATH)], { type: 'image/jpeg' }),
    'fixture.jpg',
  );
  const response = await fetch(`${API_BASE_URL}/storage-vision/captures/`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}` },
    body,
  });
  if (response.status !== 202) {
    throw new Error(
      `Upload: expected 202, got ${response.status}: ${await response.text()}`,
    );
  }
  const capture = await response.json();
  return capture.id;
}

async function waitForProcessed(
  token: string,
  captureId: number,
  timeoutMs = 30_000,
): Promise<{ id: number; observation_id: number }> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const resp = await fetch(
      `${API_BASE_URL}/storage-vision/captures/${captureId}/`,
      { headers: { Authorization: `Bearer ${token}` } },
    );
    if (resp.ok) {
      const data = await resp.json();
      if (data.status === 'processed') {
        // Find the observation row for this capture so the test
        // can deep-link the review UI.
        const obsResp = await fetch(
          `${API_BASE_URL}/storage-vision/observations/?status=pending`,
          { headers: { Authorization: `Bearer ${token}` } },
        );
        if (obsResp.ok) {
          const obsBody = await obsResp.json();
          const rows = Array.isArray(obsBody) ? obsBody : obsBody.results || [];
          const match = rows.find(
            (r: { capture: number }) => r.capture === captureId,
          );
          if (match) {
            return { id: captureId, observation_id: match.id };
          }
        }
      }
      if (data.status === 'failed') {
        throw new Error(
          `Capture ${captureId} processing failed: ${data.failure_code} ${data.failure_reason}`,
        );
      }
    }
    await new Promise((r) => setTimeout(r, 250));
  }
  throw new Error(`Capture ${captureId} did not reach processed within ${timeoutMs}ms`);
}

test.describe('Storage Vision operating loop (AC-34)', () => {
  let staffToken: string;
  let backendAvailable = false;

  test.beforeAll(async () => {
    backendAvailable = await checkBackendAvailable();
    if (!backendAvailable) {
      console.warn(
        'Backend not available — storage-vision E2E will skip. Start backend on :8000.',
      );
      return;
    }
    const username = `vision-staff-${Date.now()}`;
    await createTestUser(username, 'visionpass123', `${username}@test.com`, true);
    await createActiveMembershipForUser(username, { isStaff: true });
    staffToken = await loginUser(username, 'visionpass123');
  });

  test('staff: configure → upload → process → approve → reorder visible', async ({
    page,
  }) => {
    test.skip(!backendAvailable, 'Backend not available');
    test.setTimeout(120_000);

    // --- given: backend has the fixtures, frontend will pick up the JWT
    const seed = await seedStorageVision(staffToken);
    const captureId = await uploadFixtureCapture(staffToken, seed.areaId);
    const processed = await waitForProcessed(staffToken, captureId);

    // --- when: the staff user opens the review queue scoped to this
    // capture and clicks Approve on the pending observation.
    await setAuthToken(page, staffToken);
    await page.goto(`/facilities/storage-vision/review?capture=${captureId}`);

    const approveBtn = page.getByTestId(`approve-${processed.observation_id}`);
    await expect(approveBtn).toBeVisible({ timeout: 15_000 });
    await approveBtn.click();

    // Slice-9 resolution alert quotes the new reconciliation + reorder.
    const alert = page.getByTestId('review-resolution-alert');
    await expect(alert).toBeVisible({ timeout: 15_000 });
    await expect(alert).toContainText(/Approved observation/);
    await expect(alert).toContainText(/reconciliation #/);
    await expect(alert).toContainText(/reorder created/);

    // --- then: the existing reorder queue (AdminDashboard) shows the
    // auto-created reorder request for the seeded inventory item.
    await page.goto('/inventory/admin');
    await page.waitForLoadState('networkidle');

    // The dashboard renders one <tr data-testid="reorder-row-{id}">
    // per pending request. The simplest assertion that proves
    // AC-34 is satisfied is "at least one row mentions the
    // seeded item by name".
    const reorderRows = page.locator('[data-testid^="reorder-row-"]');
    await expect(reorderRows.first()).toBeVisible({ timeout: 15_000 });
    await expect(reorderRows.filter({ hasText: 'E2E Vision Bolt' })).toHaveCount(
      1,
    );
  });
});
