{{- if .Values.redis.internal -}}
{{- $component := "redis" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oms.fullname" . }}-redis
  labels:
    {{- include "oms.componentLabels" (merge (dict "component" $component) .) | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "oms.componentSelectorLabels" (merge (dict "component" $component) .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oms.componentSelectorLabels" (merge (dict "component" $component) .) | nindent 8 }}
    spec:
      {{- include "oms.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: redis
          image: {{ include "oms.image" (dict "image" .Values.redis.image "registry" .Values.imageRegistry "tag" .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          {{- if .Values.redis.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-redis" (include "oms.fullname" .)) .Values.redis.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
