# Generated by Django 5.1.15 on 2026-04-21 00:35

import django.db.models.deletion
import django.utils.timezone
import screens.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0045_add_work_order_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text="URL-safe identifier used in the kiosk display URL (e.g. 'electronics-lab')", max_length=80, unique=True)),
                ('name', models.CharField(help_text='Human-readable screen name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Where this screen is located / its purpose')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this screen is currently in service')),
                ('rotation_interval_seconds', models.PositiveIntegerField(default=15, help_text='Seconds between slide rotations on the kiosk')),
                ('refresh_interval_seconds', models.PositiveIntegerField(default=60, help_text='Seconds between content refreshes from the server')),
                ('access_token', models.CharField(default=screens.models.generate_screen_token, help_text='Secret token included in the public kiosk URL', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_screens', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Physical location of the screen (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='inventory.location')),
                ('sig', models.ForeignKey(blank=True, help_text='Owning SIG/Committee — its admins may customize content blocks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScreenContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('tool_status', 'Tool Status'), ('asset_usage', 'Asset Usage'), ('custom_text', 'Custom Text / Rules Reminder'), ('announcement', 'Announcement / Class Slide'), ('weather', 'Weather'), ('traffic', 'Traffic'), ('member_count', 'Member Count'), ('board_meeting', 'Next Board Meeting')], max_length=40)),
                ('title', models.CharField(blank=True, help_text='Optional heading shown above the block', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Free-form body (used by custom_text / announcement blocks)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Block-specific configuration (e.g. location filter, asset ids)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (ascending)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Committee leaders can hide individual blocks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='screens.screen')),
            ],
            options={
                'ordering': ['screen', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('content_version', models.CharField(blank=True, help_text='Hash/version of the content the kiosk is currently showing', max_length=64)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='screens.screen')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Message body — shown on every active screen')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Show from this time (optional)', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Hide after this time (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['is_active'], name='screens_scr_is_acti_e769fd_idx'),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['sig'], name='screens_scr_sig_id_62e21e_idx'),
        ),
        migrations.AddIndex(
            model_name='screencontentblock',
            index=models.Index(fields=['screen', 'is_enabled'], name='screens_scr_screen__c947ce_idx'),
        ),
        migrations.AddIndex(
            model_name='screenheartbeat',
            index=models.Index(fields=['screen', '-reported_at'], name='screens_scr_screen__a3eed9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmessage',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='screens_sys_is_acti_d25573_idx'),
        ),
    ]
