# Generated by Django 5.1.15 on 2026-04-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screencontentblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("tool_status", "Tool Status"),
                    ("asset_usage", "Asset Usage"),
                    ("custom_text", "Custom Text / Rules Reminder"),
                    ("announcement", "Announcement / Class Slide"),
                    ("weather", "Weather"),
                    ("shared_weather", "Shared Weather"),
                    ("traffic", "Traffic"),
                    ("member_count", "Member Count"),
                    ("board_meeting", "Next Board Meeting"),
                ],
                max_length=40,
            ),
        ),
    ]
